### ISSUE TITLE
Instructions how to add functionality

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1018]
Once the new autogeneration of the C++ part is done we should add documentation on how functionality can be added.

**Comment by coderkalyan** [comment]
What's the new autogeneration of the C++ part? Just curious.

**Comment by JonasVautherin** [comment]
@coderkalyan: The goal is to auto-generate the whole gRPC logic from the proto files, and also the C++ headers. See here for the action plugin: https://github.com/mavlink/MAVSDK/pull/1017

**Comment by coderkalyan** [comment]
@JonasVautherin thats really cool! Can I help port anything else to autogenerated?

**Comment by JonasVautherin** [comment]
I don't think so, but thanks :slightly_smiling_face:. Would be nice to make some tests once they are there, though, to see if that does not break functionality! :innocent:

**Comment by julianoes** [comment]
This is being covered in https://github.com/mavlink/MAVSDK-docs/pull/219.
