### ISSUE TITLE
Add examples to CI?

### ISSUE THREAD

**Issue by coderkalyan** [mavlink/MAVSDK#1027]
I was thinking, as there is often minor refactoring (such as @JonasVautherin 's recent Action gRPC port), we should check if all the official MAVSDK examples at least compile. A lot of people use them to get started, and as our documentation is pretty much just the docstrings + examples, it would be good to make sure that they actually build :). What do you guys think?

Even better would be to have integration tests which test that the examples do what they are supposed to do, but this would be harder.

**Comment by julianoes** [comment]
Yes totally, we should do that!
