### ISSUE TITLE
mavlink_mission_item_to_mission_item_indices never cleared

### ISSUE THREAD

**Issue by Katawann** [mavlink/MAVSDK#1031]
_mission_data.mavlink_mission_item_to_mission_item_indices is never cleared which means we might have more mavlink_mission_item_to_mission_item_indices than we want if we download a list of items smaller than the previous one

https://github.com/mavlink/MAVSDK/blob/8afd4640cebf4fae242a9ff9650d354cebab2f48/src/plugins/mission/mission_impl.cpp#L241

**Comment by julianoes** [comment]
Thanks for the report.

**Comment by coderkalyan** [comment]
What's needed to fix this? Is it simply a matter of clear()ing the list before we start inserting into it?

**Comment by Katawann** [comment]
yes only that hehe. I'm not working with the last version of MAVSDK and I don't have the time to upgrade for now with my job but yes if you clear it everything is fine !

**Comment by coderkalyan** [comment]
Okay, if it's just clearing I can try to get a PR for this soon.
