### ISSUE TITLE
Is tune example working?

### ISSUE THREAD

**Issue by limhyon** [mavlink/MAVSDK#1035]
We are testing tune example, but it does not work at the moment.

**Comment by julianoes** [comment]
Oh yes, sorry about that.

It is not implemented on the PX4 side unless you use this PR: https://github.com/PX4/Firmware/pull/13158

**Comment by julianoes** [comment]
Soon this should be fixed on the PX4 side: https://github.com/PX4/Firmware/pull/13158

**Comment by julianoes** [comment]
This should work with latest master: https://github.com/PX4/Firmware/pull/13158.
