### ISSUE TITLE
Segmentation fault when request Euler angle

### ISSUE THREAD

**Issue by Katawann** [mavlink/MAVSDK#1043]
You have a segmentation fault when you request information about attitude like `set_rate_attitude_async`. Issue comes from the atan2f not know.

https://github.com/mavlink/MAVSDK/blob/67862f45ea86a33a1392183f94e9be423746b3ba/src/plugins/telemetry/math_conversions.cpp#L13

**Comment by julianoes** [comment]
Thanks for the issue. How can I reproduce this?

**Comment by Katawann** [comment]
Ouch, you can actually hehe. I found I had a atan2f in my code as well and if I remove it everything is working just fine... Sorry for the wrong report !
