### ISSUE TITLE
Rename everything `backend` to `mavsdk_server`

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1055]
At some point we should complete that rename.

**Comment by Siddharth1698** [comment]
Ill work on this one too.. :) 
Just let me briefly know what to be done.

**Comment by JonasVautherin** [comment]
Hmm that one will move files and may create conflicts. We should probably do it when other PRs are merged. Let's wait a bit :sweat_smile:

**Comment by Siddharth1698** [comment]
Sure. Just let me know when you are  ready. :-)
