### ISSUE TITLE
Rename all leftover `dc`, `dcsdk` etc. to `mavsdk`

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1056]
Back when MAVSDK was named differently we also called the instance of `Mavsdk` different. Leftovers are still sprinkled all over the integration tests and examples. It would be nice to get them cleaned up.

**Comment by Siddharth1698** [comment]
I am new to working on open source. If this is an manual and easy task just tell me ill work on it.

**Comment by julianoes** [comment]
Sure, that would be great. I would quickly wait until https://github.com/mavlink/MAVSDK/pull/1076 and https://github.com/mavlink/MAVSDK/pull/1075 are merged to avoid conflicts though.

Here is an example:
https://github.com/mavlink/MAVSDK/blob/242437c1b29d2e78cd60ca9383fda8d7b6858a6b/src/integration_tests/mission_cancellation.cpp#L26

It should just be `Mavsdk mavsdk;`.

**Comment by Siddharth1698** [comment]
Cool. Got this. I should do this completely on all the files right.

**Comment by JonasVautherin** [comment]
> Cool. Got this. I should do this completely on all the files right.

Ideally, yes. If it's too much work, it can be split in smaller chunks, too :blush: (like integration tests first, then examples, etc). Your call :wink:!

**Comment by Siddharth1698** [comment]
No prob. Got it.. :+1:
