### ISSUE TITLE
[Plugin] Forward RTK RTCM packets to FCU

### ISSUE THREAD

**Issue by AlexisTM** [mavlink/MAVSDK#112]
Adding a plugin which can send the RTCM updates of the base station to the UAVs. Thus replacing the need for QGroundcontrol for in-flight operation.

**Comment by julianoes** [comment]
Sounds like a good thing to have. Thanks for listing this.

**Comment by mrpollo** [comment]
For context, there's some information on a duplicate issue #534

**Comment by coderkalyan** [comment]
The most time consuming thing to develop here is probably a parser for GPS messages I think?

**Comment by coderkalyan** [comment]
Or... not, https://github.com/PX4/PX4-GPSDrivers this exists apparently

**Comment by AlexisTM** [comment]
The [rtk_ros](https://github.com/AlexisTM/rtk_ros) actually uses -an outdated version of- [PX4/GPSDrivers](https://github.com/PX4/PX4-GPSDrivers). We were using Mavros for that RTCM forward feature.

**Comment by Katawann** [comment]
And from this issue #1252, this is how QGC is handle it:

> This is the functionality in QGC.
> https://github.com/mavlink/qgroundcontrol/blob/master/src/GPS/RTCM/RTCMMavlink.cc#L24
> 
> It is sending GPS_RTCM_DATA.
> https://mavlink.io/en/messages/common.html#GPS_RTCM_DATA
