### ISSUE TITLE
UDP Bind Error After First Run v0.28

### ISSUE THREAD

**Issue by AlexKlimaj** [mavlink/MAVSDK#1135]
I have a MAVSDK C++ application built on v0.28. On first run, the application runs without issue. When I try to run the application again, I get a bind error.

`bind error: Address already in use (udp_connection.cpp:85)`

The application exits properly. This happens with and without calling the MAVSDK destructor before the application exits.

**Comment by JonasVautherin** [comment]
Is it new with v0.28? And would you happen to have a minimal example that we could run to reproduce the bug? :blush:

**Comment by AlexKlimaj** [comment]
Ignore this. The issue is in a non-MAVSDK portion of the code.
