### ISSUE TITLE
Problem running tools/generate_from_protos.sh

### ISSUE THREAD

**Issue by shakeebbb** [mavlink/MAVSDK#1139]
I'm getting the following error when I run 'tools/generate_from_protos.sh'.
I ran the configuration step before running the .sh script 'cmake -DBUILD_BACKEND=ON -Bbuild/default -H.' Anyone knows what am I missing?

-------------------------------
 Error
-------------------------------
'protoc-gen-mavsdk' not found in PATH

Make sure 'protoc-gen-mavsdk' is installed and available

**Comment by julianoes** [comment]
I think this changed, can you try:
```
pip3 install --user protoc-gen-mavsdk
```

**Comment by JonasVautherin** [comment]
It was called `protoc-gen-dcsdk`, but now it is `protoc-gen-mavsdk` indeed. The error message says that you need to install it, as @julianoes suggests above.
