### ISSUE TITLE
Undefined reference to custom plugin

### ISSUE THREAD

**Issue by KrisRadowski** [mavlink/MAVSDK#1161]
Hello,

I'm trying to use my simple MAVSDK plugin in my program, but I have problem defined here: https://discuss.px4.io/t/undefined-reference-to-custom-mavsdk-plugin/18070 which make using this plugin impossible. 
Please answer on forum.

**Comment by JonasVautherin** [comment]
It is very difficult to tell you what's wrong in the code just from the information you are giving. Can you show the code that is not compiling? Can you explain what you did that resulted in this error message?

**Comment by KrisRadowski** [comment]
added explanation and source code on forum :)
