### ISSUE TITLE
Reading GPS RAW data other than fused one

### ISSUE THREAD

**Issue by cjffly** [mavlink/MAVSDK#1198]
Hi,

I am trying to use MAVSDK to read a GPS height data from px4 (RTK connected), right now I am subscribing to telemetry-position: 
```
...
telemetry->subscribe_position([](Telemetry::Position position) {
z = position.absolute_altitude_m;
}
...
```
However, I did notice the height from the telemetry->position is fused and not accurate compare the raw RTK-GPS height. (I already set the `EKF2_HGT_MODE = GPS` ), the flight log show sometimes the fused height estimation is drifting around even my system is sitting on the ground:
![Screenshot from 2020-09-27 16-17-38](https://user-images.githubusercontent.com/11035640/94378414-63adb400-00de-11eb-9685-52fbffc12362.png)

My question is, is there a way for MAVSDK to read the mavlink message GPS_RAW_INT, other than the fused data from (telemetry->position) showed in the flight log above?

Best
C.J.

**Comment by julianoes** [comment]
Ok, that's an interesting observation. Now the question is what exactly you need from MAVSDK. Do you need the GPS height for debugging? I'm asking because to me it seems that this is more of a PX4 estimation and controls problem than a MAVSDK problem.

**Comment by cjffly** [comment]
I am using that GPS data as a reference point, which my other applications will rely on. I did get some answer from px4 perspective [here](https://discuss.px4.io/t/difference-between-gps-altitude-vs-fused-altiude-estimation/18784), seems the fused data also consider other sensors. 

So the question becomes is there any method for MAVSDK to access the raw data, not fused ones?

Also, I notice in MAVLink message definition, there are [GPS_RAW_INT](https://mavlink.io/en/messages/common.html#GPS_RAW_INT) and [GLOBAL_POSITION_INT](https://mavlink.io/en/messages/common.html#GLOBAL_POSITION_INT). Does MAVSDK provide any api to access that?

**Comment by julianoes** [comment]
@cjffly if you are using MAVSDK C++ you can use the Passthrough plugin to access any MAVLink message. So that would be one way. Alternatively, you can make a pull request to https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/telemetry/telemetry.proto to extend the Telemetry plugin to include an API for Raw GPS.

**Comment by julianoes** [comment]
This has been added, see https://github.com/mavlink/MAVSDK/pull/1333.
