### ISSUE TITLE
Inconsistent naming in Action API

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#120]
`set_max_speed()`
`get_max_speed_m_s()`
`set_takeoff_altitude`
`get_takeoff_altitude_m`

All names should either include units or none of them. I tend to favour "none", unless you plan on having different methods for each unit type.

**Comment by julianoes** [comment]
This has been fixed with the API changes that came with the gRPC auto-generation, see: https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/action/include/plugins/action/action.h.
