### ISSUE TITLE
Camera triggering in QGC survey missions not supported.

### ISSUE THREAD

**Issue by petergerten** [mavlink/MAVSDK#1202]
Currently there is no support for the `MAV_CMD_DO_SET_CAM_TRIGG_DIST` mission item, which is the standard way of triggering in a survey mission. Currently a survey mission imported with` import_qgroundcontrol_mission` will be executed but without the camera doing anything.

There is a test case for `MAV_CMD_DO_SET_CAM_TRIGG_DIST` in https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/mission/mission_import_qgc_test.cpp  but no implementation yet.

**Comment by julianoes** [comment]
That's right. Contributions are welcome :). The first question is what the MAVSDK API should look like for this.

**Comment by julianoes** [comment]
MissionRaw enables this.
