### ISSUE TITLE
Add position control to offboard

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#122]
Offboard currently only supports velocity inputs, however, it would be good to also have position control.

**Comment by hamishwillee** [comment]
Yes! I think we need to consider whether we can make this simpler than velocity control. For example, should DC handle the resending of messages? I would say yes. 

It might also be nice to have an API that completes when you reach the destination.

**Comment by julianoes** [comment]
Being addressed by #260.

**Comment by afwilkin** [comment]
Hello, I was looking for something similar to this (a method like set_velocity_body()) under offboard mode. Is this still being developed?

**Comment by julianoes** [comment]
This is done.

See: https://github.com/mavlink/MAVSDK/blob/7d7579659f8c12e3d9406a17eac96f3382153a5b/src/plugins/offboard/include/plugins/offboard/offboard.h#L208-L213

**Comment by hamishwillee** [comment]
And [here in the docs](https://mavsdk.mavlink.io/develop/en/api_reference/classmavsdk_1_1_offboard.html#classmavsdk_1_1_offboard_1a0bcbc79ba1277f0e7ad110f86b902cc7)

**Comment by Iko-Git** [comment]
Could you please give me a guideline for using _float mavsdk::Offboard::VelocityBodyYawspeed::forward_m_s {}_ into _ROS_ @hamishwillee @julianoes

**Comment by julianoes** [comment]
@Iko-Git please don't necrobump and create a new issue.
