### ISSUE TITLE
Research MAVLink statustexts

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#127]
https://github.com/dronecore/DroneCore/pull/119 adds support to print statustexts from the vehicle. 

This issue is to review the messages and determine whether they:
- Can remain FYI console logs
- Should be escalated to users
- Should result in code errors
- Require other actions. 

Also determine best place for handling messages (proposal is to defer to relevant plugins). 

Relevant discussion:  https://github.com/dronecore/DroneCore/pull/119#pullrequestreview-69720267

**Comment by JonasVautherin** [comment]
@julianoes is that solved now that we have the statustext in the telemetry plugin?

**Comment by julianoes** [comment]
This will improve once we have the event interface, closing for now.
