### ISSUE TITLE
Need to be able to set the System ID of Dronecore itself

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#128]
A MAVLink network could have multiple DroneCore instances. If this case needs to be addressed, then Dronecore needs a mechanism to set its own current system id.

**Comment by julianoes** [comment]
This has been fixed in the meantime.

There is now the API: https://github.com/mavlink/MAVSDK/blob/6434e0c6a7c25a3203d4652da13ea1944279beb1/src/core/mavsdk.h#L161-L169
