### ISSUE TITLE
mavsdk_server does not clean mission state after flight

### ISSUE THREAD

**Issue by petergerten** [mavlink/MAVSDK#1282]
If I want to start a second mission after a successful first mission - without restarting mavsdk_server -
the previous state persists.

Resulting in things like: is_mission_finished being true.
This happens even after clear_mission() and reuploading a new mission.

Is there any "cleanup" action I have to do that I am not aware about?

**Comment by julianoes** [comment]
Thanks for the issue. That doesn't sound like the correct behaviour. Which PX4 version are you using? And can you reproduce this against SITL?

**Comment by petergerten** [comment]
I am currently experiencing this with a customized PX4 firmware on the Yuneec H520 (in HITL). Will try in SITL with standard firmware now.

**Comment by petergerten** [comment]
I can reproduce it in SITL using PX4 Release 1.10.1

**Comment by julianoes** [comment]
@petergerten does it still happen with 1.11?

**Comment by L4ncelot** [comment]
@julianoes, I can confirm the same behavior with 1.11 in the SITL configuration.

**Comment by julianoes** [comment]
@L4ncelot would be great if you could test #1304.

**Comment by L4ncelot** [comment]
@julianoes #1304 works great, thank you for the support.
