### ISSUE TITLE
MavlinkCommandReceiver public access to private elements

### ISSUE THREAD

**Issue by yhabib29** [mavlink/MAVSDK#1284]
Hi,
We might have missed a mistake during corresponding pull request #1218 except if it was made in purpose.
The following lines in **_MavlinkCommandReceiver_** class seem to be public instead of private:
from https://github.com/mavlink/MAVSDK/blob/8d4ede5c08cfee476054b143d6146595550f9569/src/core/mavlink_commands.h#L214-L236

**Comment by julianoes** [comment]
Thanks for the note @yhabib29 .
