### ISSUE TITLE
UDP port parsing is weird

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1299]
Sometimes a connection added with `udp://portnumber` seems to work, and sometimes it seems to require `udp://:portnumber`. It's not quite clear why this happens.

**Comment by julianoes** [comment]
I just checked the unit tests and it looks like `udp://14540` gets evaluated to `UDP` with host `14540`.

@JonasVautherin what would you say should be the behaviour?
1. Reject `14540` because it is not of the form `num.num.num.num`?
2. Or just assume `14540` is the port number?

**Comment by JonasVautherin** [comment]
Same, I would favor 1 :+1:
