### ISSUE TITLE
Using multiple UDP remotes

### ISSUE THREAD

**Issue by yhabib29** [mavlink/MAVSDK#1319]
Hello,
I am trying to use MAVSDK to build 2 programs:
- A "client" program which runs on the companion computer on each drone.
- A GroundStation (GS) which can connect to each client.

I am using 2 UDP connections to connect each client to the GS. However, I can create only one UDP remote at a time otherwise it overwrites the existing system (is_single_system in mavsdk_impl.cpp).

How should I connect my GS to the other clients where each program is using Mavsdk.

**Comment by JonasVautherin** [comment]
I think you're right: right now MAVSDK can only add one remote. This would need to be updated in the implementation :+1:. Open for contributions, though :innocent:

**Comment by yhabib29** [comment]
All right, I will try to implement it in few days.
Thank you for the confirmation 👍🏼

**Comment by yhabib29** [comment]
To summarize the UDP connections system in Mavsdk.
- add_udp_connection("IP:PORT"):
    Create a new UdpConnection instance listening on IP:PORT.
    When the first message coming from a new endpoint (IP_ENDPOINT:PORT_ENDPOINT) is received, a new remote is created to send messages to IP_ENDPOINT:PORT_ENDPOINT.
    
- setup_udp_remote(IP, PORT):
    Create a new UdpConnection instance listening on 0.0.0.0:0 (port = 0 ??).
    Then a remote is created to send messages to IP:PORT

When sending a message, the mavsdk_impl iterates over all connections to send the message.
However, if one of the connections is a UDP connection and has no remote, the loop will break even if other connections could send the message.

see [add-multi-udp-remotes](habib29/MAVSDK/tree/add-multi-udp-remotes)

**Comment by yhabib29** [comment]
In addition, could it be interesting to add a vector of available system IDs for each connection ?

When sending a message to a specific system ID, this will allow to ignore connections which have never see the corresponding system ID.

The reason is that for radio connections, it might be better to preserve the bandwidth from useless messages.

**Comment by julianoes** [comment]
> However, if one of the connections is a UDP connection and has no remote, the loop will break even if other connections could send the message.

That sounds like a bug, right?

> When sending a message to a specific system ID, this will allow to ignore connections which have never see the corresponding system ID.

Yes, I think that would be a good optimization.

**Comment by yhabib29** [comment]
> That sounds like a bug, right?

Well, I think yes but I did not know if it was done in purpose ...
Here is the quick changes I did, but there might be a better solution.
``` 
bool MavsdkImpl::send_message(mavlink_message_t& message)
{
    std::lock_guard<std::mutex> lock(_connections_mutex);

    uint succesfull_emissions = 0;
    for (auto it = _connections.begin(); it != _connections.end(); ++it) {
        if ((**it).send_message(message)) {
            succesfull_emissions++;
        }
    }

    if (succesfull_emissions == 0) {
        LogErr() << "send fail";
        return false;
    }

    return true;
}
```


> Yes, I think that would be a good optimization.

All right, I thought of adding a std:vector<uint8_t> in Connection class protected attributes, and a method to check for system ID existence.
I will add it to the corresponding branch, and initialize a pull request.

**Comment by julianoes** [comment]
@JonasVautherin can you check this?

**Comment by julianoes** [comment]
#1331 was merged, closing.
