### ISSUE TITLE
[windows10] cannot connected to FCU

### ISSUE THREAD

**Issue by imindude** [mavlink/MAVSDK#1357]
I'm using MAVSDK in windows10. Actually already used in version 0.33.1, and worked good. But these days, update to 0.37.0 and have a trouble.

Here is my build command.

```
git clone https://github.com/mavlink/MAVSDK.git -b v0.37.0
cd MAVSDK
git submodule update --init --recursive
cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=build/install_debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -Bbuild/debug
cmake --build build/debug --config Debug --target install
```

And in my Qt, here is initial code.

```
  mav_sdk_ = std::make_shared<mavsdk::Mavsdk>();
  mavsdk::Mavsdk::Configuration configuration(mavsdk::Mavsdk::Configuration::UsageType::CompanionComputer);

  mav_sdk_->set_configuration(configuration);

  if (mav_sdk_->add_udp_connection(mavlink_port) == mavsdk::ConnectionResult::Success)
    mav_sdk_->subscribe_on_new_system(std::bind(&DroneControl::cbDiscoverNewSystem, this));
```

Here is my error message and debugging screenshot. Again, past version 0.33.1 works good in same code. This problem is only 0.37.0.

![error1](https://user-images.githubusercontent.com/5907865/111246336-6a5ac400-8649-11eb-8552-d8ea693f9e33.png)
![error2](https://user-images.githubusercontent.com/5907865/111246338-6b8bf100-8649-11eb-9d76-b31c3597a392.png)

I have no idea about this. My environment is,

**MSVC2019 Community latest version
Qt Opensource 5.15.2**

P.S.
In my compile of "gimbal_protocol_v1.cpp", it occurs error. So I modified "mavsdk_gimbal.vcxproj" file in build directory,

```
<AdditionalOptions>%(AdditionalOptions) -bigobj /Wv:18</AdditionalOptions>
```

Added "/Wv:18 " option.

**Comment by JonasVautherin** [comment]
Hmm :thinking:. Is it because `systems()` is called twice? Should it be more something like this?

```
auto systems = systems();

...

return std::any_of(systems.cbegin(), systems.cend, ...)
```

Would you mind trying that?

Note: if you copy-paste the code instead of sending a screenshot, we can actually copy-paste and edit it more easily :wink:.
