### ISSUE TITLE
Prebuild libraries for Windows

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1364]
We should also build and upload libraries for Windows like we do for Linux. We could distribute them just as a zip file.

**Comment by JonasVautherin** [comment]
If a Windows person reads this: [this is how we build for Windows in the CI](https://github.com/mavlink/MAVSDK/blob/develop/.github/workflows/main.yml#L487-L520), and you can see [here](https://github.com/mavlink/MAVSDK/blob/develop/.github/workflows/main.yml#L512-L520) that we already publish `mavsdk_server_bin.exe`.

We statically link the mavsdk libraries into `mavsdk_server_bin.exe` (see `-DBUILD_SHARED_LIBS=OFF` [here](https://github.com/mavlink/MAVSDK/blob/develop/.github/workflows/main.yml#L509)), but I guess we want to distribute `dll`s for this issue?

I guess a very valuable information would be to know what a Windows user would expect. I expect that we already build everything, we (or at least I) just need to know how to package it.
