### ISSUE TITLE
Windows release build not building

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1369]
I just tried to build in Release mode on Windows with MSVC 2019 and it failed with:

```
mavlink_mission_transfer_test.obj : error LNK2001: unresolved external symbol "class testing::internal::Mutex testing::
internal::g_gmock_mutex" (?g_gmock_mutex@internal@testing@@3VMutex@12@A) [C:\Users\Julian Oes\src\MAVSDK\build\release\
src\unit_tests_runner.vcxproj]
mavlink_mission_transfer_test.obj : error LNK2001: unresolved external symbol "class testing::internal::ThreadLocal<cla
ss testing::Sequence *> testing::internal::g_gmock_implicit_sequence" (?g_gmock_implicit_sequence@internal@testing@@3V?
$ThreadLocal@PEAVSequence@testing@@@12@A) [C:\Users\Julian Oes\src\MAVSDK\build\release\src\unit_tests_runner.vcxproj]
C:\Users\Julian Oes\src\MAVSDK\build\release\src\Debug\unit_tests_runner.exe : fatal error LNK1120: 2 unresolved extern
als [C:\Users\Julian Oes\src\MAVSDK\build\release\src\unit_tests_runner.vcxproj]
```

**Comment by julianoes** [comment]
I think the underlying problem is that the dependencies are all built in debug mode for Windows because MSVC based generators require `--config Release` unlike Makefile based generators which work with `CMAKE_BUILD_TYPE`.

**Comment by JonasVautherin** [comment]
So this line does not work properly? https://github.com/mavlink/MAVSDK/blob/main/third_party/cmake/build_target.cmake#L37

**Comment by JonasVautherin** [comment]
Oh, this line does not run the dependencies. Got it!

**Comment by julianoes** [comment]
While I look at this I'm asking myself: Does it work for Linux because I don't see that we pass on `CMAKE_BUILD_TYPE`?

> ```BUILD_COMMAND cmake --build . --config ${CMAKE_BUILD_TYPE}```

This would only work if `CMAKE_BUILD_TYPE` is set but I assume it's not on Windows where we use `--config`.

**Comment by JonasVautherin** [comment]
For the "main" [build command](https://github.com/mavlink/MAVSDK/blob/main/third_party/cmake/build_target.cmake#L37), we only do it for MSVC, where we set `CMAKE_BUILD_TYPE` [in the CI](https://github.com/mavlink/MAVSDK/blob/main/.github/workflows/main.yml#L509).

For the dependencies, maybe we would need to `if (MSVC)`, but in my experience (just tried once on my laptop :laughing:), Linux seems to ignore `--config` completely :see_no_evil:

**Comment by julianoes** [comment]
Note that `CMAKE_BUILD_TYPE` does not do anything when you use it with the MSVC generator, as we do it. It just builds debug. You would need `--config Release` as well.

> Linux seems to ignore --config completely 🙈

Yes. When you use Makefile base generators, it is not used. I believe configuration is a build time flag whereas `CMAKE_BUILD_TYPE` is a configure time flag.

**Comment by JonasVautherin** [comment]
> Note that CMAKE_BUILD_TYPE does not do anything when you use it with the MSVC generator, as we do it. It just builds debug. You would need --config Release as well.

Yes, but that's exactly what the following would do, right? Be ignored by Linux, and set `CMAKE_BUILD_TYPE` for Windows. And if not specified, either default to Debug, or fail on Windows.

```
BUILD_COMMAND cmake --build . --config ${CMAKE_BUILD_TYPE}
```

**Comment by julianoes** [comment]
Yes, true, so what we need to do for Windows is use `--config` as well as `-DCMAKE_BUILD_TYPE`, right?

**Comment by julianoes** [comment]
Ok, I can build release on Windows by combining both flags:
```
cmake -DCMAKE_BUILD_TYPE=Release --config Release -Bbuild -H.
```


I think the error of this issue is unrelated to the build type though.

**Comment by JonasVautherin** [comment]
Wait, this is the configure step, right? `--config Release` should go in the build step, i.e. `cmake --build build --config Release`, right?

**Comment by julianoes** [comment]
You're right. So you need to have `-DCMAKE_BUILD_TYPE` for the configure step and `--config` for the build step.
