### ISSUE TITLE
Unable to connect to Serial COM port on Windows 10 (64 bit)

### ISSUE THREAD

**Issue by Sudheer421** [mavlink/MAVSDK#1379]
![Screenshot (143)](https://user-images.githubusercontent.com/23721696/112449310-413ce080-8d79-11eb-8406-9fb284271ddc.png)

Hi guys,

I am making a sample application to communicate with a pixhawk 4 (Running Px4 ) firmware via Telemetry device.
I have built the MAVSDK lib and integrated it in my project. 
I was trying to establish communication with the FCU (Pixhawk 4) , but it is throwing an exception "KernelBase.dll"
**Please refer to the image posted above for more information.**
could someone help me resolve the issue.
Thanks in advance.

**Comment by julianoes** [comment]
Interesting. Can you copy the full output that you see on the bottom right and paste it here. You can add ``` around it to format it nicely.

**Comment by Sudheer421** [comment]
Hi @julianoes,

Please find the output trace below.

'HCWindowsGCS.exe' (Win32): Loaded 'H:\Programming\HCWindowsGCS\x64\Debug\HCWindowsGCS.exe'. Symbols loaded.
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Program Files\AVAST Software\Avast\aswhook.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'H:\Programming\HCWindowsGCS\x64\Debug\mavsdk.dll'. Module was built without symbols.
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'HCWindowsGCS.exe' (Win32): Unloaded 'C:\Windows\System32\advapi32.dll'
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\winspool.drv'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\msimg32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'HCWindowsGCS.exe' (Win32): Unloaded 'C:\Windows\System32\combase.dll'
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.959_none_e6c7bbbf130c62bb\comctl32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\oledlg.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.959_none_17b2aea46d9edc89\GdiPlus.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\oleacc.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'HCWindowsGCS.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'HCWindowsGCS.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'HCWindowsGCS.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. 
**Exception thrown at 0x00007FFCC41BA799 in HCWindowsGCS.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x0000005CE18FD500.
Unhandled exception at 0x00007FFCC41BA799 (KernelBase.dll) in HCWindowsGCS.exe: 0xC000041D: An unhandled exception was encountered during a user callback.**'

**Comment by julianoes** [comment]
My first thought would be that the exception is somewhere else and not in MAVSDK but that's probably too easy :).

It says that:
> 'HCWindowsGCS.exe' (Win32): Loaded 'H:\Programming\HCWindowsGCS\x64\Debug\mavsdk.dll'. Module was built without symbols.

Could you use a debug build for MAVSDK to see if that gives you more information?

Could it be a permission issue for the COM port, or something wrong with the way we try to access it?

**Comment by Sudheer421** [comment]
Hi @julianoes ,

I got the MAVSDK working. 

The problem was actually with the type of the library. Let me explain...
I used **Release version** library files and was building a **Debug version** of application which was causing the issue.
I built  **Release version** and It was working fine. 


Thanks for the support.

**Comment by julianoes** [comment]
Aha! I find that very confusing on Windows how release vs debug needs to match!
