### ISSUE TITLE
Using multiple UDP remotes with system id - mavsdk android 

### ISSUE THREAD

**Issue by Kutbip** [mavlink/MAVSDK#1389]
Hello @JonasVautherin & @julianoes,
I have gone through issue #1319  (multiple UDP remotes).
Came to know that changes have been merged in the branch.
I just want to know if it is available for Android using mavsdk?

**Comment by JonasVautherin** [comment]
It is not exposed in MAVSDK-Java, but if you use MAVSDK-C++ on Android, then yes, it can be used.

**Comment by Kutbip** [comment]
Would it be available in MAVSDK-Java in the coming days?

**Comment by JonasVautherin** [comment]
No, that's not so easy to expose unfortunately :(

**Comment by Kutbip** [comment]
Thank you for the quick response.
I will try to add MAVSDK-C++ on Android.
