### ISSUE TITLE
import_qgroundcontrol_mission not working after moved to mission_raw

### ISSUE THREAD

**Issue by petergerten** [mavlink/MAVSDK#1421]
Hi,

I just upgraded MAVSDK to 0.39.0 and the QGC mission import was migrated from mission to mission_raw. All existing mission plans I could import before stopped working with the following error:

`Error Parameter to MergeFrom() must be instance of same class: expected MissionItem got MissionItem.`

I have a hard time interpreting the error. Any hints what is going on here?

**Comment by JonasVautherin** [comment]
Could you share one such mission plan such that we can reproduce the issue?

**Comment by julianoes** [comment]
@petergerten Where do you get this error?

**Comment by julianoes** [comment]
No answer in 3 years, I might as well close this.
