### ISSUE TITLE
One drone arming and flying does not allow the other to arm.

### ISSUE THREAD

**Issue by AldoCF96** [mavlink/MAVSDK#1425]
Currently I am creating a code that uses multiple classes. In the zip file I shared I use two classes one for mavsdk and connections. and other for addressing individual drones.

the drones are drone0 and drone1
![image](https://user-images.githubusercontent.com/50414883/116796612-c9668200-aaab-11eb-8b5e-04b52e9ba26e.png)

as You can see when trying to arm drone 1 it says it is already arm, but it is not drone 0 is armed. 

My setup is right now running two simulations without changing the location:

` ./Tools/sitl_multiple_run.sh 2
HEADLESS=1  ./Tools/jmavsim_run.sh -l
`
and the second one in a new terminal 
```
HEADLESS=1  ./Tools/jmavsim_run.sh -p 4561 -l
```

[server_sample.zip](https://github.com/mavlink/MAVSDK/files/6410384/server_sample.zip)

**Comment by julianoes** [comment]
I can reproduce the issue. Thanks for the steps @AldoCF96.

I found that this comes from the fact that systems are stores in an `unordered_map` and therefore the order is actually not guaranteed. So what happens is that in your case you initialize both `Drone`s with the same `System`.

I will create a fix to address that.
