### ISSUE TITLE
Feature req: pkgconfig for building

### ISSUE THREAD

**Issue by vranki** [mavlink/MAVSDK#1428]
The "standard" way of including libraries in linux is pkgconfig mechanism. This tells what headers and libraries must be included in the compilation process. Almost any library in linux distros ship with pkgconfig metadata file. Pkgconfig can be used from any build system including cmake and qmake.

Mavsdk currently does not ship with pkgconfig and it's not obvious how to build correctly when using other than CMake as build system.

**Comment by julianoes** [comment]
Thanks for the note. Pull requests are welcome :wink:.

**Comment by JonasVautherin** [comment]
Yes, that would be a great addition! Would you be willing to look into it?

**Comment by vranki** [comment]
I can take a look.

First thing I noticed that the debian package doesn't provide library symlinks. For example I needed to ln -s /usr/lib/libmavsdk.so.0 /usr/lib/libmavsdk.so

I think that's a packaging error.

After that this .pc file placed at /usr/lib/x86_64-linux-gnu/pkgconfig/mavsdk.pc seems to work or at least compile:

```
#############################################
#####   Pkg-Config file for mavsdk      #####
#############################################

prefix=/usr
exec_prefix=${prefix}

libdir=/usr/lib
includedir=${prefix}/include/mavsdk

Name: mavsdk
Version: 0.39.0
Description: Set of libraries providing a high-level API to MAVLink
Libs: -L${libdir} -lmavsdk
Cflags: -I${includedir}
```

**Comment by JonasVautherin** [comment]
Should the `.pc` file be generated by cmake? Or only installed? Like can we get the `Libs` and `Cflags` set automatically by cmake? Would be cool :sunglasses:

**Comment by vranki** [comment]
I haven't actually done any of them in real life situation, but the debian/rpm package should provide the .pc file. The file contents can be generated by packaging and include for example correct version number. I believe static file without version would also work, but you couldn't check for certain version in project build.

I bet there is some cmake based library in wild with proper .pc packaging that could be used as a example.

**Comment by JonasVautherin** [comment]
@vranki just realized it is done [here](https://github.com/leethomason/tinyxml2/blob/master/CMakeLists.txt#L123-L129), which could serve as inspiration:

```cmake
## pkg-config

configure_file(cmake/tinyxml2.pc.in tinyxml2.pc.gen @ONLY)
file(GENERATE OUTPUT tinyxml2.pc INPUT "${CMAKE_CURRENT_BINARY_DIR}/tinyxml2.pc.gen")
install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/tinyxml2.pc"
    DESTINATION "${tinyxml2_INSTALL_PKGCONFIGDIR}"
    COMPONENT tinyxml2_development
)
```

Using the following `tinyxml2.pc.in`:

```pkgconfig
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@

Name: TinyXML2
Description: simple, small, C++ XML parser
Version: @tinyxml2_VERSION@
Libs: -L${libdir} -l$<TARGET_FILE_BASE_NAME:tinyxml2::tinyxml2>
Cflags: -I${includedir}
```

**Comment by Consti10** [comment]
any updates on this ? I am trying to integrate mavsdk with qmake (Qt), which doesn't speak cmake.

**Comment by Consti10** [comment]
Dirty but compiles in qmake:
```
# mavsdk - dirty
INCLUDEPATH += /usr/local/include/mavsdk
LIBS += -L/usr/local/lib -lmavsdk
```

**Comment by JonasVautherin** [comment]
Did you try with @vranki's mavsdk.pc file above?

**Comment by JonasVautherin** [comment]
I started looking into it [(draft PR here)](https://github.com/mavlink/MAVSDK/pull/1889). Happy to get feedback :+1:

**Comment by julianoes** [comment]
@vranki could you please give feedback on the draft PR by @JonasVautherin in https://github.com/mavlink/MAVSDK/pull/1889?
