### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by fpersson** [mavlink/MAVSDK#1434]
Links are broken for API Reference, Example and FAQ.

**Comment by JonasVautherin** [comment]
Just tried some links and they work for me. Would you mind being specific and sharing the said links?

**Comment by fpersson** [comment]
In README.md links are pointing to https://mavsdk.mavlink.io/main/en/examples/ and I think correct path is https://mavsdk.mavlink.io/main/en/cpp/examples/ and its same error with the FAQ and API Reference under "Qiuck Links:"

Only "API Reference", "Example" and "FAQ" is broken.

**Comment by julianoes** [comment]
Aha! Thank you. Would you mind creating a PR to fix it?

**Comment by fpersson** [comment]
Done.

**Comment by julianoes** [comment]
Thanks a lot @fpersson.
