### ISSUE TITLE
Method to return string for Telemetry::GPSinfo::fix_type ?

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#144]
This is something people would reasonably want to get a string for, in the same way as we do for our enums. See [Telemetry::GPSinfo::fix_type](https://dronecore.gitbooks.io/dronecore-guide/content/en/api_reference/structdronecore_1_1_telemetry_1_1_g_p_s_info.html#structdronecore_1_1_telemetry_1_1_g_p_s_info_1acc9d81d4b884bb2b229fe68d0c36f6cc)

**Comment by julianoes** [comment]
We have that now:

https://github.com/mavlink/MAVSDK/blob/6434e0c6a7c25a3203d4652da13ea1944279beb1/src/plugins/telemetry/include/plugins/telemetry/telemetry.h#L60-L78

https://github.com/mavlink/MAVSDK/blob/6434e0c6a7c25a3203d4652da13ea1944279beb1/src/plugins/telemetry/telemetry.cpp#L1090-L1110
