### ISSUE TITLE
Should we assume that a UDP packet contains messages from only one system?

### ISSUE THREAD

**Issue by JonasVautherin** [mavlink/MAVSDK#1454]
I was just reading the code, and wondered about [this](https://github.com/mavlink/MAVSDK/blob/main/src/core/udp_connection.cpp#L234-L235):

```c++
            if (!saved_remote && sysid != 0) {
                saved_remote = true;
```

This is an optimization so that it does not "save" the remote for each message of the UDP packet, right?

I'm just thinking that this assumes that a UDP packet only ever contains messages from one sysid. Not sure if that's relevant or not, but I can imagine situations where this will give weird results :thinking:.

**Comment by julianoes** [comment]
Doesn't sound like that's correct, thanks for bringing it up.
