### ISSUE TITLE
Сan not connect to the drone

### ISSUE THREAD

**Issue by gnarwhal97** [mavlink/MAVSDK#1457]
Hello, I'm simulating VTOL in Gazebo. I want to run example takeoff_and_land.py, but it cannot conect to drone. 
My output:

Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...

**Comment by julianoes** [comment]
Is this running on the same machine or are you running docker or a virtual machine somewhere?

**Comment by julianoes** [comment]
No answer in 3 years, I think I can close this.
