### ISSUE TITLE
Connect DJI Mavic 2 to PyCharm

### ISSUE THREAD

**Issue by cepoya** [mavlink/MAVSDK#1475]
Hi Gentlements,

newbie want ask you, please help
my drone: Mavic 2

i have issue, 
i already connect my phone to QGroundControl , it's work even the video show and didn't show
i want collect data distance and all parameter from drone to PC using Pyton language  also direct video from drone to PC but always error

my step:
1. mavsdk server running but still any problem
![image](https://user-images.githubusercontent.com/62041698/124900446-444b9c00-e00b-11eb-806d-096a745ed2be.png)

2. actually i still doesn;t know how to connect scrip to drone (newbie person)
![image](https://user-images.githubusercontent.com/62041698/124900756-94c2f980-e00b-11eb-867d-46aacbbfaf76.png)

need your help to step by step,,
thanks

**Comment by JonasVautherin** [comment]
Are you sure that the DJI Mavic 2 exposes a MAVLink interface? :thinking:
