### ISSUE TITLE
Cannot build examples on Windows (lib error)

### ISSUE THREAD

**Issue by fookinhell** [mavlink/MAVSDK#1478]
Hello,
I don't get how to build examples on Windows.

From a clean clone, after the submodule update, I did the following : 

`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=install -Bbuild/default -H.`

`cmake --build build/default --config Release --target install`

Then, when I try to compile the takeoff and land example, using this command 
`cmake -Bbuild -DCMAKE_PREFIX_PATH=../../install -H.`

I have the following error : 

```
D:\workspace\MAVSDK\examples\takeoff_land>cmake -Bbuild -DCMAKE_PREFIX_PATH=../../install -H.
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a package configuration file provided by "CURL" with any of
  the following names:

    CURLConfig.cmake
    curl-config.cmake

  Add the installation prefix of "CURL" to CMAKE_PREFIX_PATH or set
  "CURL_DIR" to a directory containing one of the above files.  If "CURL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  D:/workspace/MAVSDK/install/lib/cmake/MAVSDK/MAVSDKConfig.cmake:7 (find_dependency)
  CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/workspace/MAVSDK/examples/takeoff_land/build/CMakeFiles/CMakeOutput.log".
```

There might be something I don't get !
Thanks in advance for your help :)

**Comment by JonasVautherin** [comment]
Almost there, but I think you need to point CMake to the dependencies (curl is one of them), so something like this:

```
cmake -Bbuild -DCMAKE_PREFIX_PATH="../../install;../../build/default/third_party/install" -H.
```

**Comment by fookinhell** [comment]
Well, that wasn't so hard, thanks :)

After removing the generated build folder and retrying to build the example, I know have this error : 
```
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "takeoff_and_land" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Shouldn't Threads be already linked ?

**Comment by JonasVautherin** [comment]
Oh it's right that the example does [#include <thread>](https://github.com/mavlink/MAVSDK/blob/main/examples/takeoff_land/takeoff_and_land.cpp#L14), but does not link it (see [here](https://github.com/mavlink/MAVSDK/blob/main/examples/takeoff_land/CMakeLists.txt)).

The [fly_mission](https://github.com/mavlink/MAVSDK/blob/main/examples/fly_mission/CMakeLists.txt) example does it correctly. Would you mind changing takeoff_land to link threads, similarly?

**Comment by fookinhell** [comment]
That did the trick !
Sorry for not taking the time to look at other examples.. I'll do it next time I have a problem :)

I'm closing this, thanks for your quick answers :)

**Comment by JonasVautherin** [comment]
> Sorry for not taking the time to look at other examples..

You actually found a bug in this one :slightly_smiling_face:. Would you mind opening a PR to fix it?
