### ISSUE TITLE
Error Running Example Mission.py

### ISSUE THREAD

**Issue by TomoCoder123** [mavlink/MAVSDK#1496]
When I run Mission.py from Examples using Gazebo and the PX4 flight controller software, I receive these errors. 
![Screenshot from 2021-07-30 00-12-38](https://user-images.githubusercontent.com/76802324/127599176-93c6e567-5ce6-4ae1-837b-cbc0262b8e78.png)

I am wondering if the warnings shown below are the reason for the problem and if anyone has any ideas. Thanks in advance, a little new to this software.
![Screenshot from 2021-07-30 00-14-51](https://user-images.githubusercontent.com/76802324/127599526-40991b86-a490-4ca4-b4ff-3feeaa769eb3.png)

**Comment by julianoes** [comment]
The API for MissionItem has changed, fix coming: https://github.com/mavlink/MAVSDK-Python/pull/372
