### ISSUE TITLE
Question about Pixhawk Cube Orange & Pixhawk Cube Black

### ISSUE THREAD

**Issue by marcinm97** [mavlink/MAVSDK#1505]
Does the MAVSDK C++ support both versions of pixhawk? ( Orange Cube & Black Cube )

**Comment by reedev** [comment]
I guess it might be good to describe what you are trying to achieve. What is your setup wrt PX4 or ArduPilot, etc. What have you tried so far? Giving more details will allow people to help you better.

**Comment by JonasVautherin** [comment]
MAVSDK supports mainly PX4, and I have seen people use at least parts of it with Ardupilot.

It's not related to pixhawk though: pixhawk is the hardware, and MAVSDK does not care about the hardware. So you can run PX4 on a pixhawk, a raspberry pi, your laptop or a coffee machine, as long as MAVLink messages reach MAVSDK, it will be fine.

Does that answer your question? :blush:

**Comment by julianoes** [comment]
Closing as there was no follow up.
