### ISSUE TITLE
Action not working properly

### ISSUE THREAD

**Issue by saadnec** [mavlink/MAVSDK#1506]
I just added action.gotolocation in the takeoff example but as soon as it takes this command instead of going to that location my vehicle starts  going down and lands.

Pictures of codes and mavsdk messages are attached 
![0](https://user-images.githubusercontent.com/88645996/129013215-64ea7ff2-c14c-42c6-aa79-a28d88defad7.PNG)
![1](https://user-images.githubusercontent.com/88645996/129013219-a6b3cfb0-90ff-46aa-af10-b525d1abf114.PNG)

I added these two lines
***
sleep_for(seconds(10));
    const Action::Result result = action.goto_location(47.3974,8.54565,2.5,0);
    if (result != Action::Result::Success) {
        std::cerr << "Action failed:" << result << '\n';
    }
***

what am i doing wrong ?

**Comment by reedev** [comment]
Never tried this particular case myself but I know from missions that you need to be within a certain distance (900 meters) from the home point. I guess you need to set the home position, see for sitl https://docs.px4.io/master/en/simulation/gazebo.html

**Comment by JonasVautherin** [comment]
The altitude of the goto_location command is given above sea level (see the documentation here: https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/action/action.proto#L79-L80).

So if your drone takes off 400m above the sea level, and you ask it to go to 2.5 meters above sea level, then it will go down. Could that be the reason for your issue?

**Comment by saadnec** [comment]
> 
> 
> The altitude of the goto_location command is given above sea level (see the documentation here: https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/action/action.proto#L79-L80).
> 
> So if your drone takes off 400m above the sea level, and you ask it to go to 2.5 meters above sea level, then it will go down. Could that be the reason for your issue?

Yes, that was the issue. Thanks for helping me resolve this issue :).
