### ISSUE TITLE
(slightly off-topic) How to 'reset' Gazebo after running integrations tests?

### ISSUE THREAD

**Issue by reedev** [mavlink/MAVSDK#1508]
Hi,

v0.42.0
I ran the integrations tests and now running the  MAVSDK example fly_mission (with custom waypoints next to the home point) and now I get "MAVLink: critical: Geofence violation for waypoint". Which is understandable since I ran the integration tests...

Is there a way to reset/clear Gazebo? I couldn't find an answer in the MAVSDK issues...

Thanks

**Comment by JonasVautherin** [comment]
I just restart it :sweat_smile:. I don't think there is a way, to be honest

**Comment by reedev** [comment]
No way, that doesn’t work for me...?! Of course, I tried that 😛

**Comment by mrpollo** [comment]
I think what @JonasVautherin means is you need to stop PX4 and relaunch it. That should start the gazebo simulation environment in a fresh state.

**Comment by reedev** [comment]
Hi Ramon,
Yes, that’s how I interpreted Jonas’ suggestion, thanks. I also restarted the machine and the geofence violation was still there.

I now realized that it is indeed px4 that does the sitl, thanks.

I remember that I also ran px4 unit tests and integrations tests so maybe the state is stored in the px4 source tree. Not sure, I am learning about px4, mavsdk, etc

I have now ‘fixed’ the issue by using a fresh clone and build of the px4…

**Comment by mrpollo** [comment]
It's possible that PX4 stores some values to make the build faster, in those cases I recommend you run 'make clean' it's faster than a fresh clone

**Comment by reedev** [comment]
Fyi, I tried that but no change. Actually, I did not expect this to be honest since 'make clean' is a build command. Anyway, it's not important for now.

**Comment by julianoes** [comment]
O

**Comment by reedev** [comment]
Yes, that sounds right to me too.
For my understanding, which file stores the geofence, do you know that? Is there documentation about these sitl runtime files?

**Comment by julianoes** [comment]
This should be the file: `build/px4_sitl_default/tmp/rootfs/dataman`.

**Comment by reedev** [comment]
All clear, thanks
