### ISSUE TITLE
How to get lidar data with mavsdk

### ISSUE THREAD

**Issue by saadnec** [mavlink/MAVSDK#1511]
I am trying to get lidar data with mavsdk but there is no header file present to interact with a lidar. Is there any way i can get lidar data using mavsdk?

**Comment by JonasVautherin** [comment]
So I assume that the distance sensor interface does not work in your case? https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/telemetry/telemetry.proto#L73-L74

**Comment by julianoes** [comment]
@saadnec could you respond to what @JonasVautherin wrote please?
And what lidar are you using? And is it connected to PX4, and how? And does PX4 see it?

**Comment by saadnec** [comment]
Couldnt get the data using mavsdk so ended up using mavlink
