### ISSUE TITLE
mission vs mission_raw?

### ISSUE THREAD

**Issue by reedev** [mavlink/MAVSDK#1512]
Hi,
Is there any documentation about both classes and particularly about the reason of the 2 types?

thank you

**Comment by JonasVautherin** [comment]
`mission_raw` is a lower-level interface, where you have to use the `msgid` etc. `mission` is higher-level, and ideally the one you should use if it does the job for you.

**Comment by reedev** [comment]
Aha, ok, that's good advice. Thanks.
