### ISSUE TITLE
Not able to access camera 

### ISSUE THREAD

**Issue by saadnec** [mavlink/MAVSDK#1513]
I am using px4 and made the changes in iris.sdf.jinja file to add the camera plugin and it is successfully implemented too its showing in the gazebo environment. 

But when i am trying to connect to it using mavsdk by using camera example in examples, it says No camera found, exiting.
@JonasVautherin 
@julianoes

**Comment by JonasVautherin** [comment]
Did you try with the typhoon h480 model? I believe it has a camera

**Comment by julianoes** [comment]
Closing, please comment again if this is not resolved.
