### ISSUE TITLE
no entries received

### ISSUE THREAD

**Issue by TechNaturalist** [mavlink/MAVSDK#1523]
Hello!

I am trying to pull logs onto a companion computer via MAVSDK.  However,  when using the get_entries() function I get a warning saying: "No entries received" for the log_files_impl.cpp

Checking Q Ground Control there are at least 14 entries.

Why is nothing being found? 

Any hints would help! Thanks you!

**Comment by JonasVautherin** [comment]
For the record: that message comes from [here](https://github.com/mavlink/MAVSDK/blob/main/src/plugins/log_files/log_files_impl.cpp#L167), which comes from `list_timeout`, which [is called](https://github.com/mavlink/MAVSDK/blob/main/src/plugins/log_files/log_files_impl.cpp#L97) by [`get_entries_async`](https://github.com/mavlink/MAVSDK/blob/main/src/plugins/log_files/log_files_impl.cpp#L86).

It would require some more debugging, but my first guess is that the MAVLink communication does not work properly. Can you try to call `get_entries()` multiple times, e.g. (pseudo-code):

```
get_entries()
sleep(2 seconds)
get_entries()
```

If that works, it would show that there is a significant delay on that link.

Also, does MAVSDK work other than get_entries? E.g. can you take a photo, receive telemetry, stuff like that? Just to know if mavlink messages can go from your MAVSDK code to PX4 and back.

**Comment by TechNaturalist** [comment]
Hello! 

I will try that and get back to you soon.

To answer your follow up question: I am using Mavlink Passthrough successfully.  So I believe it is working.

**Comment by arvind00x** [comment]
did you find any solution ? I am facing same problem.

**Comment by julianoes** [comment]
This has been improved with v2 and fixed up recently. I'll close this for now.
