### ISSUE TITLE
How to control velocity or fly time when using offboard::set_position_ned?

### ISSUE THREAD

**Issue by happyzihao** [mavlink/MAVSDK#1547]
Hello, when using offbaord::set_postion_ned to actual fly, the speed of vehicle is always too fast.
For safety, I want to slow down the actual fly speed.

I try to change the value of this variable: 
 const float SEND_INTERVAL_S = 0.05f;

But It's not work, How can I do ?
thanks

**Comment by julianoes** [comment]
You should be able to set the speed using the param [MPC_XY_CRUISE](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_XY_CRUISE).

**Comment by happyzihao** [comment]
> You should be able to set the speed using the param [MPC_XY_CRUISE](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_XY_CRUISE).

Thanks, It's work.
