### ISSUE TITLE
How to set vehicle's flight mode?

### ISSUE THREAD

**Issue by happyzihao** [mavlink/MAVSDK#1554]
Sorry, I ask for a simple question?

We can get the flight mode by telemetry plugin?
But how to set ?
Sorry , I spent much time finding this function. But I didnot find.

Thanks for your help

**Comment by JonasVautherin** [comment]
Depends on which mode you want. To go to hold mode, you can do it from the `action` plugin. To go to mission mode, you `start_mission` from the `mission` plugin. To go to offboard, that's in the `offboard` plugin.

Does that help?

**Comment by happyzihao** [comment]
Thanks, I  get.
