### ISSUE TITLE
Can't connect to SITL - "Ignoring unknown ping sequence" (possibly not bug)

### ISSUE THREAD

**Issue by KrisRadowski** [mavlink/MAVSDK#1582]
Disclaimer: I'm not sure it's a bug, but I'm submitting issue anyway since it looks like the app and SITL are somehow using different MAVLINK version (at least that's what I'm thinking)

Description of problem:

Trying to connect to SITL fails; display of mavsdk_server(dev bulid) and application are attached
![mavsdk_server](https://user-images.githubusercontent.com/10513413/139116885-e01d2cc6-af27-4f8f-a1e0-ee4fa9b472b0.png)
![mavsdk_app](https://user-images.githubusercontent.com/10513413/139116907-9b1de8a9-f653-40cd-9b56-5cc3e566519b.png)
Problem persist on fresh install with current MAVSDK and PX4

How to reproduce problem:

1.  use current MAVSDK and px4
2. run Gazebo SITL and mavsdk_server
3, run application compiled from attached source files
[kwik_n_dirty_test.zip](https://github.com/mavlink/MAVSDK/files/7428214/kwik_n_dirty_test.zip)

**Comment by KrisRadowski** [comment]
ok, I decided to sidestep the issue by rewriting my program to Python,

before I close that I have a question:
how to handle promises in python; I know that in C++ a _future_ library is used for example:
```
promise<void> inAirPromise; //these two I don't know how to rewrite
auto inAirFuture = inAirPromise.get_future();
...
telemetry->subscribe_landed_state(landedStateCallback(telemetry,inAirPromise)); //that i know how to rewite to python
```

**Comment by julianoes** [comment]
Sorry, I'm closing this, not sure what else to do about it at this stage.
