### ISSUE TITLE
When used the cancel of calibration plugin class, there is crash!!!  

### ISSUE THREAD

**Issue by SSSnow** [mavlink/MAVSDK#1600]
debug the error:
A command cannot be sent if another command with the same command_id is still processing! Ignoring command 241
Mavsdk: Callback called from mavlink_commands.cpp:337 took more than 1 second to run.

when i comment [the line:226](https://github.com/mavlink/MAVSDK/blob/main/src/plugins/calibration/calibration_impl.cpp#L226):

```c++
 _parent->send_command_async(command, nullptr);
```

then work ok!   
I want to know why send a nullptr callback before send a normal cancel calibration command?
thanks!

**Comment by SSSnow** [comment]
@bkueng

**Comment by JonasVautherin** [comment]
Reading through the code, this seems like a bug indeed. I think this line should not be there.

@SSSnow: Would you mind opening a PR with that change?

**Comment by JonasVautherin** [comment]
@SSSnow: Not sure I understood correctly: will you open a PR with your bugfix? You deserve the credit with the commit :blush:
