### ISSUE TITLE
Missing Param - SITL. Not reading position

### ISSUE THREAD

**Issue by evanatherton1** [mavlink/MAVSDK#1616]
Trying to read global position using SITL. This is the output I get. Lat Lon and Alt values are read as nan.
![IMG_7968](https://user-images.githubusercontent.com/92040868/141012357-67a6616e-6557-4291-a2ed-5d311cc1fff6.jpg)

**Comment by julianoes** [comment]
What's your PX4 version and what's the MAVSDK version?

**Comment by evanatherton1** [comment]
PX4: 1.12.3
I'm not sure how to check which version of MAVSDK is being run.

**Comment by evanatherton1** [comment]
It looks like I'm running the latest version of mavsdk (0.48.0)

**Comment by JonasVautherin** [comment]
Not sure I get the problem. What is the code you run, what do you expect as a result, and what do you get instead?

**Comment by evanatherton1** [comment]
I'm just trying to print the location of the UAV (Latitude, Longitude, Altitude). After setting the update rate, I call my callback function as so:
`telemetry->subscribe_position(PositionCallbackFunc);`

`void PositionCallbackFunc(Telemetry::Position position)
{
    gDronePosition.alt = position.absolute_altitude_m;
    gDronePosition.lat = position.latitude_deg;
    gDronePosition.lon = position.longitude_deg;
    std::cout<< "Reported Drone Position: \r\n";
    std::cout << "Altitude: " << position.relative_altitude_m << " m" << std::endl
              << "Latitude: " << position.latitude_deg << std::endl
              << "Longitude: " << position.longitude_deg << std::endl;

 
    std::chrono::time_point<std::chrono::system_clock> now = std::chrono::system_clock::now();
    auto duration = now.time_since_epoch();
    m_drone_pos_update_Time = std::chrono::duration_cast<std::chrono::milliseconds>(duration).count();
}`

It never seems to enter the Callback function, and when I try to print the altitude latitude and longitude values they print as "nan"

**Comment by JonasVautherin** [comment]
Did you try running an example, e.g. https://github.com/mavlink/MAVSDK/tree/main/examples/takeoff_and_land? Does that work?

**Comment by evanatherton1** [comment]
![2021-11-15-110817_1280x1024_scrot](https://user-images.githubusercontent.com/92040868/141815330-4986cf9e-3ae1-4ae1-9b20-2d127aae07c7.png)
I get this when attempting to build the example

**Comment by JonasVautherin** [comment]
Did you install mavsdk on your system?

**Comment by evanatherton1** [comment]
I believe so. I followed the instructions found here:
https://mavsdk.mavlink.io/v0.38/en/cpp/guide/build.html

**Comment by JonasVautherin** [comment]
Your last screenshot shows a linking error when building the example, because the example tries to link against mavsdk. You have to solve that linking error, I cannot guess what's on your system :sweat_smile:

**Comment by evanatherton1** [comment]
![2021-11-15-113103_1280x1024_scrot](https://user-images.githubusercontent.com/92040868/141819824-d5a402af-6bfe-4018-924e-b6a1aa9d95a7.png)
It looks like I'm having issues building the library. Would this be a place to start?

**Comment by evanatherton1** [comment]
![2021-11-15-113103_1280x1024_scrot](https://user-images.githubusercontent.com/92040868/141820139-987c130c-0092-4586-a7a3-ec5b136992ad.png)
Looks like I'm having issues building the library. Would this be a place to start?

**Comment by JonasVautherin** [comment]
If the cmake configure step fails ("Configuring incomplete, errors occurred"), then there is no need to try the build step :sweat_smile:.

It does not appear in your screenshot, but it seems like you are using the deprecated `-DBUILD_BACKEND=ON`, so probably you want to use a more recent version of the docs, e.g. just upstream: https://mavsdk.mavlink.io/main/en/cpp/guide/build.html.

Also to use MAVSDK-C++ (i.e. if you don't plan on using MAVSDK-Swift or MAVSDK-Java or MAVSDK-Python), no need to build mavsdk_server.

**Comment by evanatherton1** [comment]
Followed the install instructions from that link. Specifically did this:

$ sudo apt-get update
$ sudo apt-get install build-essential cmake git
$ cd MAVSDK
$ git clone https://github.com/mavlink/MAVSDK.git
$ git submodule update --init --recursive
$ cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild/default -H.
$ cmake --build build/default -j8
$ cmake -Bbuild/default -DCMAKE_BUILD_TYPE=Release -H.
$ cmake --build build/default -j8
$ sudo cmake --build build/default --target install

Seemed to build and install properly. The linking error persists when I try to run the takeoff_and_land example. Specifically did this:
$ cd MAVSDK
$ cd examples
$ cd takeoff_and_land
$ cmake -Bbuild -H.
$ cmake --build build

Error messages come up - same as my 2nd most recent screenshot. Am I missing anything obvious?

**Comment by JonasVautherin** [comment]
So `$ cmake -Bbuild -H.` in the example project worked and found mavsdk on the system?

**Comment by evanatherton1** [comment]
When I run `$ cmake -Bbuild -H.` here's what I get:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/MAVSDK/examples/takeoff_and_land/build

**Comment by JonasVautherin** [comment]
And do you have the symbols in the build binaries? For me:

```
% nm ./build/default/src/core/libmavsdk.so | grep subscribe_on_new_system                                                       [0]
000000000017bd0e T _ZN6mavsdk10MavsdkImpl23subscribe_on_new_systemERKSt8functionIFvvEE
00000000001771d4 T _ZN6mavsdk6Mavsdk23subscribe_on_new_systemERKSt8functionIFvvEE
```

**Comment by evanatherton1** [comment]
Where would I see that? Not sure how to access build binaries. 

Really appreciate the help. I'm new to this stuff

**Comment by JonasVautherin** [comment]
Something like this should find it:

```
find ~/MAVSDK | grep libmavsdk.so
```

**Comment by julianoes** [comment]
No more answer, closing.
