### ISSUE TITLE
package architecture (armv7) does not match system (armhf)

### ISSUE THREAD

**Issue by Katawann** [mavlink/MAVSDK#1680]
From a Raspberry Pi 3b+ I try to get the debian package to install MAVSDK but I run into an issue:

```
$ sudo dpkg -i mavsdk_1.0.6_debian11_armv7.deb 
dpkg: error processing archive mavsdk_1.0.6_debian11_armv7.deb (--install):
 package architecture (armv7) does not match system (armhf)
Errors were encountered while processing:
 mavsdk_1.0.6_debian11_armv7.deb
```
Information regarding my rpi:
```
$ uname -a
Linux 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

It fails the same way when I build a docker containing MAVSDK. Happy to provide more information if necessary !

**Comment by julianoes** [comment]
I see, these arch flags are tricky. Thanks for the info.

**Comment by julianoes** [comment]
@Katawann when you try the armv6 one? Do you get the same warning?

**Comment by Katawann** [comment]
On the RPi yes:

```
$ sudo dpkg -i mavsdk_1.0.6_debian11_armv6.deb 
dpkg: error processing archive mavsdk_1.0.6_debian11_armv6.deb (--install):
 package architecture (armv6) does not match system (armhf)
Errors were encountered while processing:
 mavsdk_1.0.6_debian11_armv6.deb
```

**Comment by julianoes** [comment]
Let's see if https://github.com/mavlink/MAVSDK/pull/1681 helps.

**Comment by Katawann** [comment]
works for me !

```
$ sudo dpkg -i libmavsdk-dev_1.0.7_debian11_armv7.deb 
Selecting previously unselected package libmavsdk-dev.
(Reading database ... 46954 files and directories currently installed.)
Preparing to unpack libmavsdk-dev_1.0.7_debian11_armv7.deb ...
Unpacking libmavsdk-dev (1.0.7) ...
Setting up libmavsdk-dev (1.0.7) ...
```

Does the new naming _libmavsdk-dev_ will remain the same for next release or will you go back to previous _mavsdk_1.0.6_debian11_armv6.deb_ ?

**Comment by julianoes** [comment]
Nice, thanks for testing. I changed that naming on purpose, it's how usually libraries with headers are named for Debian/Ubuntu, I believe.
