### ISSUE TITLE
Error when calling Telemetry.get_gps_global_origin() for second vehicle with multiple Simulations running

### ISSUE THREAD

**Issue by fas2037** [mavlink/MAVSDK#1687]
I am running PX4 1.12.3 and using the command `Tools/gazebo_sitl_multiple_run.sh  -2` to start two vehicles.
I added `std::cout << telemetry.get_gps_global_origin().first << std::endl;` in Line 148 of https://github.com/mavlink/MAVSDK/blob/5806dc04d890e7aefad93c65a44486b477371719/examples/fly_multiple_drones/fly_multiple_drones.cpp#L143-L150.

When running `./fly_multiple_drones udp://:14540 udp://:14541 plan1.plan plan2.plan` the get_gps_global_origin() fails for the second vehicle with the result "Connection Error".

It does work for older MAVSDK versions (v.0.42.0)

**Comment by julianoes** [comment]
I just tested latest `main` against PX4 v1.13 and that worked fine, including `telemetry.get_gps_global_origin()`, returning "Success" for both.
