### ISSUE TITLE
Windows Executable - missing mavsdk.dll

### ISSUE THREAD

**Issue by Tzhao7** [mavlink/MAVSDK#1688]
Hi,
After having build issues several days earlier, I managed to successfully build and install MAVSDK. However, after creating and building a cmake C++ project and running the executable, I was given this error:
![image](https://user-images.githubusercontent.com/59535719/150616852-398aace3-fcdf-49b6-8179-9925940e6eac.png)
I think my CMakeLists.txt is fine but this is what it looks like:
![image](https://user-images.githubusercontent.com/59535719/150618265-99b23bac-4dbe-425b-9e2e-4920ef1bb374.png)
**Want to note that I did a system-wide install and I'm not sure if this should be done on Windows.
Also I noticed that the installed library found in C:\Program Files only contains mavsdk.lib and does not contain any .dll.**

**Comment by JonasVautherin** [comment]
How did you build and install it? Can you copy the commands here?

**Comment by Tzhao7** [comment]
These are the commands I used:
git clone https://github.com/mavlink/MAVSDK.git
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild/default -H.
runas cmake --build build/default --target install

**Comment by JonasVautherin** [comment]
After the build, in your `MAVSDK` directory, can you search for `mavsdk.dll`? Not in `C:\Program Files`, but really in the build folder (so `path/to/MAVSDK/build/default`).

Maybe the system install is not installing the DLL correctly...

**Comment by Tzhao7** [comment]
mavsdk.dll is in build/default of the MAVSDK directory. Is the MAVSDK directory supposed to be inside my C++ project? That could be why it's returning this error.

**Comment by JonasVautherin** [comment]
> Is the MAVSDK directory supposed to be inside my C++ project? That could be why it's returning this error.

No. The right files from `build/default` should be installed on your system (in `C:\Program Files`) when you run `cmake --build build/default --target install`. It seems to me that we don't install `mavsdk.dll` correctly on Windows, which ends up in your error.

**Comment by Tzhao7** [comment]
Should I try a local install and see if the mavsdk.dll can be found there?

**Comment by JonasVautherin** [comment]
[This](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/CMakeLists.txt#L94) is (I believe) where we say where the library should be installed. On Linux it gets into `lib/` (more specifically `lib/libmavsdk.so`, `lib/libmavsdk.so.0`, `lib/libmavsdk.so.0.50.1`).

Somehow it seems like on Windows the `.dll` (which should be the equivalent to the `.so` on Linux) is not installed correctly.

**Comment by Tzhao7** [comment]
So after doing a local install I was still not able to find mavsdk.dll within the ### install directory. Only see it in ### build/default.

**Comment by JonasVautherin** [comment]
Could you try to debug it? For instance, you could try to print `${CMAKE_INSTALL_LIBDIR}` [here](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/CMakeLists.txt#L94) to see if it looks correct on Windows. With something like:

```
message(FATAL_ERROR "CMAKE_INSTALL_LIBDIR: ${CMAKE_INSTALL_LIBDIR}")
```

**Comment by Tzhao7** [comment]
I modified the CMakeLists.txt to include that line of code and was given this: ```CMake Error at src/mavsd/core/CMakeLists.txt:98 (message): CMAKE_INSTALL_LIBDIR: lib```

**Comment by JonasVautherin** [comment]
That looks fine to me :thinking:

**Comment by Tzhao7** [comment]
Do you think the previous releases have this problem? It seems like other Windows users haven't had this problem or have had the issue resolved.

**Comment by julianoes** [comment]
https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

What about passing the directory where you need/want it?

```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -Bbuild/default -H.
cmake --build build/default --target install
```

**Comment by JonasVautherin** [comment]
But it seems like it's installing "stuff" already, just not that one dll :thinking:. Do you think that a local install would help?

**Comment by julianoes** [comment]
Is it's installing it into `C:\Program Files\lib`? That would be a bit awkward.

**Comment by JonasVautherin** [comment]
I was assuming something like `C:\Program Files\mavsdk\lib`, but I don't know what CMake does on Windows really :sweat_smile:. However from this:

> So after doing a local install I was still not able to find mavsdk.dll within the install directory. Only see it build/default.

my understanding was that `mavsdk.dll` is not installed correctly, even locally

**Comment by julianoes** [comment]
> mavsdk.dll within the install directory

The question is which one that is.

**Comment by Tzhao7** [comment]
Although this is technically incorrect, I was able to temporarily fix the dependency problem by moving a copy of mavsdk.dll into the same directory as my project executable.

**Comment by julianoes** [comment]
@Tzhao7 ok, do you have any suggestions what we should change? I really don't know how linking works properly on Windows.

**Comment by JonasVautherin** [comment]
> Also I noticed that the installed library found in C:\Program Files only contains mavsdk.lib and does not contain any .dll.

> mavsdk.dll is in build/default of the MAVSDK directory

Given [this information](https://stackoverflow.com/questions/913691/dll-and-lib-files-what-and-why):

> There are static libraries (LIB) and dynamic libraries (DLL) - but note that .LIB files can be either static libraries (containing object files) or import libraries (containing symbols to allow the linker to link to a DLL).

and assuming that the `mavsdk.lib` in this case is an import library, then my hunch is that `mavsdk.dll` should be installed next to `mavsdk.lib`, but it is not. Currently we install it [here](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/CMakeLists.txt#L92-L96).

**Comment by JonasVautherin** [comment]
Where is `mavsdk.lib`? `C:\Program Files\mavsdk\lib\mavsdk.lib`?

**Comment by Tzhao7** [comment]
Yeah it is in `C:\Program Files (x86)\mavsdk_superbuild\lib\mavsdk.lib`. I copied the mavsdk.dll from the cloned MAVSDK to the lib folder and the error continued to occur.

**Comment by JonasVautherin** [comment]
@Tzhao7: Would you mind trying to build and install again from the [fix-windows-install](https://github.com/mavlink/MAVSDK/tree/fix-windows-install) branch and tell me if that changes anything? I would expect `mavsdk.dll` to be installed in `:\Program Files (x86)\mavsdk_superbuild\bin\mavsdk.dll`.

**Comment by Tzhao7** [comment]
After building and installing from the fix-windows-install branch I was able to find `mavsdk.dll` in `:\Program Files (x86)\mavsdk_superbuild\bin\mavsdk.dll`. However after removing `mavsdk.dll` from my Visual Studio project I started to received the dependency error again.

**Comment by JonasVautherin** [comment]
Grmbl, I don't know where the dll should go, and if we are missing something else. My understanding is that the import library (`mavsdk.lib`) should have some kind of reference to `mavsdk.dll`. 

Do you know how to inspect `mavsdk.lib`? I don't know, something like `dumpbin.exe -headers mavsdk.lib` maybe? Just to see if there is a path or something there...

At least now it installs the DLL, so I think that's progress.

**Comment by Tzhao7** [comment]
I ran `dumpbin.exe -headers mavsdk.lib` and directed the output to a text file. I wasn't able to find an explicit path but there were references to `mavsdk.dll`. Here's a snippet of what one output paragraph looks like (rest of the output had similar-looking paragraphs):
`Version      : 0
  Machine      : 8664 (x64)
  TimeDateStamp: E1485C25
  SizeOfData   : 00000094
  DLL name     : mavsdk.dll
  Symbol name  : ?get_option@CameraImpl@mavsdk@@AEAA?AW4Result@Camera@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUOption@42@@Z (private: enum mavsdk::Camera::Result __cdecl mavsdk::CameraImpl::get_option(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct mavsdk::Camera::Option &))
  Type         : code
  Name type    : name
  Hint         : 12295
  Name         : ?get_option@CameraImpl@mavsdk@@AEAA?AW4Result@Camera@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUOption@42@@Z`

**Comment by JonasVautherin** [comment]
Can you try to move `mavsdk.dll` from `bin/` into `lib/`, so that it's next to `mavsdk.lib`? That was not working before, and I don't think that my PR changed anything about that, but just in case.

What I don't get is: assuming that it finds `lib/mavsdk.lib`, and then tries to find `mavsdk.dll` because of that `DLL name` field, then why doesn't it find it next to `mavsdk.lib`?

My other question would be: does it actually use `lib/mavsdk.lib`? What if you remove it entirely, does it still complain about "The code execution cannot proceed because mavsdk.dll was not found"?

**Comment by Tzhao7** [comment]
After moving `mavsdk.dll` from `bin/` into `lib/`, I was given the following error message when compiling the CMakeLists.txt:
![image](https://user-images.githubusercontent.com/59535719/152263251-f176165a-b00d-46d7-a48a-2c28627f64e6.png)
It seems like `lib/mavsdk.lib` is looking for `bin/mavsdk.dll`. Removing `lib/mavsdk.lib` entirely returned the following error message: 
![image](https://user-images.githubusercontent.com/59535719/152265561-1b96b11c-50b4-4d21-af54-16a623670be4.png)
However, as you said previously, when I tried moving `mavsdk.dll` next to `mavsdk.lib` before, I received those dependency errors. I'm not exactly sure what is going on either haha.

**Comment by JonasVautherin** [comment]
Wait but then it's looking for it now :thinking:. Are you sure you made a clean build with my PR?

**Comment by julianoes** [comment]
@Tzhao7 could you please report back if the PR helped (after a clean build)?

**Comment by Tzhao7** [comment]
Sorry for the delay...I made a clean build with the PR and moved mavsdk.dll into `lib/` but the runtime error still appears.

**Comment by julianoes** [comment]
@Tzhao7 ok do you have a suggestion what we could do to fix this? @JonasVautherin and I are both not using Windows normally, so we don't know how cmake on Windows is usually done.

**Comment by Tzhao7** [comment]
To be honest I am also not a native Windows user and do not know how cmake works either. The only way I was able to resolve the dependency error was by placing mavsdk.dll next to my project executable and I don't think this is a viable solution. I wonder if other Windows users had this problem after building and installing the SDK.

**Comment by julianoes** [comment]
> by placing mavsdk.dll next to my project executable and I don't think this is a viable solution.

This is usually what I do. :smirk:
