### ISSUE TITLE
Failsafe enabled: Nomanual control stick input  

### ISSUE THREAD

**Issue by dzywater** [mavlink/MAVSDK#1701]
I used px4 gazebo simulation to test offboard example(~/examples/offboard/offboard.cpp).

The iris takeoff and then land.

I tried to set parameters by some references
    set COM_RC_IN_MODE 1
    set NAV_RC_ACT 0
It showed same errors.

**Comment by julianoes** [comment]
WWhen you say "it did not work" what does happen instead?

**Comment by dzywater** [comment]
use mavsdk::Param::set_param_int("COM_RCL_EXCEPT", 4), it works.
