### ISSUE TITLE
MAVSDK Make Unknown Argument

### ISSUE THREAD

**Issue by altay434** [mavlink/MAVSDK#1707]
Hi when i try to build an example for simulation according to https://mavsdk.mavlink.io/main/en/cpp/quickstart.html
this command `cmake --build build -j4` gives `Unknown argument -j4` error. 

My Ubuntu version is 18.04 LTS

**Comment by altay434** [comment]
Hi again, i solved my problem with this guide https://mavsdk.mavlink.io/main/en/cpp/guide/build.html
Quick Guide causes that problem.

**Comment by julianoes** [comment]
We no longer support the default version of cmake on Ubuntu 18.04. Instead you have to update cmake as explained here:
https://askubuntu.com/a/1157132
