### ISSUE TITLE
mavsdk::System::has_gimbal() return false on Windows10

### ISSUE THREAD

**Issue by dzywater** [mavlink/MAVSDK#1714]
On Windows10, it is not workable (mavsdk::System::has_camera() return false ).
![windows10](https://user-images.githubusercontent.com/22073470/156682684-c67a7cf6-5b0d-42a8-a182-a030b7af886b.PNG)

On ubuntu20.04, it is workable (mavsdk::System::has_camera() return false ).
![ubuntu2004](https://user-images.githubusercontent.com/22073470/156682755-2d53179a-86da-42ad-84aa-ef67c593cfc5.png)

I used gazebo_typhoon_h480.

**Comment by JonasVautherin** [comment]
How is that different from https://github.com/mavlink/MAVSDK/issues/1710?

**Comment by dzywater** [comment]
> How is that different from #1710?
Use gazebo_typhoon_h480
On ubuntu20.04, mavsdk::System::has_gimbal()  return true, mavsdk::System::has_camera() return false;

On Windows10, mavsdk::System::has_gimbal()  return false, mavsdk::System::has_camera() return false;

That is,

On Ubuntu20.04, gimbal is workable, but camera is not.
On Windows10, both gimbal and camera are not workable.

**Comment by dzywater** [comment]
> How is that different from #1710?
Use gazebo_typhoon_h480
On ubuntu20.04, mavsdk::System::has_gimbal()  return true, mavsdk::System::has_camera() return false;

On Windows10, mavsdk::System::has_gimbal()  return false, mavsdk::System::has_camera() return false;

That is,

On Ubuntu20.04, gimbal is workable, but camera is not.
On Windows10, both gimbal and camera are not workable.

**Comment by julianoes** [comment]
On Windows, which simulation and which model are you using?

**Comment by dzywater** [comment]
1.Run gazebo_typhoon_h480 simulator On ubuntu20.04.
2.Map Ubuntu port14540 to Windows port 14540 by MavRouter.
3.On Windows, use MavSDK1.0.8 to program.

**Comment by julianoes** [comment]
Aha, my guess is that something with the forwarding goes wrong. What mavlink-router version are you using?

**Comment by julianoes** [comment]
No more answer, closing.
