### ISSUE TITLE
Mission::upload_mission_with_progress_async() ends with progress nan - correct?

### ISSUE THREAD

**Issue by reedev** [mavlink/MAVSDK#1719]
Hi,

I am using Mission::upload_mission_with_progress_async() to upload a mission and the progress is increased correctly. Only the last reported progress is nan, is this correct?

Double check: does progress == 1.0 mean that the upload is successful? I guess so but just double checking...

Thanks!

**Comment by julianoes** [comment]
Could it be that you get 100% progress and then a result successful? I think you should only read the progress when the result is `Next` and ignore progress otherwise.

**Comment by reedev** [comment]
Yes, indeed, that's what is returned. Ok, I will check for Next then. Thanks!

**Comment by julianoes** [comment]
Just re-open if I was wrong ;).
