### ISSUE TITLE
Building MAVSDK v1.0.8 with gcc-4.9

### ISSUE THREAD

**Issue by BestITUserEUW** [mavlink/MAVSDK#1724]
Hey, 
i'm currently trying to build libmavsdk with gcc-4.9. It seems that some test requires CXX17. Is it possible to build it cc-4.9?

Error Output Log:
CMake Error in src/CMakeLists.txt:
  Target "unit_tests_runner" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.

CMake Error in src/mavsdk/CMakeLists.txt:
  Target "mavsdk" requires the language dialect "CXX17" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.

CMake Error in src/third_party/gtest/googlemock/CMakeLists.txt:
  Target "gmock" requires the language dialect "CXX17" , but CMake does not
  know the compile flags to use to enable it.

CMake Error in src/third_party/gtest/googlemock/CMakeLists.txt:
  Target "gmock_main" requires the language dialect "CXX17" , but CMake does
  not know the compile flags to use to enable it.

CMake Error in src/third_party/gtest/googletest/CMakeLists.txt:
  Target "gtest" requires the language dialect "CXX17" , but CMake does not
  know the compile flags to use to enable it.

CMake Error in src/third_party/gtest/googletest/CMakeLists.txt:
  Target "gtest_main" requires the language dialect "CXX17" , but CMake does
  not know the compile flags to use to enable it.

CMake Error in src/integration_tests/CMakeLists.txt:
  Target "integration_tests_runner" requires the language dialect "CXX17"
  (with compiler extensions), but CMake does not know the compile flags to
  use to enable it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
[ERROR]: build failed with error Code: 1

**Comment by julianoes** [comment]
MAVSDK C++ is using C++17 features, so you need a compiler that supports these. GCC 4.9 is definitely too old, sorry.
