### ISSUE TITLE
Camera::set_setting_async send request only to the first camera

### ISSUE THREAD

**Issue by persuader72** [mavlink/MAVSDK#1728]
Working with a system with two cameras (#1705) i noticed that the camera settings requests using (`Camera::set_setting_async`) are  always sent to the first camera, regardless the real camera target.

The problem resides in the  `MAVLinkParameters` class that in the` MAVLinkParameters::do_work` function use predefined constants depending on the `work->defined` value has target components.

I want to try to add a more generic way to set the component target in  the MAVLinkParameters class.  

My question is: It's better to (1) add a component id argument (with a default value) to already existent functions like `SystemImpl::set_param_async`, or is better to (2) add a new whole set of functions that will accept also a component id?

**Comment by julianoes** [comment]
Ah yes, that sounds like a correct assessment.

Mmm, overloading with default arguments or add more functions? :thinking: I would probably use these functions:
https://github.com/mavlink/MAVSDK/blob/4dcee2b14945a80276f1b30abd99088ed7009d9f/src/mavsdk/core/system_impl.h#L169-L172
And then add the overload with default. I wouldn't use the functions which already have the default for `extended`.
