### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by ShinjiIkari256** [mavlink/MAVSDK#1798]
Excuse me, I don't need logs. How can I disable this logs?

![image](https://user-images.githubusercontent.com/39000784/171622851-97d31af3-63e7-4e89-b7e0-43ffca8f8f7d.png)

**Comment by julianoes** [comment]
Here is an API to implement your own logging function:
https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/include/mavsdk/log_callback.h#L18

So you create your own callback which doesn't do anything and then subscribe with it.
