### ISSUE TITLE
Param Server - exception when using custom string parameter

### ISSUE THREAD

**Issue by Consti10** [mavlink/MAVSDK#1805]
I am trying to accomplish the following:
1) Have a parameter server (supposed to run on the OHD Ground station) for OHD related settings

2) test out the set / get -equivalents inside QOpenHD for then changing the settings.

So far I am just trying things out, but while doing so I stumpled across the following issue:

I add a custom (string) parameter to the server side:
https://github.com/OpenHD/Open.HD/blob/consti-test/OpenHD/ohd_telemetry/tests/test_mavsdk.cpp#L40

And just for testing, request all the parameters from the Ground controll application side: 
` auto result=paramOhdGround->get_all_params();`

Both the server and client side crash. On the server side, the output is:
```
test_mavsdk: /media/consti10/ade719d9-e80a-46da-8802-58ca3b8e08bc1/1_ohd-dev/MAVSDK/src/mavsdk/core/mavlink_parameters.cpp:1999: float mavsdk::MAVLinkParameters::ParamValue::get_4_float_bytes_bytewise() const: Assertion `false' failed.
[12:24:24|Error] Unknown type (mavlink_parameters.cpp:1998)
```

On the client side the output is less usefull:
```
See: https://mavsdk.mavlink.io/main/en/cpp/troubleshooting.html#user_callbacks
terminate called after throwing an instance of 'std::future_error'
  what():  std::future_error: No associated state
```

Any ideas ?

**Comment by Consti10** [comment]
The issue above can be easily reprodcued by adding 2 lines of code to the autopilot_server example:

https://github.com/OpenHD/MAVSDK/commit/753f6553970fbda491fc66f4711a193dcce940db

**Comment by Consti10** [comment]
Also, a question not a bug:

For commands or parameters set - aka stuff that is acknowledged - is there some type of re-transmission inside mavsdk ?

**Comment by JonasVautherin** [comment]
> For commands or parameters set - aka stuff that is acknowledged - is there some type of re-transmission inside mavsdk ?

Yes those are the [different](https://mavlink.io/en/services/command.html) [mavlink](https://mavlink.io/en/services/parameter.html) [microservices](https://mavlink.io/en/services/parameter_ext.html) :+1:.

> The issue above can be easily reprodcued by adding 2 lines of code to the autopilot_server example

Nice, thanks for sharing a reproducible example! This looks like a bug indeed. Would you be willing to look into debugging it inside MAVSDK?

**Comment by Consti10** [comment]
> > For commands or parameters set - aka stuff that is acknowledged - is there some type of re-transmission inside mavsdk ?
> 
> Yes those are the [different](https://mavlink.io/en/services/command.html) [mavlink](https://mavlink.io/en/services/parameter.html) [microservices](https://mavlink.io/en/services/parameter_ext.html) +1.
> 
> > The issue above can be easily reprodcued by adding 2 lines of code to the autopilot_server example
> 
> Nice, thanks for sharing a reproducible example! This looks like a bug indeed. Would you be willing to look into debugging it inside MAVSDK?


Nice. I'l look into the source code more, still need to understand who/ what does the retransmission and how to change stuff like n of retransmissions usw.

Regarding the bug:

I've looked a bit into the source code. I don't fully understand it, but in short:

`paramServer.provide_param_custom("OHD_UART_NAME","/dev/ttyUSB0");`

is not a mavlink parameter but a mavlink extended parameter:
https://mavlink.io/en/services/parameter_ext.html

But for some reason the receiver calls 
` MAVLinkParameters::ParamValue::get_4_float_bytes_bytewise()`

on the extended parameter (which obviously is a string, not a float or int).

So 
` MAVLinkParameters::ParamValue::get_4_float_bytes_bytewise()`
should not be called - this switch is  probably messed up:
https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/mavlink_parameters.cpp#L795

why - cannot tell yet ;)

**Comment by Consti10** [comment]
So the issue seems to be created by the requesting side when calling:
`get_all_params();`

since when I explicitly request it using the custom keyword:
`get_param_custom("OHD_UART_NAME");`

It works. So when writing the implementation in mavsdk, the author did not consider that on a call to
`get_all_params()`

the server might provide mixed mavlink params and mavlink custom params.

**Comment by Consti10** [comment]
Another thing, when looking at the code:
`get_all_params()`
would fetch all parameters (extended and non-extended).
But the imlementation only uses:
`mavlink_msg_param_request_list_pack`
and misses
`mavlink_msg_param_ext_request_list_pack`

So in theory get_all_params() should completely ignore extended params anyways ?

**Comment by JonasVautherin** [comment]
Honestly not completely sure. I'd say if the `param` plugin can automatically handle param vs param_ext, then that's better.

**Comment by JonasVautherin** [comment]
> Also, can you maybe get the person who wrote the param impl. into here ? I am a bit lost with exactly how things work in there.

@julianoes would know better, but he is on holiday at the moment, I believe :slightly_smiling_face:

**Comment by Consti10** [comment]
thank you, I guess we have to wait then :/ I think the issue here is not easily fixable, at least for me. The more I read the code, the more worried I get how abstract the mavlink_parameters class actually is (aka what exactly can you use it for - to **exchange configuration settings between MAVLink components** or **to exchange non-extended parameters between ground controll and PX4 FC and extended parameters between ground controll and a camera component**

Because I read comments like 
`// FIXME: extended currently always go to the camera component`
and
`MAV_COMP_ID_AUTOPILOT1); // FIXME: what should the component be?
`

which makes me worried if we can even use mavsdk "parameters" for our intended purpose
(exchange non-extended and extended parameters between mavlink components)

**Comment by JonasVautherin** [comment]
> which makes me worried if we can even use mavsdk "parameters" for our intended purpose
(exchange non-extended and extended parameters between mavlink components)

The functions to set params (e.g. `set_param_int`) take a component id and a boolean telling them if it should use the extended microservice or not:

```c++
MAVLinkParameters::Result SystemImpl::set_param_int(
    const std::string& name,
    int32_t value,
    std::optional<uint8_t> maybe_component_id,
    bool extended)
{
    return _params.set_param_int(name, value, maybe_component_id, extended);
}
```

So it is possible at the lower level. Maybe even from the MavlinkPassthrough plugin.

Now the question is the interface: should the param plugin allow you to set the component id, or should the component id be abstracted away by MAVSDK? My intuition would be that it should be abstracted away. For instance, the camera plugin uses the params under the hood, but exposed as camera settings.

So somehow the param plugin talks to the autopilot, and the param server maybe should represent an autopilot? Then the camera plugin talks to a camera, and the camera server uses params under the hood, but not directly the params server.

What do you think?

**Comment by Consti10** [comment]
A cuple of updates:
1) I found the reason for the client side crash - this one is a simple fix, the all_params callback takes a reference but this reference can go out of scope, resulting in a crash.

2) With the fix I proposed before, the get_all_params() now doesn't work anymore if there are parameters that need the ext. protocoll - the class would have to track the count of parameters seperatively for ext and non-ext.

**Comment by JonasVautherin** [comment]
Oh nice! Could you open a PR with your fix for 1? That's already worth it, right?

**Comment by Consti10** [comment]
Sure, I'd love to talk to the author though, these changes might have implications one cannot see immediately.

get_all_params() is now working again, but obviosly only returns parameters that do not neccessarily need the extended protocoll.

Ideally, we'l have 
get_all_params_non_extended() and
get_all_params_extended() soon.

**Comment by julianoes** [comment]
Interesting, I will have a closer look next week.

**Comment by Consti10** [comment]
I've been working on mavlink_parameters for the last couple of days. My goal has been to reduce the amount of duplicated code,without reducing the public functionalities (which are thought out quite well). 

So far, I have found a ton of cases where by just using templates or similar the duplicated code collapses nicely.

The only one's that are missing so far are the set_param_xxx methods from the non-servier (client side), which are extra tricky due to the  `// We need to know the exact int type first.` part

**Comment by julianoes** [comment]
> The only one's that are missing so far are the set_param_xxx methods from the non-servier (client side), which are extra tricky due to the // We need to know the exact int type first. part

Exactly, that's where it gets tricky.

**Comment by julianoes** [comment]
Uh oh, I hope you built on top of my refactoring!?

https://github.com/mavlink/MAVSDK/pull/1772

**Comment by Consti10** [comment]
Oh dang, no, I did not know such a task is already underway - I totally agree though, splitting them into 2 is a really good idea.

**Comment by Consti10** [comment]
Having a quick glance at it, one of the steps we both did is to extrakt ParamValue out ;) nice to see we are on the same page then.

**Comment by Consti10** [comment]
And looking into your pull request, merging the 2 branches directly probably won't work, but especially since recv/ server are now split I think it would be easy for me to just copy stuff over and create a new pull request based on your pr request. Then I also have to think a bit more about my commit messages ;)

Do you have any local changes in regard to parameters or is this pull request still up to date ?

**Comment by Consti10** [comment]
One more thing I'd like to put out for discussion:

Should the server-side make sure that parameter's types are immutable ?

For example, when the client sends a [PARAM_SET](https://mavlink.io/en/messages/common.html#PARAM_SET) message, but the type of the message doesn't match the internally stored type, what does the server do ?

In my opininion, the server should then ignore the update and respond with a PARAM_VALUE with the unchanged type & value for non-extended and a [PARAM_EXT_ACK](https://mavlink.io/en/messages/common.html#PARAM_EXT_ACK) with error code set in case of extended.

Unfortunately, the mavlink specification doesn't give out a quideline here, but I'd think that this is a fair restrictive quide line.

**Comment by Consti10** [comment]
> And looking into your pull request, merging the 2 branches directly probably won't work, but especially since recv/ server are now split I think it would be easy for me to just copy stuff over and create a new pull request based on your pr request. Then I also have to think a bit more about my commit messages ;)
> 
> Do you have any local changes in regard to parameters or is this pull request still up to date ?

Please let me know soon, r.n I still have all the changes in my head and could easily just manually copy them over.

**Comment by julianoes** [comment]
> Do you have any local changes in regard to parameters or is this pull request still up to date ?

No, that's all pushed.

> For example, when the client sends a [PARAM_SET](https://mavlink.io/en/messages/common.html#PARAM_SET) message, but the type of the message doesn't match the internally stored type, what does the server do ?

Hmm. The problem is that there is no "nack type error" for that case. So according to [the docs](https://mavlink.io/en/services/parameter.html#write) it says:

> The Drone must acknowledge the PARAM_SET by broadcasting a PARAM_VALUE even if the write operation fails. In this case the PARAM_VALUE will be the current/unchanged parameter value.

> In my opininion, the server should then ignore the update and respond with a PARAM_VALUE with the unchanged type & value for non-extended and a [PARAM_EXT_ACK](https://mavlink.io/en/messages/common.html#PARAM_EXT_ACK) with error code set in case of extended.

Ah yes, what you said :smile:.

**Comment by Consti10** [comment]
> > Do you have any local changes in regard to parameters or is this pull request still up to date ?
> 
> No, that's all pushed.
> 
> > For example, when the client sends a [PARAM_SET](https://mavlink.io/en/messages/common.html#PARAM_SET) message, but the type of the message doesn't match the internally stored type, what does the server do ?
> 
> Hmm. The problem is that there is no "nack type error" for that case. So according to [the docs](https://mavlink.io/en/services/parameter.html#write) it says:
> 
> > The Drone must acknowledge the PARAM_SET by broadcasting a PARAM_VALUE even if the write operation fails. In this case the PARAM_VALUE will be the current/unchanged parameter value.
> 
> > In my opininion, the server should then ignore the update and respond with a PARAM_VALUE with the unchanged type & value for non-extended and a [PARAM_EXT_ACK](https://mavlink.io/en/messages/common.html#PARAM_EXT_ACK) with error code set in case of extended.
> 
> Ah yes, what you said smile.

Thanks for letting me know. I'l see if I can merge it today then.

Regarding the nack type error:
I am asking because right now the behaviour is to overwrite the value  type:
https://github.com/mavlink/MAVSDK/blob/pr-split-mavlink-params/src/mavsdk/core/mavlink_parameter_receiver.cpp#L167

**Comment by Consti10** [comment]
@julianoes 

I am mostly done with the param providing part (mavlink_parameter_receiver.cc / .h )
https://github.com/OpenHD/MAVSDK/blob/b3d9651391d888d949274095baa1f6ee5e7a4115/src/mavsdk/core/mavlink_parameter_receiver.h

There are 2 TODO's left -
1) what to do if the value to set matches the current value (for examle, provider currently has value x=1.0 and gets a reques to change x to 1.0 ) - what response do we send in this case and do we call the listeners
2) currently, using indices instead of the name strings as ID's is unsupported, even though in the mavlink specification
(Request the value of a specific parameter using **EITHER** its param_id or param_index )




Next up is the requesting / mavlink_parameter_sender.cc / .h part, this one is a bit more complicated. But I should be done in the next coule of days.

**Comment by julianoes** [comment]
I believe this has been fixed.
