### ISSUE TITLE
Fail to build v1.4.0 or later on armv7

### ISSUE THREAD

**Issue by Katawann** [mavlink/MAVSDK#1817]
Since version 1.4.0 (v1.3.1 and before is ok), I can not build my code on a Raspberry Pi 3b+ with the following issue:

```
/usr/include/mavsdk/plugins/mavlink_passthrough/mavlink_include.h:3:10: fatal error: mavlink/v2.0/common/mavlink.h: No such file or directory
#include "mavlink/v2.0/common/mavlink.h"
```

I will dig into the modifications but I just open an issue if @julianoes or @JonasVautherin you already see what it could be. I will try with a simple MAVSDK example to see if the issue remains

**Comment by JonasVautherin** [comment]
And do you set `-DMAVLINK_HEADERS`, like [in the CI](https://github.com/mavlink/MAVSDK/blob/main/.github/workflows/main.yml#L308)? This is fairly new, and it should work with the default, but worth having a look :+1:.

**Comment by Katawann** [comment]
I do something like this in my Dockerfile:

```
RUN wget https://github.com/mavlink/MAVSDK/releases/download/v${MAVSDK_VERSION}/libmavsdk-dev_${MAVSDK_VERSION}_${MAVSDK_PKG}.deb \
&& sudo dpkg -i libmavsdk-dev_${MAVSDK_VERSION}_${MAVSDK_PKG}.deb \
&& sudo rm libmavsdk-dev_${MAVSDK_VERSION}_${MAVSDK_PKG}.deb
```

But you mean I need to add it if I build some source ? Looks like this flag has been added two months ago so it is already in v1.3.1 as well as v1.4.0 so the debian package should have this modification right ?

**Comment by JonasVautherin** [comment]
Oh, sorry, I misunderstood. So you install the package, but then it fails building your code. :thinking:

**Comment by Katawann** [comment]
exactly yes.

Would it be possible that there are extra quotes on the debian install [here](https://github.com/mavlink/MAVSDK/blob/e619fbbdfee674a346d8ce1de70d99426c59d7c9/debian/rules#L15) ? I don't see them in the in the CI

**Comment by JonasVautherin** [comment]
Not sure :confused:. Did you try installing a package on your laptop and e.g. compiling the examples? Would be faster to debug than doing everything on the RPi :grin:

**Comment by julianoes** [comment]
I had to do some more modifications to this mavlink header inclusion in this PR: https://github.com/mavlink/MAVSDK/pull/1768

It would be good to have a way to reproduce this locally in docker.

**Comment by Katawann** [comment]
Install package the pacakge ubuntu20.04_amd64 on a linux host works fine. To test locally would it work if I build the package for armv7 and use it in my dockerfile instead of the v1.4.3 ?

**Comment by Katawann** [comment]
I just tried to build with main branch and I still have the issue. I will try with the PR you mentioned @julianoes and see if it fixes my issue

**Comment by Katawann** [comment]
The proper installation of mavlink header in the CMakelists in this [commit](https://github.com/mavlink/MAVSDK/commit/0c8e2367952b3233669739d439a13f2ccb568470) fixes my issue. 

Thank you ! I will work with locally build deb package until there is a new release including this modification.
