### ISSUE TITLE
Lack of a "streaming_server"

### ISSUE THREAD

**Issue by dayjaby** [mavlink/MAVSDK#1818]
Should we create a new plugin for managing video streams or should they be part of the camera_server?

Purpose should be to have a unified way to respond to things like `MAV_CMD_REQUEST_VIDEO_STREAM_INFORMATION` and reacting to parameter changes of "CAM_VIDSTREAM" to do video switching.

**Comment by JonasVautherin** [comment]
I would say this is part of the `camera_server`. If the camera server exposes, say, an rtsp stream, then it should say it in the VIDEO_STREAM_INFORMATION message.
