### ISSUE TITLE
autopilot_server vs 1.4.3 does not compile

### ISSUE THREAD

**Issue by edhage** [mavlink/MAVSDK#1836]
Seems ServerComponentType and server_component_by_type is unknown.
I installed libmavsdk-dev_1.4.3_ubuntu20.04_amd64.deb on Ubuntu 20.04 (latest) rather than mavsdk_0.37.0_ubuntu20.04_amd64.deb as mentioned in the Quick Start documentation. I did not find a mavsdk_1.4.3_ubuntu20.04 so assumed libmavsdk-dev* was the successor. So I expected below compilation to work.

edward@x:~ /MAVSDK/examples/autopilot_server$ ls
autopilot_server.cpp  build  CMakeLists.txt
edward@x:~ /MAVSDK/examples/autopilot_server$ cmake --build build -j4
Scanning dependencies of target autopilot_server
[ 50%] Building CXX object CMakeFiles/autopilot_server.dir/autopilot_server.cpp.o
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp: In lambda function:
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:72:26: error: ‘class mavsdk::Mavsdk’ has no member named ‘server_component_by_type’
   72 |             mavsdkTester.server_component_by_type(Mavsdk::ServerComponentType::Autopilot);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:72:59: error: ‘mavsdk::Mavsdk::ServerComponentType’ has not been declared
   72 |             mavsdkTester.server_component_by_type(Mavsdk::ServerComponentType::Autopilot);
      |                                                           ^~~~~~~~~~~~~~~~~~~
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:75:64: error: no matching function for call to ‘mavsdk::ParamServer::ParamServer(<brace-enclosed initializer list>)’
   75 |         auto paramServer = mavsdk::ParamServer{server_component};
      |                                                                ^
In file included from /home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:9:
/usr/include/mavsdk/plugins/param_server/param_server.h:256:5: note: candidate: ‘mavsdk::ParamServer::ParamServer(const mavsdk::ParamServer&)’
  256 |     ParamServer(const ParamServer& other);
      |     ^~~~~~~~~~~
/usr/include/mavsdk/plugins/param_server/param_server.h:256:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/param_server/param_server.h:52:14: note: candidate: ‘mavsdk::ParamServer::ParamServer(std::shared_ptr<mavsdk::System>)’
   52 |     explicit ParamServer(std::shared_ptr<System> system); // new
      |              ^~~~~~~~~~~
/usr/include/mavsdk/plugins/param_server/param_server.h:52:14: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/param_server/param_server.h:39:14: note: candidate: ‘mavsdk::ParamServer::ParamServer(mavsdk::System&)’
   39 |     explicit ParamServer(System& system); // deprecated
      |              ^~~~~~~~~~~
/usr/include/mavsdk/plugins/param_server/param_server.h:39:14: note:   conversion of argument 1 would be ill-formed:
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:76:68: error: no matching function for call to ‘mavsdk::TelemetryServer::TelemetryServer(<brace-enclosed initializer list>)’
   76 |         auto telemServer = mavsdk::TelemetryServer{server_component};
      |                                                                    ^
In file included from /home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:11:
/usr/include/mavsdk/plugins/telemetry_server/telemetry_server.h:1060:5: note: candidate: ‘mavsdk::TelemetryServer::TelemetryServer(const mavsdk::TelemetryServer&)’
 1060 |     TelemetryServer(const TelemetryServer& other);
      |     ^~~~~~~~~~~~~~~
/usr/include/mavsdk/plugins/telemetry_server/telemetry_server.h:1060:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/telemetry_server/telemetry_server.h:54:14: note: candidate: ‘mavsdk::TelemetryServer::TelemetryServer(std::shared_ptr<mavsdk::System>)’
   54 |     explicit TelemetryServer(std::shared_ptr<System> system); // new
      |              ^~~~~~~~~~~~~~~
/usr/include/mavsdk/plugins/telemetry_server/telemetry_server.h:54:14: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/telemetry_server/telemetry_server.h:41:14: note: candidate: ‘mavsdk::TelemetryServer::TelemetryServer(mavsdk::System&)’
   41 |     explicit TelemetryServer(System& system); // deprecated
      |              ^~~~~~~~~~~~~~~
/usr/include/mavsdk/plugins/telemetry_server/telemetry_server.h:41:14: note:   conversion of argument 1 would be ill-formed:
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:77:66: error: no matching function for call to ‘mavsdk::ActionServer::ActionServer(<brace-enclosed initializer list>)’
   77 |         auto actionServer = mavsdk::ActionServer{server_component};
      |                                                                  ^
In file included from /home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:12:
/usr/include/mavsdk/plugins/action_server/action_server.h:296:5: note: candidate: ‘mavsdk::ActionServer::ActionServer(const mavsdk::ActionServer&)’
  296 |     ActionServer(const ActionServer& other);
      |     ^~~~~~~~~~~~
/usr/include/mavsdk/plugins/action_server/action_server.h:296:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/action_server/action_server.h:52:14: note: candidate: ‘mavsdk::ActionServer::ActionServer(std::shared_ptr<mavsdk::System>)’
   52 |     explicit ActionServer(std::shared_ptr<System> system); // new
      |              ^~~~~~~~~~~~
/usr/include/mavsdk/plugins/action_server/action_server.h:52:14: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/action_server/action_server.h:39:14: note: candidate: ‘mavsdk::ActionServer::ActionServer(mavsdk::System&)’
   39 |     explicit ActionServer(System& system); // deprecated
      |              ^~~~~~~~~~~~
/usr/include/mavsdk/plugins/action_server/action_server.h:39:14: note:   conversion of argument 1 would be ill-formed:
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:95:74: error: no matching function for call to ‘mavsdk::MissionRawServer::MissionRawServer(<brace-enclosed initializer list>)’
   95 |         auto missionRawServer = mavsdk::MissionRawServer{server_component};
      |                                                                          ^
In file included from /home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:13:
/usr/include/mavsdk/plugins/mission_raw_server/mission_raw_server.h:245:5: note: candidate: ‘mavsdk::MissionRawServer::MissionRawServer(const mavsdk::MissionRawServer&)’
  245 |     MissionRawServer(const MissionRawServer& other);
      |     ^~~~~~~~~~~~~~~~
/usr/include/mavsdk/plugins/mission_raw_server/mission_raw_server.h:245:5: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/mission_raw_server/mission_raw_server.h:54:14: note: candidate: ‘mavsdk::MissionRawServer::MissionRawServer(std::shared_ptr<mavsdk::System>)’
   54 |     explicit MissionRawServer(std::shared_ptr<System> system); // new
      |              ^~~~~~~~~~~~~~~~
/usr/include/mavsdk/plugins/mission_raw_server/mission_raw_server.h:54:14: note:   conversion of argument 1 would be ill-formed:
/usr/include/mavsdk/plugins/mission_raw_server/mission_raw_server.h:41:14: note: candidate: ‘mavsdk::MissionRawServer::MissionRawServer(mavsdk::System&)’
   41 |     explicit MissionRawServer(System& system); // deprecated
      |              ^~~~~~~~~~~~~~~~
/usr/include/mavsdk/plugins/mission_raw_server/mission_raw_server.h:41:14: note:   conversion of argument 1 would be ill-formed:
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:99:27: error: ‘IncomingMissionHandle’ is not a member of ‘mavsdk::MissionRawServer’
   99 |         MissionRawServer::IncomingMissionHandle handle =
      |                           ^~~~~~~~~~~~~~~~~~~~~
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:108:18: error: expected primary-expression before ‘)’ token
  108 |                 });
      |                  ^
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp: In function ‘int main(int, char**)’:
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:162:13: error: ‘NewSystemHandle’ is not a member of ‘mavsdk::Mavsdk’
  162 |     Mavsdk::NewSystemHandle handle = mavsdk.subscribe_on_new_system([&mavsdk, &prom, &handle]() {
      |             ^~~~~~~~~~~~~~~
/home/edward/MAVSDK/examples/autopilot_server/autopilot_server.cpp:174:6: error: expected primary-expression before ‘)’ token
  174 |     });
      |      ^
make[2]: *** [CMakeFiles/autopilot_server.dir/build.make:63: CMakeFiles/autopilot_server.dir/autopilot_server.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/autopilot_server.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by JonasVautherin** [comment]
The API has changed in MAVSDK `main`, breaking compatibility with v1.4.3 (the next release from `main` will be v2.0.0).

You should use the examples from tag v1.4.3, or compile MAVSDK `main` from sources and use it against the examples in `main`.

Does that make sense?

**Comment by edhage** [comment]
Hello Jonas, I was not aware that the 1.4 was another branch (just loaded the newest). Thanks for pointing that out to me . I want to add Autopilot to ROS2 robot  to be able to communicate with QGroundControl for mission planning in MAVSDK. What would be the recommended branch, main or 1.4?

**Comment by julianoes** [comment]
main is for the latest refactorings towards v2.
v1.4 for now is probably recommended, unless you need things from main.
