### ISSUE TITLE
FollowMe integration tests

### ISSUE THREAD

**Issue by JonasVautherin** [mavlink/MAVSDK#1845]
The [integration tests](https://github.com/mavlink/MAVSDK/blob/main/src/integration_tests/follow_me.cpp#L19) say:

> /* Updated FollowMe only works from PX4 v1.13, as it went through refactoring */

But I thought it had not been merged in v1.13.0. Has it?

@junwoo091400 FYI

**Comment by junwoo091400** [comment]
Created a PR for it! It is NOT in v1.13, and the PR is necessary :D
