### ISSUE TITLE
Changing from offboard mode to mission mode

### ISSUE THREAD

**Issue by MrPrietix** [mavlink/MAVSDK#1858]
Hi 

I am loading a mission to the drone, then I am starting offboard mode and when it has reached an altitude I change to mission mode, these changes of different modes are done with an onboard computer. All of this is performed without the RC connected. Furthermore, the arming is done with the onboard computer. 

Nevertheless, when the drone changes to mission mode, it wants to reach a higher altitude different that the initial 5 meters specified on QGC when designing the mission. When it comes to the mission mode I am just running the `MissionRaw::Result start_mission_result = mission_raw->start_mission();` without loading any mission with mavsdk. I am supposing that when I run `MissionRaw::Result start_mission_result = mission_raw->start_mission();` the drone automatically takes the mission in the flight controller.

Can anybody help me?

**Comment by JonasVautherin** [comment]
Everything you said makes sense to me :+1:.

If you start the mission from QGC, does it work?

**Comment by MrPrietix** [comment]
Yes, it works, but when changing the mode with mavsdk using an onboard computer seems to end in changing the altitude of waypoints. So, I do not know what it can be.

**Comment by JonasVautherin** [comment]
The waypoints are saved in the Autopilot, MAVSDK cannot change them without re-uploading the mission (in which case you could download it from QGC and see that the altitude changed).

> All of this is performed without the RC connected.

Are you sure the drone doesn't just go to RTL as a failsafe? To me that would explain why it gains altitude :thinking:

**Comment by MrPrietix** [comment]
When I analyze the logfiles it enters in mission mode, and there is nothing regarding RTL. So I guess it does not enter in RTL.

**Comment by MrPrietix** [comment]
In the case of entering in RTL, what do you think would be the cause of entering in RTL mode?

**Comment by JonasVautherin** [comment]
I was guessing an RC loss, but really I don't know. I just don't see how MAVSDK would change the mission altitude. It's not really a thing: mission items ("waypoints") are uploaded to PX4, and then when you tell PX4 to go in `mission` mode, it executes them. MAVSDK should put PX4 in mission mode just like QGC does :thinking:.

I guess my question was: are you sure that it is in mission mode, or could it be in another mode (like RTL, which is a mode that could start by gaining altitude in some situations)

**Comment by MrPrietix** [comment]
I will leave a flight log regarding the flight. In offboard mode it reaches the desired altitude 5m with respect to the landing altitude, but then in mission the altitude setpoint increases. Let me know if you see anything strange.

https://logs.px4.io/plot_app?log=0d0df6e7-1248-495d-9a1d-67cd14af68e1

**Comment by MrPrietix** [comment]
And thanks for the fast answers

**Comment by julianoes** [comment]
Just while looking at your log I saw that [thrust correlates with your mag](https://logs.px4.io/plot_app?log=0d0df6e7-1248-495d-9a1d-67cd14af68e1#Nav-Thrust-and-Magnetic-Field) which means that you mean is too close to your power wiring or motors. I'd suggest using a GPS mast, or if you're already doing that, make sure that the external mag in the GPS board is used.

---
Now that aside, if you look at the [altitude plot](https://logs.px4.io/plot_app?log=0d0df6e7-1248-495d-9a1d-67cd14af68e1#Nav-Altitude-Estimate) you can see that it sets a altitude setpoint at around 175m (this tiny yellow circle), and then climbs to it.

My assumption is that this is really the mission you set it to. Can you show the mission that you set? E.g. the QGC mission plan file, or a screenshot of it. I would be interested in the altitude that you set, as well as the frame. Unfortunately, the mission is not logged to ulog, so I can't see that.

**Comment by MrPrietix** [comment]
This is an example of a mission we are running, where the first item has the doJumpId set to 2. The reason is that my team removed the default takeoff, but when configuring the mission, they created a takeoff item that does not send the takeoff command but sends the altitude to be taken into consideration during the takeoff. Could it be the doJumpId the problem?
Nevertheless, in simulation, everything works perfectly.

Regarding the frame, it is the Quadrotor X.
[mission_plan_custom.txt](https://github.com/mavlink/MAVSDK/files/9130317/mission_plan_custom.txt)

**Comment by julianoes** [comment]
I'm confused. I'm looking at a plan with 2 items and a doJumpId of 2 and 3 respectively. I don't even know how this works. The altitude itself looks like just 5m for both of them.

> they created a takeoff item that does not send the takeoff command but sends the altitude to be taken into consideration during the takeoff.

I don't know how you are doing that but I would guess something is wrong with that.

Or to put it differently: you are telling me that you are doing some magic with the mission items but the altitude is not correct but you also don't actually show me in detail what you're doing so I can't really help.

**Comment by MrPrietix** [comment]
By using a default mission file without our modifications it works. So it is solved. Nevertheless, thank you.
