### ISSUE TITLE
Running example takeoff_and_land compiles errors on Macos

### ISSUE THREAD

**Issue by ayomidebajo** [mavlink/MAVSDK#1867]
After compiling the SDK and running the px4 simulator, I get this error when I run the first example (i.e takeoff_and_land)

This is the error below.
<img width="1496" alt="Screenshot 2022-07-21 at 12 52 39" src="https://user-images.githubusercontent.com/54250291/180207816-a842c468-e6d1-4f9e-aaf8-4c7675f83cc0.png">

Note that I can control the drone from px4 using `commander takeoff` and `commander land`

Please is there anything I did wrong, I'm using MACOS Montenery by the way.

**Comment by ayomidebajo** [comment]
The first output was different because I tried fixing the error, but it compiled to another error, so I reversed what I fixed. I don't have any experience writing c++😅

**Comment by JonasVautherin** [comment]
Feels like you are using a new example with an older version of MAVSDK. Please use the examples from the tag that corresponds to your MAVSDK version (if you use `main`, take the examples from `main`, if you use `v1.4.4`, take the examples from tag `v1.4.4`).

**Comment by ayomidebajo** [comment]
I downloaded the `v1.4.4` and it gave me the same error. I checked the docs. I use an M1 chip and the SDK doesn't really support M1 chip users for now 🥲

**Comment by JonasVautherin** [comment]
> I downloaded the v1.4.4 and it gave me the same error.

What did you download? A package?

> I use an M1 chip and the SDK doesn't really support M1 chip users for now smiling_face_with_tear

If you build from sources, I don't see why it would not work.

Could you explain what steps you are following?

**Comment by ayomidebajo** [comment]
I downloaded the package from `brew`. Then I cloned this repo.

**Comment by ayomidebajo** [comment]
> > I downloaded the v1.4.4 and it gave me the same error.
> 
> What did you download? A package?
> 
> > I use an M1 chip and the SDK doesn't really support M1 chip users for now smiling_face_with_tear
> 
> If you build from sources, I don't see why it would not work.
> 
> Could you explain what steps you are following?

I downloaded the package from brew. Then I cloned this repo.

**Comment by JonasVautherin** [comment]
Yeah that may not work for M1. Try to build MAVSDK from sources instead :+1:

**Comment by ayomidebajo** [comment]
what package did you use to extract it?  I'm having issues using `dpkg`

**Comment by JonasVautherin** [comment]
Sorry I did not get that :confused:

**Comment by ayomidebajo** [comment]
Wrong question, sorry.

I tried building it, I just remembered that I did this method before and I kept having issues with `openssl` even after installing it and deleting it several times.

This is the error, I got when trying to build the sdk.
<img width="1197" alt="Screenshot 2022-07-26 at 22 47 47" src="https://user-images.githubusercontent.com/54250291/181118513-1c1b297c-5d3f-4ba5-a95a-8b3739dc7541.png">

**Comment by ayomidebajo** [comment]
My current version of `openssl` and the location it is installed.

<img width="643" alt="Screenshot 2022-07-26 at 22 51 31" src="https://user-images.githubusercontent.com/54250291/181118912-27a7818b-670e-4f37-a185-e32b5b178e82.png">

**Comment by JonasVautherin** [comment]
My guess is that you are lacking the SDKROOT, as defined e.g. here: https://github.com/mavlink/MAVSDK/blob/main/.github/workflows/main.yml#L514

**Comment by julianoes** [comment]
https://stackoverflow.com/questions/51761599/cannot-find-stdio-h

**Comment by julianoes** [comment]
:man_shrugging:
