### ISSUE TITLE
gps time 

### ISSUE THREAD

**Issue by O2KAN** [mavlink/MAVSDK#1882]
Hello, I am trying to get telemetry data using mavsdk. But I can not get gps time data. Do you have any idea?

**Comment by JonasVautherin** [comment]
Is that not [`timestamp_us`](https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/telemetry/telemetry.proto#L540)?

**Comment by O2KAN** [comment]
No, when i turned into the utc time. It gives random time.  Maybe I am doing something wrong

**Comment by julianoes** [comment]
I think that's not exposed at the moment. Either create a pull request to add it, or use mavlink passthrough, I'd suggest.
