### ISSUE TITLE
can't get the mission item total

### ISSUE THREAD

**Issue by valenbase** [mavlink/MAVSDK#1921]
I used the example code for uploading the mission, but the status of mission progress is right the total is always 0.
 
do you have any suggestions,thanks

**Comment by JonasVautherin** [comment]
Are you saying that the example does not work as expected, or are you using the example to upload a mission and then running your own code?

**Comment by julianoes** [comment]
Can you comment on the PX4 version that you're using and maybe provide a simple example for me to reproduce? Thanks.

**Comment by julianoes** [comment]
No follow up, closing.
