### ISSUE TITLE
Provided MAVLink headers are installed to the wrong directory

### ISSUE THREAD

**Issue by eastman-bechamo** [mavlink/MAVSDK#1924]
When supplying MAVLink C-header files and building from source, the build system installs the headers to a location that's not able to be found by `mavlink_include.h`.

Ubuntu 18.04 LTS
CMake v3.24.3

Configuration:
`cmake -B build/default -S . -DMAVLINK_DIALECT=all -DMAVLINK_HEADERS=../my_headers -H.`

Build and Install:
`sudo cmake --build build/default --target install -j8`

Resulting directory structure:
`/usr/local/include/mavsdk/plugins/mavlink_passthrough/**my_headers**/mavlink/v2.0/...`

Include line from `mavlink_passthrough/mavlink_include.h`:
`#include "mavlink/v2.0/all/mavlink.h`

---

To fix this, I edited `mavsdk/src/mavsdk/plugins/mavlink_passthrough/CMakeLists.txt`:
```
install(DIRECTORY
    ${MAVLINK_HEADERS} --> ${MAVLINK_HEADERS}/mavlink
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/mavsdk/plugins/mavlink_passthrough
)
```

---

Please let me know if I'm doing something incorrectly. If I'm not, please update that `install(...)` command in the next release. Thanks! :)

**Comment by julianoes** [comment]
Which version is that?

**Comment by eastman-bechamo** [comment]
1.4.6

**Comment by julianoes** [comment]
Hehe, look at the changelog for 1.4.7: https://github.com/mavlink/MAVSDK/releases/tag/v1.4.7 :smile:

**Comment by eastman-bechamo** [comment]
Ahh sorry! Thanks for pointing that out :smile:

**Comment by julianoes** [comment]
Although I'm confused. I think I was supposed to publish v1.4.8. I'll do that now.

**Comment by julianoes** [comment]
Ok, so I broke it a second time :astonished:

**Comment by julianoes** [comment]
Did 1.4.7 work?

**Comment by eastman-bechamo** [comment]
Unfortunately, it didn't. So to summarize:
- v1.4.6 copies that parent directory of the custom MAVLink headers instead of the `mavlink/` folder
- v1.4.7 copies the correct `mavlink/` folder, but to a location that's inaccessible to `mavlink_passthrough`

---

Configuration:
`cmake -B build/default -S . -DMAVLINK_DIALECT=all -DMAVLINK_HEADERS=../my_headers -H.`

Build and Install:
`sudo cmake --build build/default --target install -j8`

---

#### v1.4.6

Resulting directory structure:
`/usr/local/include/mavsdk/plugins/mavlink_passthrough/**my_headers**/mavlink/v2.0/...`

Include line from mavlink_passthrough/mavlink_include.h:
`#include "mavlink/v2.0/all/mavlink.h`

---

#### v1.4.7

Resulting directory structure:
`/usr/local/include/mavsdk/**my_headers**/...`

Include line from mavlink_passthrough/mavlink_include.h:
`#include "mavlink/v2.0/all/mavlink.h`

**Comment by julianoes** [comment]
Thanks, so both are wrong :thinking:

**Comment by julianoes** [comment]
Can you test this branch? https://github.com/mavlink/MAVSDK/pull/1931

**Comment by eastman-bechamo** [comment]
@julianoes Looks like that branch worked, thanks for fixing that :)

**Comment by julianoes** [comment]
Thanks for testing, I will merge that then and make a new point release.
