### ISSUE TITLE
bottom_clearance not added to ALTITUDE message.

### ISSUE THREAD

**Issue by psherk-aero** [mavlink/MAVSDK#1928]
Hi all.  The ALTITUDE message was recently added here: https://github.com/mavlink/MAVSDK/commit/849cb9a3c3bd18d21731da3b0c4fe31ca6b9d039.  Unfortunately bottom_clearance was not added.  I'd guess not a lot of folks use it, but we're working on an application that requires it.  Any chance it could be added in?

Thanks,
Peter

**Comment by CY-1992** [comment]
Hi,
Yeah I thought no one would be using it. Anyway I will try to add bottom_clearance to ALTITUDE soon.

**Comment by psherk-aero** [comment]
> Hi, Yeah I thought no one would be using it. Anyway I will try to add bottom_clearance to ALTITUDE soon.

Excellent, thank you very much.
