### ISSUE TITLE
Get entries stalls indefinitely

### ISSUE THREAD

**Issue by eastman-bechamo** [mavlink/MAVSDK#1945]
**Version**: 1.4.9
**System**: Ubuntu Bionic, 18.04LTS
**Build Info**: CMake 3.25.1

I'm having an issue where getting entries from a Cube Orange stalls indefinitely half the time. Here's some example code:
```
auto logfiles = make_shared<LogFiles>(system);
auto entries = logfiles->get_entries();
/** stalls here indefinitely */
```
This code stalls as well:
```
auto logfiles = make_shared<LogFiles>(system);
vector<Entry> entries{};
Result res{Result::Next};
auto entries_cb = [&](Result r, vector<Entry> ve)->void{
    res = r;
    if (res == Result::Success) entries = ve;
};
logfiles->get_entries_async(entries_cb);
while (res != Result::Success && res == Result::Next) { sleep_for(10us); }
```

Am I doing something wrong? For reference, I have about 40 entries on the Cube.

**Comment by eastman-bechamo** [comment]
After deleting the all of the log entries on the Cube, the code no longer stalls. The issue should be addressed though.

**Comment by JonasVautherin** [comment]
Is that running PX4 or Ardupilot?

**Comment by eastman-bechamo** [comment]
The Cube is loaded with PX4 v1.12.3

**Comment by JonasVautherin** [comment]
Sounds like a bug, yeah :laughing:

**Comment by julianoes** [comment]
I think that's fixed now.
