### ISSUE TITLE
Prefer MISSION_ITEM_INT over MISSION_ITEM

### ISSUE THREAD

**Issue by weagle08** [mavlink/MAVSDK#1952]
Previously I was using raw mavlink to communicate with a PX4 controller and it would request and accept the MISSION_ITEM_INT messages for mission uploads. I've now switched to using MAVSDK and the same PX4 controller will no longer request or accept MISSION_ITEM_INT, just MISSION_ITEM (using the pass-through plugin). Is something being set to cause this? Is there a configuration of MAVSDK I can set to allow use of MISSION_ITEM_INT?

**Comment by JonasVautherin** [comment]
What version of PX4 are you using?
