### ISSUE TITLE
mavsdk_server build fail 

### ISSUE THREAD

**Issue by dayleMG** [mavlink/MAVSDK#1956]
I want build mavsdk_server, but there had some problems.. 

I have already installed this one 
```
sudo apt-get install build-essential cmake git
```

I used this command There was a no problem
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_MAVSDK_SERVER=ON -Bbuild/default -H.
```

But this one had problems
```
cmake --build build/default -j8
```

![image](https://user-images.githubusercontent.com/63579963/211960030-f1ddc3e7-9c99-4042-be8a-50e72dbd3cf0.png)

Looks like grpc library error.. So I have installed grpc with this guide
https://grpc.io/docs/languages/cpp/quickstart/
But still error occured.

My Ubunt environment 

cmake version 3.16.3

OpenSSL 1.1.1i  8 Dec 2020

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Comment by JonasVautherin** [comment]
Is it a clean build? Looks like an issue with OpenSSL. Did OpenSSL build successfully above?

**Comment by dayleMG** [comment]
Thank you for comment @JonasVautherin 

![image](https://user-images.githubusercontent.com/63579963/212009746-74c3b826-4e60-4795-b8ac-56a815084698.png)
![image](https://user-images.githubusercontent.com/63579963/212010138-7aec7fe7-de9b-4436-8e6f-0ea7dc9e6058.png)
Umm I'm not sure about that this one is end point of OpeenSSL.

And there has warnings.
It looks like there has some problems.
![image](https://user-images.githubusercontent.com/63579963/212010474-8008ba7a-0dc4-4286-b9fa-c61210a982f8.png)
![image](https://user-images.githubusercontent.com/63579963/212010523-67f0a022-8631-4ff3-b22d-b9b411293a31.png)
![image](https://user-images.githubusercontent.com/63579963/212010586-ec9e6ece-2902-4bdd-9129-c6fda665bc94.png)

**Comment by JonasVautherin** [comment]
Can you search for "Found OpenSSL" in your log? It should find the one that you just built, not the one on your system.

Also just to be sure: are you building the `main` branch?

**Comment by julianoes** [comment]
And what sort of Ubuntu are you using?

**Comment by dayleMG** [comment]
Thank you for comment @julianoes 

This one is my Ubuntu environment.

Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

**Comment by dayleMG** [comment]
@JonasVautherin 
Yes my branch is this one ![image](https://user-images.githubusercontent.com/63579963/212207365-1c0493e9-533a-4f3a-9d68-7acf941ed94c.png)

Do you mean this log?
![image](https://user-images.githubusercontent.com/63579963/212215305-1fee706a-f52d-41b6-ba1f-5346c7a51a6e.png)

**Comment by JonasVautherin** [comment]
> Found OpenSSL: /usr/local/lib/libcrypto.so

This is wrong, it should find it in `/preneu/utm/MAVSDK/build/default/third_party/install/lib`. Can you check that you have the ssl libraries installed in `/preneu/utm/MAVSDK/build/default/third_party/install/lib`?

**Comment by julianoes** [comment]
@dayleMG and is that latest `main`?

You can do `git rev-parse HEAD` to check the commit.

**Comment by dayleMG** [comment]
@JonasVautherin 
![image](https://user-images.githubusercontent.com/63579963/212620241-a0df800b-b37b-49b8-9d43-f5e50495dbec.png)
Do you mean this one??

**Comment by dayleMG** [comment]
@julianoes 
Here you are~ 444d6b693b2d76cd594b1df074f28f468cc78f47

**Comment by JonasVautherin** [comment]
> Do you mean this one??

Yes. I don't see libcrypto and libssl there, it feels like OpenSSL failed to build/install :thinking:

**Comment by julianoes** [comment]
So what was the fix? Sorry I missed it.

**Comment by dayleMG** [comment]
@julianoes that's okay thank you
I found mavsdkserver releases artifacts. so I have just used that one. 
Thanks for helping me.

**Comment by tbago** [comment]
I use ubuntu 22.04 to build the mavsdk server. And also cannot found the openssl library. 
First the openssl library in ubuntu 22.04 is output at **build/third_party/install/lib64** dir.
And the openssl seems only generate pkg-config file and no cmake config file.

**Comment by julianoes** [comment]
@tbago please create a new separate issue and describe the steps you do and what goes wrong, thank you.
