### ISSUE TITLE
subscribe_on_new_system callback never triggered

### ISSUE THREAD

**Issue by weirdgyn** [mavlink/MAVSDK#1965]
Mavsdk mavsdk;

	Mavsdk::Configuration configuration(
		Mavsdk::Configuration::UsageType::Autopilot);

	int opt;
	uint8_t _id;

	char url[256] = DEF_URL;

	while ((opt = getopt(argc, argv, "i:u:")) != -1)
	{
	   switch (opt)
	   {
		   case 'i':
			   cout << "System id: " << optarg << endl;
			   _id = (uint8_t)atoi(optarg);
			   configuration.set_system_id(_id);
			   break;

		   case 'u':
			   cout << "Connecting on: " << optarg << endl;
			   strcpy(url , optarg);
			   break;

		   default:
			   fprintf(stderr, "Usage: %s [-i system_id] [-u connection_url]\n", argv[0]);
			   exit(EXIT_FAILURE);
	   }
   }

	mavsdk.set_configuration(configuration);

	cout << "Making connection...";

	ConnectionResult conn_result = mavsdk.add_any_connection(url);

	if (conn_result != mavsdk::ConnectionResult::Success) {
	    cout << "connection failed: " << conn_result << endl;
	    return -1;
	}
	else {
		cout << "connection created" << endl;

        mavsdk.subscribe_on_new_system(
            [&](){
        		cout << "System connected"  << endl;
            }
        );
	}

      do {
         this_thread::sleep_for(std::chrono::milliseconds(1000));
      } while(1);

The callback on `subscribe_on_new_system` is never triggered (tested with QGroundControl) ...

**Comment by JonasVautherin** [comment]
Note: this was already asked in https://discuss.px4.io/t/callback-on-mavsdk-subscribe-on-new-system-is-never-called/30564/2

**Comment by weirdgyn** [comment]
yes I started it there also...

**Comment by julianoes** [comment]
Can you give some more steps on how I should run this, and with what arguments, so that I can reproduce it?

**Comment by julianoes** [comment]
This is what you have to debug:

https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/mavsdk_impl.cpp#L296-L302

Presumably it triggers for you, even though it shouldn't.

**Comment by julianoes** [comment]
You can also debug that using `export MAVSDK_MESSAGE_DEBUGGING=1`.

**Comment by julianoes** [comment]
No follow up, closing.
