### ISSUE TITLE
when sending mavlink command MAV_CMD_USER_4  with dronekit . i'm getting command acknowledgment result 3 i.e. unsupported command.

### ISSUE THREAD

**Issue by anjaliJT** [mavlink/MAVSDK#1973]
I'm using MAV_CMD_USER_4 for custom message but it's showing unsupported.
how to use this command without error.
i'm sending it like :

vehicle.send_mavlink(vehicle.message_factory.command_long_encode(
0, 0, # target system, target component
mavutil.mavlink.MAV_CMD_DO_SET_HOME, # command
0, # confirmation
0, # param 1: 1 to use current position, 0 to use the entered values.
0, 0, 0, # params 2-4
0.0, 0.0, 0.0))

@vehicle.on_message('*')
def message(n,m,m2):
print(m2)

**Comment by JonasVautherin** [comment]
MAVSDK is not DroneKit :see_no_evil:
