### ISSUE TITLE
get the current mission data

### ISSUE THREAD

**Issue by pwl24** [mavlink/MAVSDK#1975]
Hi i am using mavsdk for the drone simulation, when the drone is flying with mission mode and detect the obstacle, i would like to know the current mission item so that i can save it as the next way points. I would like to retrieve either the current mission data or download the mission plan and get the current mission number to get the mission data. Can u help me figure out how to do it?

**Comment by julianoes** [comment]
So it sounds like you want to download the mission from the vehicle?

What about [MissionRaw::download_mission()](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_mission_raw.html#classmavsdk_1_1_mission_raw_1a2cc470785c486d1b7fdaaa2e3fbff809)?

**Comment by YalamareddyChaitanya** [comment]
How about subscribing to [mission progress](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/mission.html#mavsdk.mission.Mission.mission_progress) to get the current mission item index?
