### ISSUE TITLE
Tag `v1.4.12` removed?

### ISSUE THREAD

**Issue by ZhongRuoyu** [mavlink/MAVSDK#1978]
Hi! Homebrew contributor here. We noticed that tag `v1.4.12` was removed. Was that intended?

**Comment by julianoes** [comment]
Sorry, I pushed it by mistake. It was a duplicate of v1.4.11.

**Comment by chenrui333** [comment]
@julianoes thanks for confirming that was intended, any timeline plan for a new release any time soon (asking so that we don't have to downgrade the mavsdk, which is some painful process for homebrew side). Thanks a lot!

**Comment by julianoes** [comment]
Ok, I'll try to make a release tomorrow to make this easier for you. Thanks!

**Comment by chenrui333** [comment]
That would be much better.

**Comment by julianoes** [comment]
I've released v1.4.12, hopefully that works for you.
https://github.com/mavlink/MAVSDK/releases/tag/v1.4.12

**Comment by ZhongRuoyu** [comment]
Thanks @julianoes (and @chenrui333)!

**Comment by julianoes** [comment]
And thank you for maintaining the homebrew updates!
