### ISSUE TITLE
Failure and Shell plugins work without true result

### ISSUE THREAD

**Issue by ArtBor86** [mavlink/MAVSDK#1979]
Hi!
I tried to use Failure and Shell plugin to to inject failures (gps off) into system to test failsafes.

AUTOPILOT is Pixhawk 5x
Onboard computer RPi+ 4B
Serial connection TELEM2.

### What I want

In MAVLink Console I can send command "gps" stop and "gps start".
![e2dde5d2258f0cfd9d06ade026755a8e0c68ae64](https://user-images.githubusercontent.com/92856492/217016356-8fc1868d-aff0-4324-bb7e-fea3140a2dd2.png)

I want do this using MAVSDK C++

### What I done 
At first I tried do it by MAVSDK C++ [Failure plugin](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_failure.html).
SYS_FAILURE_EN = Enabled
```
auto failure = std::make_shared<mavsdk::Failure>(system);
auto result = failure->inject(mavsdk::Failure::FailureUnit::SensorGps,mavsdk::Failure::FailureType::Off,0);
std::cout << "Result\t" << result << std::endl;
```
and had some bad result
```
[03:15:05|Warn ] sending again after 0.5003 s, retries to do: 3  (420). (mavlink_command_sender.cpp:287)
[03:15:05|Warn ] sending again after 1.00061 s, retries to do: 2  (420). (mavlink_command_sender.cpp:287)
[03:15:06|Warn ] sending again after 1.5092 s, retries to do: 1  (420). (mavlink_command_sender.cpp:287)
[03:15:06|Error] Retrying failed (420) (mavlink_command_sender.cpp:307)
Result  Timeout
```
At second I tried do it by MAVSDK C++ [Shell plugin](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_shell.html)
```
auto shell = std::make_shared<mavsdk::Shell>(system);
auto result = shell->send("gps stop");
std::cout << "Result\t" << result << std::endl;
```
`Result Success`
**But gps didn't actually stoped.**

What can I try else?
Thanks!

**Comment by julianoes** [comment]
Some failures are not supported on the autopilot side. Feel free to make a pull request to PX4 to add missing failures.
