### ISSUE TITLE
Install interface in cmakelist

### ISSUE THREAD

**Issue by devbharat** [mavlink/MAVSDK#1981]
I am curious why some plugins(camera_server, camera_information...) specify 

```
$<INSTALL_INTERFACE:include/mavsdk>
```

while most others specify

```
$<INSTALL_INTERFACE:include>
```

in their CMakeLists.txt. I am asking because I see some weird behavior similar to [this](https://github.com/mavlink/MAVSDK/issues/1912) if I disable all plugins of the former category (`INSTALL_INTERFACE:include/mavsdk`) via plugins.txt when trying to include public headers of mavsdk after i build it as a third_party library in another project(quite similar to how mavsdk itself builds its third_party libraries).

**Comment by JonasVautherin** [comment]
Hmm it sounds like those plugins may be wrong, I don't see why they would be different :thinking:

**Comment by julianoes** [comment]
Does this work? https://github.com/mavlink/MAVSDK/pull/1982

I'm not quite sure which variant is correct, sadly.

**Comment by devbharat** [comment]
I have a feeling it needs to go the other way (keep the include/mavsdk in the plugins), or include the mavsdk headers in the plugin headers with the full path (mavsdk/mavsdk_xyz.h) but not sure, will check tomorrow!

**Comment by devbharat** [comment]
>I have a feeling it needs to go the other way (keep the include/mavsdk in the plugins), or include the mavsdk headers in the plugin headers with the full path (mavsdk/mavsdk_xyz.h) but not sure, will check tomorrow!

@julianoes yes that works. That's how i would have tried it as well, perhaps I didn't see the diff right earlier. Thanks for the fix.

**Comment by julianoes** [comment]
I changed it and force pushed. Sorry, that would have been confusing!
