### ISSUE TITLE
Loading a JSON task file

### ISSUE THREAD

**Issue by thepitho** [mavlink/MAVSDK#2000]
hello, I want to load the json task file to q ground control without connecting to the drone with a separate script on my gcs computer. How can ı do it.

**Comment by julianoes** [comment]
What's a JSON task file? Is that a QGroundControl mission plan?

**Comment by swimmingseeds** [comment]
This issue has been mentioned on **Discussion Forum for PX4, Pixhawk, QGroundControl, MAVSDK, MAVLink**. There might be relevant details there:

https://discuss.px4.io/t/import-mission-to-qgc-help/31187/2

**Comment by thepitho** [comment]
https://dev.qgroundcontrol.com/master/en/file_formats/plan.html      


yes, we can import an externally prepared plan file into q ground control. How can I turn this into an automatic script?

**Comment by thepitho** [comment]
> https://dev.qgroundcontrol.com/master/en/file_formats/plan.html

yes, we can import an externally prepared plan file into q ground control. How can I turn this into an automatic script?

**Comment by thepitho** [comment]
> This issue has been mentioned on **Discussion Forum for PX4, Pixhawk, QGroundControl, MAVSDK, MAVLink**. There might be relevant details there:
> 
> https://discuss.px4.io/t/import-mission-to-qgc-help/31187/2

yes i asked that too :)

**Comment by thepitho** [comment]
Anybody help

**Comment by julianoes** [comment]
> Anybody help

Sorry, it's the weekend here and given you don't pay me to answer you, you can't expect an answer immediately anyway.

> yes, we can import an externally prepared plan file into q ground control. How can I turn this into an automatic script?

It's still not clear to me what you're trying to do. So do you create a mission plan in QGC and then you want to upload it from MAVSDK? Or do you need help in automatically create such a script?

**Comment by thepitho** [comment]
> 

I want to upload a plan file to q ground control without a direct drone connection in a script I want andddd sorry for being impatient :(

**Comment by julianoes** [comment]
I still don't understand what you mean. Please describe the steps that you would take or give some context. You need to actually invest some time into formulating a question if you expect help from maintainers.
