### ISSUE TITLE
Move docker images away from dockerhub

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#2003]
It sounds like dockerhub is no longer hosting the docker images for free, if I read the email right:

> If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization. 

So it sounds like we need to find a way around this. Either paying, using the AWS docker registry (paid), or maybe Github Actions provides something?

**Comment by JonasVautherin** [comment]
Right, MAVSDK seems to be a Docker Free Team (same as px4io). Should we try to apply for their OSS sponsorship? https://www.docker.com/community/open-source/application/

**Comment by julianoes** [comment]
I suppose we should.

**Comment by JonasVautherin** [comment]
Or we just migrate to ghcr :sweat_smile:

**Comment by julianoes** [comment]
Nevermind, docker reversed their decision. We can leave it as is.
