### ISSUE TITLE
Problem with TCP connection to a PX4 SITL

### ISSUE THREAD

**Issue by ZhenyuShiUAV** [mavlink/MAVSDK#2027]
Hi, I'm trying to connect to a PX4 SITL through TCP as a simulator, but when I'm using the line
```c++
ConnectionResult connection_result = mavsdk.add_any_connection(argv[1]);
``` 
with the argument for tcp:
```
tcp://:4560
``` 
I got this following error
```
[02:56:01|Error] connect error: Connection refused (tcp_connection.cpp:87)
``` 
I also tried `tcp://127.0.0.1:4560`, same result. And I can connect to the PX4 through UDP.

 <br>   
 <br>   

To figure out the problem, I also tried using python code
```python
connection = mavutil.mavlink_connection('tcpin:127.0.0.1:4560')
``` 
which actually worked and I can see this line in the PX4 SITL terminal
```
INFO  [simulator] Simulator connected on TCP port 4560.
``` 
and I tried with `'tcpin:127.0.0.1:4560'` to  `'tcp:127.0.0.1:4560'`, which is 
```python
connection = mavutil.mavlink_connection('tcp:127.0.0.1:4560')
``` 
and I got the error
```
[Errno 111] Connection refused sleeping
``` 
which is similar to what I got for the C++ tcp connection.

 <br>   
 <br>   

FYI, I'm a debug build for MAVSDK, and the tcp connection line is from the takeoff_and_land example code. For what I'm working on, it would be more convenient for me to stay with C++.
Am I doing something wrong and how can I fix this?  
Thank you.

**Comment by JonasVautherin** [comment]
If `connection = mavutil.mavlink_connection('tcpin:127.0.0.1:4560')` works, then this would be the way with MAVSDK:

```
ConnectionResult connection_result = mavsdk.add_any_connection("tcp://127.0.0.1:4560");
```

You said this does not work?

**Comment by ZhenyuShiUAV** [comment]
> If `connection = mavutil.mavlink_connection('tcpin:127.0.0.1:4560')` works, then this would be the way with MAVSDK:
> 
> ```
> ConnectionResult connection_result = mavsdk.add_any_connection("tcp://127.0.0.1:4560");
> ```
> 
> You said this does not work?

No, it does not work, I tried use the argument through the terminal or write the them in the code like what you said here, none of them works. And here's the full log I received:
```
[09:54:49|Info ] MAVSDK version: v1.4.0-433-g2caa1c57 (mavsdk_impl.cpp:24)
[09:54:49|Error] connect error: Connection refused (tcp_connection.cpp:87)
Connection failed: Socket connection error
``` 

Did I miss something? I followed the example tutorial, and UDP method works. Is there something like environment variables or rules that I need to set up for this to work?

**Comment by JonasVautherin** [comment]
What is this SITL and how is it configured? Does it listen on 4560/tcp? The `tcpin` sounds counter-intuitive to me, but I assumed it was making a client, not a server. Is it right that SITL is a TCP server (and not a TCP client)?

**Comment by ZhenyuShiUAV** [comment]
Okay, I'm not entirely sure, I couldn't find out if the SITL is making a TCP server from their docs, but it looks like the `add_any_connection()` can connect to the python code with `tcpin`, and a python code with `tcp` can also talk to the one with `tcpin`, so I assume that `tcpin` makes a server, and the SITL is a client, since `add_any_connection()` can only work as a TCP client? 
I think I can use a python code as a proxy to make this work, but is there any example for setting up a TCP server with C++?

**Comment by ZhenyuShiUAV** [comment]
I tried several different things, and had it figured out. I'm using a different approach, and I'm closing this issue now, thank you.

**Comment by JonasVautherin** [comment]
> is there any example for setting up a TCP server with C++?

MAVSDK does not support being a TCP server. Only a TCP client.

**Comment by PuvaneshRam** [comment]
I'm trying to create a drone simulator using AirSim with Unreal Engine, but when I attempt to connect PX4, it gets stuck at "Waiting for simulator to accept connection on TCP port 4560." I'm using Ubuntu to connect PX4 to AirSim via TCP. If anyone has a solution, please let me know.

**Comment by julianoes** [comment]
@PuvaneshRam sounds like an AirSim and not MAVSDK issue to me.

**Comment by ne246** [comment]
@PuvaneshRam did you find a solution I'm have that issue as well

**Comment by julianoes** [comment]
If you see:

> Waiting for simulator to accept connection on TCP port 4560.

This means PX4 is not communicating correctly with AirSim. This has nothing to do with MAVSDK.

**Comment by ne246** [comment]
@julianoes 
My main issue is that mavsdk server doesnt connect to px4, while px4 is connected to airsim through a tcp connection. And my apologies for the late messages.

**Comment by julianoes** [comment]
In that case please create a new issue and give the necessary detail and context.

**Comment by ne246** [comment]
@julianoes will do I'll get back to you tomorrow!
