### ISSUE TITLE
Mission upload failed: Unsupported, exiting.

### ISSUE THREAD

**Issue by ShanbinZhang** [mavlink/MAVSDK#2029]
When running fly_missions in the example, an error message is displayed, stating Mission upload failed: Unsupported, exiting. In enum class Result: Unsupported, /**&lt; @brief Mission downloaded from the system is not supported. */    But, I don't understand what is: the Mission downloaded from the system is not supported.   

Thank you!

**Comment by JonasVautherin** [comment]
Are you using Ardupilot?

**Comment by ShanbinZhang** [comment]
> Are you using Ardupilot?

Yes, is Ardupilot , and the virtual environment is built on the development board of NVIDIA NX. In addition, I am using MAVSDK version 0.44. Because only this version can be compiled in NVIDIA NX.

The compilation steps are as follows:
1. git clone --branch v0.44.0 https://github.com/mavlink/MAVSDK.git
2. git submodule update --init --recursive
3. cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild/default -H.
4. cmake --build build/default

**Comment by JonasVautherin** [comment]
The mission plugin does not support Ardupilot yet (it would require some contributions :innocent:). For now you have to use the mission_raw plugin, which works :+1:

**Comment by ShanbinZhang** [comment]
> 
Thank you. Does that mean I can not use fly_missions in the example? I found that fly_qgc_mission have to use the mission_raw plugin. But I still didn't succeed, (./fly_qgc_mission udp://:55408)

**Comment by JonasVautherin** [comment]
Not sure, I guess it depends on the elements you have in your mission?

**Comment by ShanbinZhang** [comment]
> Not sure, I guess it depends on the elements you have in your mission?
Thank you. I have been tested successfully

**Comment by JonasVautherin** [comment]
Can you maybe list the elements that were unsupported?

Also can this issue be closed now?

**Comment by ShanbinZhang** [comment]
I used fly_ qgc_ Mission, the command I initiated earlier was incorrect. This issue can be closed now, thank you!

**Comment by xiugou798** [comment]
> I used fly_ qgc_ Mission, the command I initiated earlier was incorrect. This issue can be closed now, thank you!

I also encountered the same problem. Can you share how you use fly_qgc_mission?

Thank you!
