### ISSUE TITLE
Connect to serial and take_photo() returns TIMEOUT.

### ISSUE THREAD

**Issue by jean-dupond** [mavlink/MAVSDK#2033]
Hi everyone,

By running my code I intend to connect to the drone and simply take a photo triggering its pwm connected to the camera.

Code:

```
import asyncio

from mavsdk.camera import (CameraError, Mode)
from mavsdk import System


async def run():
    drone = System()
    await drone.connect(system_address="serial:///dev/ttyUSB0:57600")

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"-- Connected to drone!")
            break
    
    print_mode_task = asyncio.ensure_future(print_mode(drone))
    print_status_task = asyncio.ensure_future(print_status(drone))
    running_tasks = [print_mode_task, print_status_task]
    
    print("Setting mode to 'PHOTO'")
    try:
        await drone.camera.set_mode(Mode.PHOTO)
    except CameraError as error:
        print(f"Setting mode failed with error code: {error._result.result}")
    
    
    print("Taking a photo")
    try:
        await drone.camera.take_photo()
    except CameraError as error:
        print(f"Couldn't take photo: {error._result.result}")


async def print_mode(drone):
    async for mode in drone.camera.mode():
        print(f"Camera mode: {mode}")


async def print_status(drone):
    async for status in drone.camera.status():
        print(status)


if __name__ == "__main__":
    # Run the asyncio loop
    asyncio.run(run())
```

It prints out a TIMEOUT result after the set_mode and take_photo were called...

The camera is properly plugged. I can trigger it by using **pymavlink** instead.

The reason I wanna use MAVSDK is the fact that I want to get back the CAMERA_IMAGE_CAPTURED information (lat,lon,etc.) and for that I need to use the command MAV_CMD_IMAGE_START_CAPTURE, which returns an UNSUPPORTED result when I send it from pymavlink... In [this post](https://discuss.px4.io/t/trigger-camera-from-onboard/16775/2) i saw that its because only MAVSDK supports it.

The only way i can trigger my camera now is using MAV_CMD_DO_SET_CAM_TRIGG_DIST from pymavlink, but like that i cannot get the CAMERA_IMAGE_CAPTURED info...

Can anyone tell me how to succeed? Either doing it from MAVSDK or pymavlink its okay for me.

Thanks in advance!

**Comment by JonasVautherin** [comment]
Do you have a camera on the other side? Does it receive the command MAVSDK sends?

The timeout tells you that MAVSDK sent the command but did not receive an ACK. Can MAVSDK do other things with the drone, like arm/takeoff or list params?

**Comment by jean-dupond** [comment]
Hello thanks for your comments!
Indeed, there is a MAPIR Survey 3 camera plugged into the respective pwm aux output of my board (durandal).

> Can MAVSDK do other things with the drone, like arm/takeoff or list params?

Yes It does get the list of params, i.e.

**Comment by jean-dupond** [comment]
Hello thanks for your comments!
Indeed, there is a MAPIR Survey 3 camera plugged into the respective pwm aux output of my board (durandal).

    Can MAVSDK do other things with the drone, like arm/takeoff or list params?

Yes It does get the list of params, i.e.

(sorry accidentally closed the issue, i proceed to reopen)

**Comment by jean-dupond** [comment]
Perhaps, in this case i should specify the camera interface as MAVLink interface? So far it was set to Generic PWM

**Comment by JonasVautherin** [comment]
> But the camera is not a mavlink camera.

Oh, I don't really know how the setup works then. But PX4 has to behave like the mavlink camera then, and it should trigger it itself, right?

**Comment by julianoes** [comment]
Yes, PX4 would have to support https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE.

**Comment by jean-dupond** [comment]
> Yes, PX4 would have to support https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE.

Indeed, however, the command ack I get after sending the command you mention, it gives me a MAV_RESULT = 3 (UNSUPPORTED).

Here the code sending the command:

```
from pymavlink import mavutil

master = mavutil.mavlink_connection("/dev/ttyUSB0", 57600, source_system=255, source_component=190)
master.wait_heartbeat()

while True:

    # Send image trigger command

    master.mav.command_long_send(
                #master.target_system, master.target_component, mavutil.mavlink.MAV_CMD_IMAGE_START_CAPTURE, 0, 
                #float("NaN"), 
                #0, 1, 1, 
                #float("NaN"), float("NaN"), float("NaN"))

    cmd_ack = master.recv_match(type=["COMMAND_ACK"],blocking=True)

    print(cmd_ack)

```

**Comment by jean-dupond** [comment]
> > But the camera is not a mavlink camera.
> 
> Oh, I don't really know how the setup works then. But PX4 has to behave like the mavlink camera then, and it should trigger it itself, right?

Yes that is what I would expect

**Comment by julianoes** [comment]
That API is not supported by PX4. You need a camera server that talks mavlink and can answer.
