### ISSUE TITLE
How to use MAVSDK with QgroundControl

### ISSUE THREAD

**Issue by tbago** [mavlink/MAVSDK#2035]
Hi support:
I know the MAVSDK provide simple access the mavlink protocol like the following architecture：
```mermaid
flowchart LR
	MAVSDK-Python & MAVSDK-Swift-.GRPC.->MAVSDK-Server-.Mavlink protocol.->Backend
```
And I want use the MAVSDK as the following architecture:
```mermaid
flowchart LR
	QGroundControl-.Mavlink.->MAVSDK-Server-.GRPC.->Backend
```
Just like reverse the input and output protocol. Dose the **MAVSDK Server** support this architecture.

**Comment by JonasVautherin** [comment]
I am not sure I understand your question. Typically MAVSDK is used as a ground station, to communicate with a drone (is `Backend` the drone, in your first diagram?).

If you want to connect both MAVSDK and QGC to the drone, I think the typical way is to use `mavlink-router` (there are other solutions, though). Is that what you want to do?

Or do you want to write the drone side with MAVSDK, and have QGC talk to it like it would talk to a normal drone?

**Comment by tbago** [comment]
Yeah, I want to use mavlink in the drone side. And use QGC to communicate to the drone. And maybe I can make mavlink protocol implement in the drone side. But if the protocol changed I have to manual update the code. So my question is Does the MAVLink can provide the mavlink protocol parse and feedback the command as the grpc proto.

**Comment by tbago** [comment]
Amazing **MAVSDK**. I just implement one simple camera_client to call the camera_server and the communication works well.  
One more question, the camera server seems not fully complete, the [camera server](https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/camera_server/camera_server.proto) only provide basic **take photo** and **get information** implement. 
For example I found the storage info is not implement in the [camera_server_impl.cpp](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/camera_server/camera_server_impl.cpp#L422)

**Comment by tbago** [comment]
Hi support. One more thing, I have already read and try to understand the process to add interface in camera.
First need to change the [**MAVSDK-Proto**](https://github.com/mavlink/MAVSDK-Proto) proto file. Then I can use the [**generate_from_protos.sh**](https://github.com/mavlink/MAVSDK/blob/main/tools/generate_from_protos.sh) to generate new header file(e.g. camera.h、 camer.cpp). Then use the [**fix_style.sh**](https://github.com/mavlink/MAVSDK/blob/main/tools/fix_style.sh) to format the generate file.

It seems to works well. Is this the right way to update proto and generate the source code?

**Comment by julianoes** [comment]
That's right! And best is to make a PR in MAVSDK-Proto first so that we can have a discussion about the API first up.
