### ISSUE TITLE
Linking Error Compiling On RPI4 with Atomic

### ISSUE THREAD

**Issue by Bowerdred** [mavlink/MAVSDK#2050]
Hi all !

I just updated my local MAVSDK folder with the master branch and the project is no more compiling. In fact mavsdk compiles but `system_tests_runner` `unit_tests_runner` `integration_tests_runner` dont and return two errors :

```
/usr/bin/ld /usr/local/lib/arm-linux-gnueabihf/libmavsdkd.so.1.4.0 : undefined reference to « __atomic_store_8 »
/usr/bin/ld /usr/local/lib/arm-linux-gnueabihf/libmavsdkd.so.1.4.0 : référence indéfinie vers « __atomic_load_8 »
```

To make it compile, I had to modify `CMakeLists.txt` of mavsdk to force link with libatomic:

```
if((BUILD_STATIC_MAVSDK_SERVER AND ("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")) OR
    (${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "(armv6|armv7)"))
    target_link_libraries(mavsdk PRIVATE atomic)
endif()
```
Changed to 
`target_link_libraries(mavsdk PRIVATE atomic)`

In fact just adding `armv8` in the MATCHES does'nt work.

After that I also have to add the atomic link in my own `CMakeLists.txt` or the project is not compiling :
```
target_link_libraries(${PROJECT_NAME} PRIVATE
    MAVSDK::mavsdk
    ...
    atomic
)
```

Do you have any idea ?

(-latomic flag is not working)

**Comment by julianoes** [comment]
That's odd.

Do you mind checking the variable `${CMAKE_HOST_SYSTEM_PROCESSOR}` so that we can debug and fix this?

Just add:
```
message(FATAL_ERROR "host processor: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
```

And check the output.

**Comment by Bowerdred** [comment]
Here is the output of the command :

`host processor: aarch64`

**Comment by JonasVautherin** [comment]
> In fact just adding armv8 in the MATCHES does'nt work.

That would be explained by the fact that it is `aarch64` then :see_no_evil:

> Other strange thing is that mavlink is not compiled and I have to do it and install it from its own git repo whereas it was done automatically before...

Did you try a clean build?

**Comment by JonasVautherin** [comment]
They are called `arm64` in the release page

**Comment by Bowerdred** [comment]
They are not workin I have an `aarch64 - armhf` processor so I have an error : 

`error: package architecture (arm64) does not match system (armhf)`

**Comment by Bowerdred** [comment]
I think the problem is I am using a 32 bit OS so I will try with the 64 Raspbian OS to check if it's working or not !

**Comment by julianoes** [comment]
aarch64 would be the 64bit version. If you're using a 32bit OS, then it should show you armv7, I'd guess.

**Comment by julianoes** [comment]
Feel free to make a PR that fixes it for you.

**Comment by reedev** [comment]
I can confirm that this is a 32 bit OS issue which I encountered in a different project too. Exactly the same issue, resolved by linking against atomic.

**Comment by julianoes** [comment]
PRs to fix it are welcome.
