### ISSUE TITLE
Arducopter \ SITL - basic action functions

### ISSUE THREAD

**Issue by ygratz** [mavlink/MAVSDK#2096]
Hi,
I'm using MAVSDK 1.4.6.
With Arducopter \ SITL.

I try to implement very basic things, but some of them do not work for some reason:
1. action.takeoff() - I note that I must set to guided mode in the SITL, else the takeoff() is denied.
2. action.set_takeoff_altitude() it works. However its return value is wrong.
3. action.goto_location() is denied. 

Is there a workaround to these issues? 
If so please advise.
Thank you

**Comment by JonasVautherin** [comment]
I would suggest you try with the `main` branch. Some Ardupilot got contributed there, but they will only be in the `v2` release (which is not planned yet). In the meantime, the best IMO is to compile MAVSDK from source on the `main` branch :+1:.
