### ISSUE TITLE
Adding functionality without changing the MAVSDK library

### ISSUE THREAD

**Issue by ygratz** [mavlink/MAVSDK#2105]
In order to use MAVSDK in an application, I need to follow version control requirements.
To comply with this, I can take a given MAVSDK version with a given tag.
The problem is, that sometimes I do need to make changes\adjustments in the given functionality. For example: the correction in the action.takeoff() to change mode to guided.
Is there a correct way to add such functionality to my application, while not changing the given MAVSDK tagged library I'm using?
As anyone encountered this before?
If not, is it possible to add such a gateway to allow this?

**Comment by holden-zenith** [comment]
[Passthrough](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_mavlink_passthrough.html) or intercept_outgoing_messages_async/intercept_incoming_messages_async

**Comment by julianoes** [comment]
You can either fork and change but if you want to avoid that you can workaround with passthrough functionality as suggested by @holden-zenith above.

May I ask why you need to switch to Guided for Takeoff? Can you elaborate on the exact use case here?

**Comment by ygratz** [comment]
Hi [julianoes](https://github.com/julianoes),
This is regarind ArduCopter.
By switching to Guided for Takeoff (maybe this is a wrong terminology): When commanding action.takeoff() - I note that I must set to guided mode in the SITL, else the takeoff() is denied.
This issue is already resolved in main branch (add check of the flight_mode).

**Comment by ygratz** [comment]
Hi [julianoes](https://github.com/julianoes),
In main() branch - ActionImpl::takeoff_async() already includes an implementation which resolves this.
In case of ardupilot, it calls takeoff_async_apm() and it changes the flight mode to offboard, to allow takeoff.

**Comment by JonasVautherin** [comment]
@ygratz: Do I understand correctly that it is already fixed in the `main` branch, but you want to use the latest release (which does not have this fix)?

**Comment by ygratz** [comment]
Yes, that's correct

**Comment by julianoes** [comment]
Ok, I don't think this is a "bugfix" that needs to go into v1.4 though. Let's get v2 out where it's fixed.
