### ISSUE TITLE
When running MAVSDK against ArduCopter SITL the Action/goto_location function always responds with Command Denied

### ISSUE THREAD

**Issue by paulholmstedt** [mavlink/MAVSDK#2129]
I'm running a software based on latest MAVSDK code i.e. I built library on Windows 64-bit from Main branch on GitHub. I'm using two different ArduCopter SITL, one running on Linux and one directly on a Cube Orange autopilot. So far I've tested take-off, landing, MissionRaw and Offboard mode using a gamepad. All working pretty good after some tweeks. The problem is the goto_location and goto_location_async functions which always return Command Denied no matter what I do. The command is issued when ArduCopter is in "Hold" mode in the air i.e. UAV keeping its current position. Do you have any suggestion why these MAVSDK functions might not work together with ArduCopter?

**Comment by JonasVautherin** [comment]
[Here](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/action/action_impl.cpp#L451-L456) is the command that MAVSDK sends to the drone for `goto_location()`:

```c++
            command.command = MAV_CMD_DO_REPOSITION;
            command.target_component_id = _system_impl->get_autopilot_id();
            command.params.maybe_param4 = static_cast<float>(to_rad_from_deg(yaw_deg));
            command.params.x = int32_t(std::round(latitude_deg * 1e7));
            command.params.y = int32_t(std::round(longitude_deg * 1e7));
            command.params.maybe_z = altitude_amsl_m;
```

A "denied" result sounds to me like Ardupilot denied this command. Does Ardupilot support `DO_REPOSITION`? Do you have a way to check on the Ardupilot side why the command is denied?

**Comment by paulholmstedt** [comment]
I do think that do_reposition is supported by ArduCopter. Looking at the code of goto_position it looks like MAVSDK make sure Hold mode is active prior to sending the do_reposion command. It might (not 100% sure :-) ) be that if autopilot is ArduPilot it should activate Offboard (Guided) mode, see `takeoff_async_apm`, before sending do_repositon?

**Comment by julianoes** [comment]
In that case, let's switch to guided mode if ArduPilot. Good find @paulholmstedt!

**Comment by JonasVautherin** [comment]
@paulholmstedt: would you be willing to open a PR with that change? I guess we need to discriminate between px4 and ardupilot, and switch to guided if ardupilot (as Julian suggested). Another example where we do that kind of discrimination is [here](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/action/action_impl.cpp#L260-L264), for inspiration :blush:.

**Comment by paulholmstedt** [comment]
@JonasVautherin Sorry, never done any PR on GitHub so I'm a newbie in that department :-) Here is what I changed and now the `goto_location_async` works fine with ArduCopter SITL:

`void ActionImpl::goto_location_async(
    const double latitude_deg,
    const double longitude_deg,
    const float altitude_amsl_m,
    const float yaw_deg,
    const Action::ResultCallback& callback)
{
    auto send_do_reposition =
        [this, callback, yaw_deg, latitude_deg, longitude_deg, altitude_amsl_m]() {
            MavlinkCommandSender::CommandInt command{};

            command.command = MAV_CMD_DO_REPOSITION;
            command.target_component_id = _system_impl->get_autopilot_id();
            command.params.maybe_param4 = static_cast<float>(to_rad_from_deg(yaw_deg));
            command.params.x = int32_t(std::round(latitude_deg * 1e7));
            command.params.y = int32_t(std::round(longitude_deg * 1e7));
            command.params.maybe_z = altitude_amsl_m;

            _system_impl->send_command_async(
                command, [this, callback](MavlinkCommandSender::Result result, float) {
                    command_result_callback(result, callback);
                });
        };

	if (_system_impl->autopilot() == SystemImpl::Autopilot::Px4) {
        // Change to Hold mode first
		if (_system_impl->get_flight_mode() != FlightMode::Hold) {
			_system_impl->set_flight_mode_async(
				FlightMode::Hold,
				[this, callback, send_do_reposition](MavlinkCommandSender::Result result, float) {
					Action::Result action_result = action_result_from_command_result(result);
					if (action_result != Action::Result::Success) {
						command_result_callback(result, callback);
						return;
					}
					send_do_reposition();
				});
			return;
		}
    } else {
        // Change to Offboard mode first
		if (_system_impl->get_flight_mode() != FlightMode::Offboard) {
			_system_impl->set_flight_mode_async(
				FlightMode::Offboard,
				[this, callback, send_do_reposition](MavlinkCommandSender::Result result, float) {
					Action::Result action_result = action_result_from_command_result(result);
					if (action_result != Action::Result::Success) {
						command_result_callback(result, callback);
						return;
					}
					send_do_reposition();
				});
			return;
		}
    }    

    send_do_reposition();
}`

**Comment by JonasVautherin** [comment]
You can also go the "git e-mail workflow" way, I think this should be straightforward:

1. Put your changes in the top commit of your branch
2. Run `% git format-patch HEAD^1`
3. Copy the resulting `.patch` file here

Would you like to try?

**Comment by paulholmstedt** [comment]
I might have found another bug in `goto_location_async`: MAVSDK sends a CommandInt but the Frame (WGS84) might not be set correctly. According to the function documentation you give it a absolute altitude (WGS84) but ArduPilot interpret the altitude as a relative altitude instead of a WGS84 altitude. So when I call `goto_location_async` I need to subtract the launch position WGS84 altitude prior to calling the function. After that the function works correctly. Looking at the code the CommanInt is set to `MAV_FRAME frame = MAV_FRAME_GLOBAL_RELATIVE_ALT;`
I will try the "git e-mail workflow" way :-)

**Comment by paulholmstedt** [comment]
Here is a patch file for my changes. I hope I got it right :-)
NOTE: Added support for ArduPilot in Action->goto_location_async by switching to Offboard (Guided) flight mode before command (MAV_CMD_DO_REPOSITION) is sent. Also fixed altitude MSL argument Frame bug (only applied fix if ArduPilot) setting `frame = MAV_FRAME_GLOBAL` instead of default `frame = MAV_FRAME_GLOBAL_RELATIVE_ALT`. Only changes made to goto_location_async  method in action_impl.cpp.
[0001-Support-for-ArduPilot-in-Action-goto_location_async.patch](https://github.com/mavlink/MAVSDK/files/12565898/0001-Support-for-ArduPilot-in-Action-goto_location_async.patch)
