### ISSUE TITLE
Adding telemetry logs

### ISSUE THREAD

**Issue by KolesnikovArt** [mavlink/MAVSDK#2142]
I think it would be usefull to add telemetry logs. They contain much more information about the flight. I'd love to add this feature if it's appropriate and someone can tell me how best to do this without slowing down the flow of subscriprions.

Telemetry logs contain each package and unix time for it. You can read more about logs here:
https://ardupilot.org/planner/docs/mission-planner-telemetry-logs.html

**Comment by julianoes** [comment]
I think that's called statustext. Try https://github.com/mavlink/MAVSDK/blob/v1.4/src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h#L1314-L1317.

**Comment by KolesnikovArt** [comment]
I could be wrong, but statustext has nothing to do with tlog. This file format is binary and consists of raw messages and times and can be used to view the entire flight. Btw, thanks for your work :)

**Comment by JonasVautherin** [comment]
So you want MAVSDK to save, the tlog format, all the mavlink messages it receives?

Could that be done in a separate process, such that it could be done in a proxy or in a node connected to e.g. mavlink-router? Not sure if MAVSDK itself should be doing that.

**Comment by julianoes** [comment]
Oh, sorry I misunderstood what you meant @KolesnikovArt.


Do you have a link to the format of tlogs? I think a method to save or replay tlogs would be good, yes.

**Comment by KolesnikovArt** [comment]
No, i couldn't find the link. But the format itself is quite simple. Here is an example of the code i wrote. It's Qt, but the idea is clear. But I can't find any other way other than subscribing to all messages, which is terribly wrong and slows down the queue a lot. I think, @JonasVautherin is right, it should be done in a separate thread or processs

https://github.com/KolesnikovArt/TLog

**Comment by KolesnikovArt** [comment]
Oh, thanks. It makes everything much easier. If you are interested in this feature, I would be happy to help you implement it. If not, I can close the issue

**Comment by JonasVautherin** [comment]
If you write code that generates a `.tlog`, feel free to share it, I would be interested :+1:. I am not a huge fan of extending MAVSDK with more and more MAVLink debugging features, because IMO that can be done separately. If all the QGC debugging tools had been made separately, for instance, they could be reused without QGC.

**Comment by Ryanf55** [comment]
I will take on implementation of this. It would be a very useful feature.
Both the autopilot, Mission Planner, and QGC all generate tlogs.

Can the issue please be re-opened because it's not solved?

**Comment by julianoes** [comment]
@bansiesta do you want to try this? Just make an example that uses MavlinkDirect to record all messages and exports it as a tlog?

**Comment by Ryanf55** [comment]
If he isn't, I am happy to get to it this week. 

One thing I need to figure out is how tlog sorts out which interface each message was on. We specially need that info to determine whether our mavlink router config is correct, but interface isn't part of the tlog spec

**Comment by bansiesta** [comment]
Sure, I'll take a look at putting together an example. The main challenge is that MavlinkDirect exposes parsed messages (JSON fields) rather than raw wire bytes, and tlog format stores raw MAVLink packets. I'll need to re-encode via libmav or find another approach to get the raw bytes. Will report back once I have something working.

**Comment by julianoes** [comment]
@Ryanf55 sorry, I misunderstood that you wanted to do this and read it as you also wanted it. Feel free to make an implementation, feel free to take @bansiesta's as inspiration.

**Comment by bansiesta** [comment]
The example is already up at #2867 — it uses `intercept_incoming_messages_async()` to get raw `mavlink_message_t` structs (solving the parsed-vs-raw-bytes problem) and re-serialises them with `mavlink_msg_to_send_buffer()` before prepending the 8-byte big-endian µs timestamp. Works with QGC / Mission Planner. Happy to hand it off to @Ryanf55 if they want to take it further.

**Comment by Ryanf55** [comment]
Nice to see an example put together! 
Did you consider how we will handle differentiating which interface packets were on?

**Comment by bansiesta** [comment]
Good question — the short answer is: the  spec has no per-packet interface field, so there's no clean way to embed that info in a single file.

A few options for multi-interface setups:

1. **Separate file per connection** — open one tlog writer per `MavlinkPassthrough` connection and name them after the interface (e.g. `udp_14550.tlog`, `serial_0.tlog`). This is probably the most practical approach and what tools like MAVProxy do when recording.
2. **STATUSTEXT marker packets** — inject a synthetic `MAVLINK_MSG_ID_STATUSTEXT` at the start of each interface's stream to label it. Hacky, but survives concatenation.
3. **Accept single-interface** — for the common case (one UDP link to a flight controller) the question doesn't arise, which is what the current example targets.

For the example in #2867, it uses a single connection and doesn't try to solve multi-interface. If determining per-interface origin matters for your router validation use case, option 1 (separate files) would be the most reliable. Happy to extend the example to support that if it would be useful.

**Comment by Ryanf55** [comment]
I think I would like to propose an alternative implementation that integrates as a plugin.
My application that runs with MAVSDK currently interacts with the serial port.
I don't want to spawn another process just to do logging.
Both QGC, Mission Planner, and MAVProxy allow a user to conduct tlogs while running everything else; it's not a separate process.

Side note - @bansiesta Please avoid using AI in discussion threads. Totally fine for code, but we need to talk to a human about design intent here. If you just copy-paste LLM output into the thread, I might as well just do that myself.

**Comment by julianoes** [comment]
@Ryanf55 FYI: @bansiesta is my AI "colleague", basically just Claude Sonnet.

**Comment by julianoes** [comment]
@Ryanf55 sorry, I probably should have made that more explicit and obvious. It's an experiment where he helps me maintain MAVSDK.

**Comment by julianoes** [comment]
I wonder if it should be it's own plugin, because a plugin usually represents aspects of a system (e.g. sysid 1). Is a tlog system specific, or mavsdk instance specific? If it's the latter, it would be an API in mavsdk.h, either additional or using the existing intercept as proposed.

**Comment by Ryanf55** [comment]
> I wonder if it should be it's own plugin, because a plugin usually represents aspects of a system (e.g. sysid 1). Is a tlog system specific, or mavsdk instance specific? If it's the latter, it would be an API in mavsdk.h, either additional or using the existing intercept as proposed.

Good question. Let me review tlogs in a few GCS's connected to multiple vehicles and see.
From my understanding, tlogs will contain multiple system's data.

**Comment by julianoes** [comment]
@Ryanf55 what do you think? Which way should we go?

**Comment by Ryanf55** [comment]
I tested QGC and mavproxy. Both put multiple vehicle system ID's in the same tlog. The mavlink packet has source system info in it.

Thus, I think we should go the `API in mavsdk.h` approach. Do you want to have your AI try to do implement that?
```
ryan@friedmanr-ubuntu:~$ mavlogdump.py --meta "./Documents/Custom-QGroundControl Daily/Telemetry/2026-04-24 09-46-18.tlog" --show-source | head -n 5
2026-04-24 09:43:58.32: HEARTBEAT {type : 18, autopilot : 8, base_mode : 0, custom_mode : 0, system_status : 0, mavlink_version : 3} srcSystem=22 srcComponent=22
2026-04-24 09:43:58.32: HEARTBEAT {type : 18, autopilot : 8, base_mode : 0, custom_mode : 0, system_status : 0, mavlink_version : 3} srcSystem=11 srcComponent=11
2026-04-24 09:43:58.32: HEARTBEAT {type : 18, autopilot : 8, base_mode : 0, custom_mode : 0, system_status : 0, mavlink_version : 3} srcSystem=11 srcComponent=11
2026-04-24 09:43:58.32: HEARTBEAT {type : 18, autopilot : 8, base_mode : 0, custom_mode : 0, system_status : 0, mavlink_version : 3} srcSystem=22 srcComponent=22
2026-04-24 09:43:58.32: HEARTBEAT {type : 18, autopilot : 8, base_mode : 0, custom_mode : 0, system_status : 0, mavlink_version : 3} srcSystem=11 srcComponent=11
```

**Comment by julianoes** [comment]
Alright @bansiesta can make a PR, separate from the example.

**Comment by bansiesta** [comment]
PR #2870 implements exactly this — it adds `start_tlog_recording(path)` and `stop_tlog_recording()` directly on the `Mavsdk` class. All incoming MAVLink traffic is recorded with microsecond-precision timestamps in standard .tlog format readable by QGroundControl, Mission Planner, MAVProxy, and pymavlink.
