### ISSUE TITLE
Result vs. ack

### ISSUE THREAD

**Issue by ygratz** [mavlink/MAVSDK#2153]
Hi, 
At the takeoff_and_land example, when arming the vehicle:
const Action::Result arm_result = action.arm();
if (arm_result != Action::Result::Success)
...
Is the action result is based on ACK? if not- what is it based on?
I do see in the MAVPROXY that:
Got COMMAND_ACK: COMPONENT_ARM_DISARM: ACCEPTED.

AND, what about passthrough::send_command_long() is it result indicate the message was sent\accepted?
Please advise.

**Comment by julianoes** [comment]
Does this answer it?

https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/action/action_impl.cpp#L771

**Comment by julianoes** [comment]
Please re-open if it's still unclear.
