### ISSUE TITLE
"Sending message failed" on main branch - Cannot Upload Missions on PX4 or ArduPilot Systems

### ISSUE THREAD

**Issue by OliverHeilmann** [mavlink/MAVSDK#2163]
I have a CI pipeline which builds mavsdk and runs some various sitl tests, checking that I can connect to hardware, send missions etc. My runs on Wednesday were working as expected and thereafter, I have been getting lots of issues with sending missions to PX4 and ArduPilot flight controllers (see below).

<img width="1035" alt="Screenshot 2023-10-20 at 17 00 15" src="https://github.com/mavlink/MAVSDK/assets/49697817/1c693f6a-e1b4-4a5e-aa0c-8089f9b4621a">

Has anyone encountered this? Hope there is a fix because it is quite a big failure mode to fail sending missions... For those wondering why I am not using a stable release version, there are some important fixes which have not been released yet and are in main currently.

Thanks for your help and let me know if you need more detail!

# Edit
When I use the below commit version on Main, my code works as before so it looks like something in the last two pull requests has caused this issue.
`git checkout 76862be25267b8e1500a66223495c8cc23d7548a`

**Comment by JonasVautherin** [comment]
> When I use the below commit version on Main, my code works as before so it looks like something in the last two pull requests has caused this issue.

Oh good catch, thanks for reporting this, that's helpful!

**Comment by JonasVautherin** [comment]
What's the status here? Is that now fixed?

**Comment by OliverHeilmann** [comment]
Sorry for the delay, just tested the latest main branch (debug) and the PX4 sitl environment works again i.e. mavlink messages are sending/ receiving correctly which is great.

I did also test the latest branch with ArduPilot sitl and got the following issue:
<img width="1074" alt="Screenshot 2023-12-02 at 14 00 06" src="https://github.com/mavlink/MAVSDK/assets/49697817/7f604fe3-5b8b-4c32-9799-c13101c6a160">

You can see that the `AUTO` mode change was getting rejected in flight. Happy for this issue to be closed and a new one opened for this new problem though!

**Comment by julianoes** [comment]
There was no more follow up. I'm assuming everything is working.
