### ISSUE TITLE
Odemetry Telemetry message subscription does not persist after reboot

### ISSUE THREAD

**Issue by BestITUserEUW** [mavlink/MAVSDK#2167]
Hey,
  i'm currently trying to integrate mavsdk::Telemetry::Odometry into my application. I'm using the following to subscribe to Odometry telemetry:

Subscription:

> telemetry->set_rate_odometry(1);
telemetry->subscribe_odometry(
    [&](mavsdk::Telemetry::Odometry odometry)
    {
        ....
    });

Reboot Command:

> mavsdk::MavlinkPassthrough::CommandLong{
            sysId,
            compId,
            static_cast<uint16_t>(MAV_CMD::MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN),
            1.0F,
            0.0F,
            0.0F,
            0.0F,
            0.0F,
            0.0F,
            0.0F};

When rebooting PX4 Autopilot i stop getting messages  from Odometry subscription. When restarting the application i receive Odometry again. Do i have to set message rates again after each reboot ?

PX4 Version: 1.13.3
Mavsdk Version: v1.4.6
System: Quadcopter

**Comment by JonasVautherin** [comment]
> Do i have to set message rates again after each reboot ?

I don't know exactly how this is implemented on the PX4 side, but it could well be. MAVSDK [sends the MAV_CMD_SET_MESSAGE_INTERVAL command](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/core/system_impl.cpp#L1211C23-L1211C51), which is specified [here](https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL).

I don't see anything in the specs that say that it should or should not be persistent, it only mentions a default value:

> 0: request default rate (which may be zero).

I would personally just request it every time, to be sure. An alternative would be to check how the default value is set on the PX4 side (maybe it's a param?), and you could set it yourself for your drone.

**Comment by julianoes** [comment]
Yes, you have to set it each time.

If you want to have messages sent out at all times, make sure to use the correct telemetry mode on the PX4 side (see param: https://docs.px4.io/v1.14/en/advanced_config/parameter_reference.html#MAV_0_MODE).

Or set up a `mavlink stream ...` command in the PX4 startup, either by modifying the startup scripts directly, or from SD card: https://docs.px4.io/main/en/concept/system_startup.html#starting-additional-applications-extras-txt
