### ISSUE TITLE
Source file cmake gtest cannot find cmakelist.txt

### ISSUE THREAD

**Issue by YuZhe-CN** [mavlink/MAVSDK#2255]
Hi
Compiling the source files and building the library, cmake shows an error about not finding cmakelist.txt in gtest.
![image](https://github.com/mavlink/MAVSDK/assets/58207455/53f0e5d1-3af1-4692-8775-071a1700d136)

![image](https://github.com/mavlink/MAVSDK/assets/58207455/7e4b4cfe-d22b-4f8a-980c-600885668149)
But cloning the repository and building it is all fine.

**Comment by JonasVautherin** [comment]
It really looks like the submodule was not cloned properly. Though I see that you run `git submodule update --init --recursive` :thinking:. Can you check what is in `src/third_party/gtest` after that?

Also you can do it in one line:

```
RUN git clone https://github.com/mavlink/MAVSDK.git --recursive
```

**Comment by YuZhe-CN** [comment]
In the beginning, I was trying to build the library with the source code on the release. After the error showed up, I checked the contents inside the gtest folder. And it is empty. 
![image](https://github.com/mavlink/MAVSDK/assets/58207455/17bbd271-88ce-47f0-838c-767a08e2dbbe)
After Trying cloning the git repository directly and updating the submodule, the result is shown below. 
![image](https://github.com/mavlink/MAVSDK/assets/58207455/7e6dab8d-7f20-4e5f-9960-e611b4cde72d)

**Comment by JonasVautherin** [comment]
Awesome!
