### ISSUE TITLE
Trying to compile with make

### ISSUE THREAD

**Issue by YuZhe-CN** [mavlink/MAVSDK#2265]
Hi support, 

I'm trying to compile my program that uses MAVSDK with Makefile, but the linker cannot find references to some functions. 
```Makefile
CXX		  := g++
CXX_FLAGS := -Wall -Wextra -std=c++17 -ggdb

BIN_DIR := ../bin 
SRC_DIR := ../src/cc
BUILD_DIR := .
HEAD_DIR := ../src/h

SRC_FILES := $(shell find $(SRC_DIR) -name '*.cpp')
OBJ_FILES := $(SRC_FILES:%=$(BUILD_DIR)/%.o)

INCLUDE	:= -Iinclude -Ilib \
 -I/usr/local/include/mongocxx/v_noabi \
 -I/usr/local/include/bsoncxx/v_noabi \
 -I/usr/include/mavsdk \
 -I/usr/local/include/mavsdk\
 -I/usr/include/jsoncpp \
 -I$(HEAD_DIR)
LIB		:= lib

LIBRARIES	:= -lboost_system -lpthread -lcrypto \
-lssl -lmongocxx -lbsoncxx 
LDLIBS := -L/usr/lib
EXECUTABLE	:= main

all: $(BIN)/$(EXECUTABLE)

run: clean all
	clear
	./$(BIN)/$(EXECUTABLE)

$(BIN)/$(EXECUTABLE): $(OBJ_FILES)
	$(CXX) $(CXX_FLAGS) $(INCLUDE) -L$(LIB) $^ -o $@ $(LIBRARIES) $(LDLIBS)

$(BUILD_DIR)/%.cpp.o: %.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXX_FLAGS) $(INCLUDE) -L$(LIB) -c $< -o $@ $(LIBRARIES) $(LDLIBS)

clean:
	-rm $(BIN)/*
	-rm $(OBJ_FILES)

.PHONY: print
print: $(wildcard $(SRC_DIR)/*.cpp)
	ls -la  $?
```
Compile result:
![image](https://github.com/mavlink/MAVSDK/assets/58207455/2aad7ccd-f478-40e4-b1bd-4034e317ee22)

AMDP_Server.cpp file include:
![image](https://github.com/mavlink/MAVSDK/assets/58207455/07ec8c86-c9ea-4c49-beef-26ade6efd9e6)
And where the functions are invoked
![image](https://github.com/mavlink/MAVSDK/assets/58207455/a03220e1-d698-4a69-8331-be6826703728)

I don't know where I am doing wrong. 

Thank you

**Comment by JonasVautherin** [comment]
May I ask why you don't use CMake? Mostly out of curiosity :innocent:

**Comment by YuZhe-CN** [comment]
Jajajaja because I'm used to and does not have much practice with cmake. But I finally managed to resolved it. It is because the mavsdk library name stored in /usr/lib is named like libmavsdk.so.VERSION. And the linker needs that the name is libmavsdk.so only. So I created a symbolic link to the library and now It is all fine. 

Thank you.
