### ISSUE TITLE
QtCreator adding librrary

### ISSUE THREAD

**Issue by TkaczykHub** [mavlink/MAVSDK#2278]
Can someone explain me how to add library to use in Qt Project App?

**Comment by JonasVautherin** [comment]
I am sorry but this has nothing to do with MAVSDK, does it? :thinking: 

I suggest you look into the QtCreator documentation (maybe they have a forum or something, too?).

**Comment by TkaczykHub** [comment]
Is it impossible?

**Comment by julianoes** [comment]
I'm sure it's possible. Mavsdk is like any other C++ dependency. Are you building your Qt project using qmake or cmake?

**Comment by TkaczykHub** [comment]
yes, im using cmake and i need help to import all mavsdk to my files, cause i want to make app in Qt with MAVSDK possibiliets. can you help me to make "mavsdk.h" works?

**Comment by julianoes** [comment]
If you're using cmake you should add it as any of the examples:
https://github.com/mavlink/MAVSDK/blob/main/examples/takeoff_and_land/CMakeLists.txt
