### ISSUE TITLE
How to disable all Debug messages on COUT ?

### ISSUE THREAD

**Issue by mseidler1** [mavlink/MAVSDK#2292]
Hello,
I'm programming on Debian (x64) with C++. How to disable in MAVSDK 2.0 all debug messages on COUT? Building a RELEASE version has no impact like stated in the documentation. I personally don't get the log_callback.h API working.

Thanks for the support!

Cheers Michael

**Comment by julianoes** [comment]
Hi, I made an example. Let me know if that works for your case.
https://github.com/mavlink/MAVSDK/pull/2293
