### ISSUE TITLE
Why MAVSDK doesnt create a new system for telemetry radios?

### ISSUE THREAD

**Issue by nioroso-x3** [mavlink/MAVSDK#2302]
Seems very arbitrary, for my application I want to show the radio stats and was wondering why system 3 (wfb-ng mavlink stream stats) wasnt being detected until I found an if statement that seems to just drop these packets.

The if block is in lines 384 to 389 in src/mavsdk/core/mavsdk_impl.cpp.

**Comment by julianoes** [comment]
Here is a link:
https://github.com/mavlink/MAVSDK/blob/8fb12e35a38a8aaf0ca2e5273f9e97ba3e59eb75/src/mavsdk/core/mavsdk_impl.cpp#L384-L389

Right, it's to avoid having a system around, just for that. But I suppose we can add that back in towards v3.
