### ISSUE TITLE
 MAVSDK SERVO_OUTPUT_RAW(36) DATA Receive

### ISSUE THREAD

**Issue by boytimo** [mavlink/MAVSDK#2347]
Hello,

I have a question. I am using the Pixhawk Orange Cube Plus and MAVSDK to communicate between the Pixhawk and a Raspberry Pi. While I have successfully received GPS data, roll, pitch, yaw angles, and various other data, I have not been able to receive servo data. The following code is causing an error:

```
const Telemetry::Result set_rate_actuator_output_result = telemetry.set_rate_actuator_output_status(1.0);
if (set_rate_actuator_output_result != Telemetry::Result::Success)
{
    std::cerr << "Setting rate failed: " << set_rate_actuator_output_result << '\n';
    return 1;
}
The error code is MAVLink: info: No ap_message for mavlink id (375) (system_impl.cpp:243), and when I connect the Pixhawk to Mission Planner and inspect the MAVLink messages, the list shows:

Vehicle 1
 L Comp 1 MAV_COMP_ID_AUTOPILOT1
  L SERVO_OUTPUT_RAW (2.0 Hz, #36) 48Bps
    L port 0 system.Byte
    L servo1_raw 0 system.UInt16
    ...
    L time_usec x system.UInt32
```
According to the official documentation, the SERVO_OUTPUT_RAW ID has been replaced by ACTUATOR_OUTPUT_STATUS. Is it possible to modify the MAVSDK code to receive SERVO_OUTPUT_RAW? If not, are there any other solutions?

Thank you very much.

![Screenshot_2](https://github.com/mavlink/MAVSDK/assets/114569363/84bd42a6-0480-4797-91dd-ca0a67d512c2)

**Comment by julianoes** [comment]
PX4 or ArduPilot? And which version?

The message you're trying to set the rate is: [ACTUATOR_OUTPUT_STATUS](https://mavlink.io/en/messages/common.html#ACTUATOR_OUTPUT_STATUS).

Presumably ArduPilot doesn't implement that one?

Could you just use MavlinkPassthrough instead for this one?

**Comment by boytimo** [comment]
I solved it with MavlinkPassthrough. Thank you for your reply.
