### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Dustcendant** [mavlink/MAVSDK#2349]
Hello,
I'm trying to connect a custom flight simulator to the MavSDK using python.
I use MavSDK-python for the control, simply trying to connect via python code:

drone = System()
await drone.connect(system_address="__input_addres__")

The simulator has its own server for connection implemented in pymavlink library with which there are no problems. I am able to connect to the custom server using a controller made with pymavlink library.
The problem is I am unable to establish working connection to the MavSDK, neither via the python wrapper or the server when run from console.
Basically this is the most the most I can get out of the server:

[04:39:22|Info ] MAVSDK version: v2.12.0 (mavsdk_impl.cpp:26)
[04:39:22|Info ] Waiting to discover system on udp://:14540... (connection_initiator.h:20)
[04:39:24|Debug] New system ID: 255 Comp ID: 0 (mavsdk_impl.cpp:720)
[04:39:29|Info ] heartbeats timed out (system_impl.cpp:265)

But funnily enough, it's not like there's nothing I get, when I connect to the server, I'm receiving heartbeat and ping, the server responds to ping and heartbeat.
This is the code I use as the base for the mavlink server:

mavConn = mavutil.mavlink_connection('udp:localhost:14540')

This code can be used as both the custom server AND the client, it connects, receives messages and also sends without any issue.
After the connection is initiated, I send heartbeat and ping, both get response but the mavsdk_server never progresses beyond the third line of the log I copied.
In code, the function "connect" never ends making me believe the mavsdk_server doesn't recognize the connection as valid system.

My question is, what do I have to send to the mavsdk_server for it to recognize my custom server as valid system.

Thank you for the support.

**Comment by julianoes** [comment]
What port is your custom thing sending MAVLink to? Or what port is it listening on?

**Comment by Dustcendant** [comment]
> What port is your custom thing sending MAVLink to? Or what port is it listening on?

I run the custom server on port 14540 by default but tested with different ports too (both IP and port can be set manually to anything via in-app configurator).
Each time the same result, my custom server receives pings and heartbeats, the mavsdk_server responds to both pings and heartbeats but never returns past the connect function.
It may also be that pings don't return from my custom server?
Though I don't see any ping response neither in pymavlink docs or the library source.
For the record, pymavlink creates a simple udp socket server from pythons socket library, while MavSDK python wrapper runs precompiled c++ application that creates and manages the server, from what I saw in the source, also simple socket server.

**Comment by julianoes** [comment]
Ok, so presumably your custom server doesn't look enough like an autopilot to MAVSDK.

```
 [04:39:24|Debug] New system ID: 255 Comp ID: 0 (mavsdk_impl.cpp:720)
```

This looks like default pymavlink which is wrong in my opinion, or at least doesn't make much sense. The compid of a source can't be 0. (Only the target can be 0 meaning all.)

Your server needs to have compid 1 to be an autopilot.

**Comment by Dustcendant** [comment]
> Ok, so presumably your custom server doesn't look enough like an autopilot to MAVSDK.
> 
> ```
>  [04:39:24|Debug] New system ID: 255 Comp ID: 0 (mavsdk_impl.cpp:720)
> ```
> 
> This looks like default pymavlink which is wrong in my opinion, or at least doesn't make much sense. The compid of a source can't be 0. (Only the target can be 0 meaning all.)
> 
> Your server needs to have compid 1 to be an autopilot.

That did the trick.
But I cant find much documentation on the component IDs, I presume the IDs are defined somewhere.
Could you please send me a link to anything or point me somewhere I could find it?

Thanks for the help, I'll be closing this issue tomorrow.

**Comment by julianoes** [comment]
They used to be listed here: https://mavlink.io/en/messages/common.html

but in a recent reorg were moved to https://mavlink.io/en/messages/standard.html but that page doesn't seem to be working.

The source is here though:
https://github.com/mavlink/mavlink/blob/d65952bacc02c4a5a1ed8249be73e6a66fa800ab/message_definitions/v1.0/minimal.xml#L293-L708

**Comment by Dustcendant** [comment]
> They used to be listed here: https://mavlink.io/en/messages/common.html
> 
> but in a recent reorg were moved to https://mavlink.io/en/messages/standard.html but that page doesn't seem to be working.
> 
> The source is here though: https://github.com/mavlink/mavlink/blob/d65952bacc02c4a5a1ed8249be73e6a66fa800ab/message_definitions/v1.0/minimal.xml#L293-L708

Thanks a lot
