### ISSUE TITLE
Bug in battery.cpp example

### ISSUE THREAD

**Issue by KarthiAru** [mavlink/MAVSDK#2371]
Hi,

When examining the [battery.cpp](https://github.com/mavlink/MAVSDK/blob/main/examples/battery/battery.cpp#L92-L93) example while utilizing the SITL (Gazebo) setup, I observed that the battery statistics were not being updated for the default 'System 1'. Instead, these updates were associated with a new 'System 245'. 

Upon further investigation, I discovered that the values for `mavlink_address.system_id` and `mavlink_address.component_id` were not correctly defined, which appears to be the root cause of the issue.

![image](https://github.com/user-attachments/assets/b3397ae1-2891-4766-a449-cf8bf8a135a8)
![image](https://github.com/user-attachments/assets/76dc5abd-7446-4a22-8059-04fccae3d065)

```
battery/build   main  ./battery udp://:14540                                   
[05:56:12|Info ] MAVSDK version: v2.12.2-60-ga428ee99 (mavsdk_impl.cpp:28)
[05:56:12|Warn ] Connection using udp:// is deprecated, please use udpin:// or udpout:// (cli_arg.cpp:28)
[05:56:12|Info ] New system on: 127.0.0.1:14580 (with system ID: 1) (udp_connection.cpp:179)
[05:56:12|Debug] New system ID: 1 Comp ID: 1 (mavsdk_impl.cpp:705)
[05:56:12|Debug] Component Autopilot (1) added. (system_impl.cpp:367)
[05:56:12|Warn ] Vehicle type changed (new type: 2, old type: 0) (system_impl.cpp:218)
[05:56:12|Debug] Discovered 1 component(s) (system_impl.cpp:510)
Sending battery status with System ID: � and Component ID: �
armed
Sending battery status with System ID: � and Component ID: �
armed
Sending battery status with System ID: � and Component ID: �
```

**Comment by julianoes** [comment]
Aha, do yo mind making a pull rquest to fix it?

**Comment by julianoes** [comment]
Actually, it depends on your use case. If this is a component sending battery information to an autopilot (think of it as a sensor), it's correct.

**Comment by KarthiAru** [comment]
@julianoes, thank you for the clarification. Specifically, I'm puzzled about where the "System 245" and "Component 190" ids originated in my case, as there is no mention of it in the code or the logs. Additionally, when attempting to log the values for mavlink_address.system_id and mavlink_address.component_id, I get a "?" instead of the actual ids. Hence the confusion. Could you shed some light on this?

**Comment by julianoes** [comment]
245/190 is the default of MAVSDK when it is configured as a ground station. You're right for this example we should probably make it something like 1/180 (for [MAV_COMP_ID_BATTERY](https://mavlink.io/en/messages/common.html#MAV_COMP_ID_BATTERY)).
