### ISSUE TITLE
MAVSDK server example--not able to arm

### ISSUE THREAD

**Issue by Wudka-HTWBerlin** [mavlink/MAVSDK#2397]
Hey, I´m trying to setup the server example as well as trying to intgarted into my drone setup.

Here is the problem. As I´m runnig the example the drone can not be armed. The health status is not valid as it is shown in the commandline output.

![grafik](https://github.com/user-attachments/assets/38437be5-6ac2-4ee5-badb-f4aa5a704418)

So what should I do.

Thank you for your help

**Comment by julianoes** [comment]
It doesn't have global position, so presumably no GPS. Are you flying indoors?

**Comment by Wudka-HTWBerlin** [comment]
> It doesn't have global position, so presumably no GPS. Are you flying indoors?
So then the description of the exmple is wrong. There they said that by using the server they do not need to have a connection to  a flightcontroller. 

Anyway, for the drone setup I have a connection to a GPS and even there the health state of global position is false.
Therfore, I checked the states in QGC there aren´t any false states.

Is it possible to set health state true?

**Comment by julianoes** [comment]
Oh sorry, this is using the autopilot server, I missed that.

Ok, so then the question is what is configured in that server.

Are you publishing all of these?
https://github.com/mavlink/MAVSDK/blob/2de3994cb09eb021fb38929bd61b9d03874d79d8/examples/autopilot_server/autopilot_server.cpp#L142-L146

**Comment by Wudka-HTWBerlin** [comment]
I used the example and tried to start it.
I did not change anything.

**Comment by julianoes** [comment]
Ok, it could be related to my recent cleanup/refactor in `main`. You could also try the v2.12 branch to check if that's what it broke.

I will look into this at some point in the future but don't have time at this moment.

**Comment by Wudka-HTWBerlin** [comment]
Ok, I will check that tomorrow and get back to you  with the results.

**Comment by Wudka-HTWBerlin** [comment]
So I checked it and I´m now able to run the example with the v2.12 branch as well as running it on my companion.
Works fine.

Thx for your help. :)

**Comment by julianoes** [comment]
Great, thanks @Wudka-HTWBerlin . I'm just going to leave this issue open given it seems like it might be broken on main.

**Comment by julianoes** [comment]
I've tested the autopilot_server example in main and it's working for me. It's far from feature complete but it does arm for me and prevent to take off.

A few fixes while I was at it are here: https://github.com/mavlink/MAVSDK/pull/2423
