### ISSUE TITLE
Internal team process

### ISSUE THREAD

**Issue by mrpollo** [mavlink/MAVSDK#240]
- [ ] Who are the team members?
- [ ] How often do we meet?
- [ ] How do we set direction for the project?

**Comment by JonasVautherin** [comment]
Should we address that tomorrow during the call? =)

**Comment by JonasVautherin** [comment]
What do we do with that? I believe we should either do something, or close it :-).

**Comment by hamishwillee** [comment]
I think it is worth the discussion because I don't know (all) the answers. Am I a member of the team? Are you having meetings to discuss all this stuff that I wasn't invited to. [crying like a baby].

**Comment by julianoes** [comment]
> Am I a member of the team?

Yes, definitely.

> Are you having meetings to discuss all this stuff that I wasn't invited to. [crying like a baby].

Yes, but the time we settled at which is latish for Europe and early for the West coast is not exactly great for Australia, so we assumed it wouldn't be worth it for you.

**Comment by julianoes** [comment]
This is old, closing. For anyone wanting to get in touch with the MAVSDK maintainer team, just create an issue and the maintainers will respond.
