### ISSUE TITLE
Device API needs documentation

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#243]
As I understand it, from #188 `Device` has changed such that it supplies a "generic MAVLink service API" that plugins can use to make the queries and acknowledgements they need for specific message types, and to register/unregister plugins with the device - is that correct?

If so, then the API methods are part of the public API and need to be documented.

**Comment by julianoes** [comment]
A `Device` is now a `System` and has an API page: https://mavsdk.mavlink.io/develop/en/api_reference/classmavsdk_1_1_system.html :heavy_check_mark:
