### ISSUE TITLE
gazebo in px4-gazebo-headless container not run

### ISSUE THREAD

**Issue by liuchuanping** [mavlink/MAVSDK#2443]
i run a docker container  eg: "docker run --rm -it jonasvautherin/px4-gazebo-headless:1.15.1"  , then i exec into the container, i found gzserver self default is running ,so i run command eg: " gzclient --verbose" , 
, but i didn't see anything gazebo ui comeout l , how to resolve the problem , some errors like this: 

![image](https://github.com/user-attachments/assets/0e834cd0-be4f-4579-8cfa-a1cac79b84f1)

when i run  gzclient --verbose , gzclient self exit,

1. how to run gazebo in the px4-gazebo-headless container 
2. how to download the iris modes,  ever i  failed to download the iris model , i  maby remember the iris models website links not found, 
How to ensure that the model can be downloaded from the latest download address? I want to use the drone model. I am working on a flight control program related to mavsdk, which requires QGC/px4/mavsdk

**Comment by julianoes** [comment]
Please post this issue in https://github.com/PX4/PX4-Autopilot. This does not look like a MAVSDK issue.
