### ISSUE TITLE
Having issues with installing mavsdk.

### ISSUE THREAD

**Issue by Kareem3807** [mavlink/MAVSDK#2456]
Hey, I'm on Mac,

I used the install instructions on the website , using homebrew.

I installed mavsdk via home-brew and that went sucessfully, however when trying to compile anything using Mavsdk (I'm using the battery example). I get this error:

Mavlink.cpp:6:10: fatal error: 'mavsdk/mavsdk.h' file not found
#include <mavsdk/mavsdk.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

**Comment by julianoes** [comment]
What's your cmake file to get mavsdk?

**Comment by Kareem3807** [comment]
How can I check? As far as I know I haven't done anything with Cmake, my apologies, I'm new to this. what should I do?

**Comment by julianoes** [comment]
How are you building your C++ file?

**Comment by Kareem3807** [comment]
I'm using Vscode and just compiling the file like so:

g++ -arch arm64 -std=c++17 Mavlink.cpp

**Comment by julianoes** [comment]
Ok, when you compile C++, you need to learn how to set include directories (so it finds the includes) and link to libraries. That's a general C++ concept, and nothing MAVSDK specific.

MAVSDK tries to be like any other library, and supports specifically cmake (and its find_package).

Best to just look at how examples are built, e.g.:
https://github.com/mavlink/MAVSDK/blob/main/examples/gimbal/CMakeLists.txt

There is also some documentation for this:
https://mavsdk.mavlink.io/main/en/cpp/guide/toolchain.html#build-definition-file---cmakeliststxt

Unfortunately, it's out of date, so linking to the plugins is no longer needed, so:

```
target_link_libraries(your_executable_name
    MAVSDK::mavsdk             # needed!
    MAVSDK::mavsdk_action      # not needed, remove this!
)

```
