### ISSUE TITLE
MAVSDK v2.14.0 regression: getParamInt not working correctly anymore (it works on v2.13.0)

### ISSUE THREAD

**Issue by rayw-dronesense** [mavlink/MAVSDK#2477]
## Repro steps

1. Use v2.14.0
2. Connect an ArduPilot aircraft (can even be the SITL sim)
3. Use the API `param.getParamInt("RTL_ALT")` to fetch the Return to Launch Altitude

### Expected result

The value is fetched successfully

### Actual result

```
io.mavsdk.param.Param$ParamException: TIMEOUT: Timeout
```

## Notes

Works just fine after reverting to v2.13.0

**Comment by julianoes** [comment]
Oh, dear, I fixed one thing but broke another. Thanks for reporting this.

**Comment by julianoes** [comment]
I can reproduce this.
