### ISSUE TITLE
Guide/example for creating plugins

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#41]
Dronecore is the officially supported layer for providing access to PX4, via MAVLink (of course there are other integration points, like the RTSP bridge). We're expecting others to extend the API via plugins, for example, to add support for peripherals that interact with the system via custom MAVLink messages.

We need a simple but realistic example of a plugin and an associated guide that shows how it works/what you need to do to write one.

**Comment by julianoes** [comment]
More than 3 years later this will be covered by mavlink/MAVSDK-docs#219.
