### ISSUE TITLE
Determine exact time fly

### ISSUE THREAD

**Issue by dangviethieu-hntv** [mavlink/MAVSDK#454]
Hi all, I have mission with take photo action each waypoints. How I can determine exact time when drone fly from waypoint to waypoint and time drone do action at waypoint?

**Comment by julianoes** [comment]
@dangviethieu-hntv this would depend on the mission speed that you set. Given the distance you could then calculate the approximate time required to fly it.

**Comment by dangviethieu-hntv** [comment]
@julianoes How about determine time drone do action at waypoint, sir? (take photo, control gimbal)

**Comment by hamishwillee** [comment]
> How about determine time drone do action at waypoint, sir? (take photo, control gimbal)

That would depend on the gimbal and camera you are using. 

Does it matter? You're never going to be able to get a perfect estimate - and omitting these is likely to be a relatively small fraction of your error.

**Comment by dangviethieu-hntv** [comment]
Thanks you. But I thinks why don't we use 1 boolean parameter, and set true when drone start action at waypoints, and set false when it finish, so we can calculate time drone fly and time drone doing action. That is my ideal, thank you very much !!!

**Comment by hamishwillee** [comment]
I think the best you can do is monitor MISSION_ITEM_REACHED, which the autopilot must send whenever it gets to a new item. This is not timestamped, but it would give you a good approximation.

**Comment by julianoes** [comment]
This should probably happen on the autopilot side and not the MAVSDK side.
