### ISSUE TITLE
Have a method in Action to check if vehicle is armable

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK#65]
Essentially, a method to return the same information as `bool dronecore::Telemetry::health_all_ok() const`

**Comment by julianoes** [comment]
I would say this is sort of fixed by #462.

**Comment by hamishwillee** [comment]
Only if `arming_allowed()` / `takeoff_allowed` are exposed in public API?

**Comment by julianoes** [comment]
That's a good idea actually!

**Comment by hamishwillee** [comment]
@julianoes I'm full of them. Can you drive it? :-)

**Comment by julianoes** [comment]
Ha! Ok I'll put it on my list.

**Comment by julianoes** [comment]
Implemented: https://github.com/mavlink/MAVSDK/blob/68c8041bc911e31f99c8575a042d6b3919583b39/src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h#L417.
