### ISSUE TITLE
Enable cross compilation for devices like Raspberry Pi

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#680]
It would be nice if we could cross-compile artefacts for architectures like armv7 and arm64, e.g. for Raspberry Pis.

The build artefacts should also be generated in CI and attached to the releases like the current .deb and .rpm files.

@JonasVautherin you have already tried this with cross complation docker containers, right?

**Comment by JonasVautherin** [comment]
Yep I'm working on that!

**Comment by julianoes** [comment]
This can be built using this command:

```
docker run --rm dockcross/linux-armv7 > ./dockcross-linux-armv7
chmod +x ./dockcross-linux-armv7
./dockcross-linux-armv7 cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_BACKEND=ON -DBUILD_SHARED_LIBS=OFF -Bbuild/linux-armv7 -S.
./dockcross-linux-armv7 cmake --build build/linux-armv7 -j 8
```

Missing step is CI.
