### ISSUE TITLE
No support of VTOL TAKEOFF and LAND in mission plugin

### ISSUE THREAD

**Issue by dangviethieu** [mavlink/MAVSDK#804]
Hello guys
I get problems while test fly_qgc_mission function with vtol-simulator(https://docs.deltaquad.com/simulator.html)
![Image 2019-07-16 at 1 15 02 PM](https://user-images.githubusercontent.com/14278358/61518913-e21bba00-aa34-11e9-89c7-9507ae1c1fec.png)
Anyone can help me with it? I check in mission_impl.cpp and it seems no support for MAV_CMD_NAV_VTOL_TAKEOFF and MAV_CMD_NAV_VTOL_LAND command.
I want know why? please help me? Thanks 
<img width="1251" alt="Screen Shot 2019-07-19 at 2 57 16 PM" src="https://user-images.githubusercontent.com/14278358/61519313-ce248800-aa35-11e9-86f2-20fbd1661806.png">

**Comment by julianoes** [comment]
Correct, the `mission` plugin does not support VTOL items yet.

If you need support for that you would have to use the `mission_raw` plugin for now.

**Comment by dangviethieu** [comment]
@julianoes thank you for reply.
We does haven't example for mission_raw yet?
In mission plugin, we have MissionItem class for setup waypoint, but mission_raw is don't have.
So how to we can create mission use mission_raw plugin?

**Comment by julianoes** [comment]
Yes, with mission_raw you basically get a default MAVLink style mission and there is no easy types or examples to use.

**Comment by julianoes** [comment]
Alternatively, you could add support for VTOL actions to the `mission` plugin and that way enable it.

**Comment by itrigitech** [comment]
Any progress on that? I also need to add support for VTOL missions.

Checking the code i see how the mission plugin is implemented and for example it checks if the first mission item is a waypoint. I thought that this item could be a takoff. In fact it stops downloading the mission if is not a waypoint. 

Do you know why is that? I don't understand why this check exists.

**Comment by hamishwillee** [comment]
@itrigitech Adding to old items is frowned upon. The right way to handle this would be to raise in discussion board or slack and link here.

That said, I have responded to your query in https://github.com/mavlink/MAVSDK/issues/938

The current check is waypoint because the plugin doesn't support takeoff items. It should IMO.

**Comment by JonasVautherin** [comment]
> The current check is waypoint because the plugin doesn't support takeoff items. It should IMO.

Agreed. And @julianoes does, as well:

> Alternatively, you could add support for VTOL actions to the mission plugin and that way enable it.

We are open for contributions :blush:
