### ISSUE TITLE
How to connect Px4 on SITL

### ISSUE THREAD

**Issue by friendbaby** [mavlink/MAVSDK#811]
The Firmware version is 1.8.0dev.
PX4 SITL listen  on UDP port 14560, MAVSDK in UDP Mode  listen one port too.
So, How to connect Px4 on SITL ?

**Comment by julianoes** [comment]
Does this diagram help?
https://dev.px4.io/v1.8.2/en/simulation/#sitl-simulation-environment

QGC usually listens on UDP port 14550, MAVSDK or MAVROS listen on UDP port 14540.

**Comment by friendbaby** [comment]
> Does this diagram help?
> https://dev.px4.io/v1.8.2/en/simulation/#sitl-simulation-environment
> QGC usually listens on UDP port 14550, MAVSDK or MAVROS listen on UDP port 14540.

I have seen this diagram, and I test result is different it.

the pix4  is not connect to QGC(udp port 14550), it is :

pix4(udp 14560) <---->Simulator<---->QGC(udp 14550).

So if remove Simulator , the pix4 can not connect to QGC.

In actually, my target is write a new Simulator with MAVSDK.  I need  connect pix4 udp active,just like jMAVSim.

**Comment by julianoes** [comment]
Ah that's an idea. You can do that. I think you just need to connect to UDP port 14560 instead of 14550.

**Comment by DiegoGLagash** [comment]
Is there any support for v1.9.2 and setting a TCP port?

**Comment by julianoes** [comment]
Please re-open if this is not working as intended.
