### ISSUE TITLE
Recover optical flow camera video using mavsdk

### ISSUE THREAD

**Issue by shrit** [mavlink/MAVSDK#842]
Is it possible to recover the video from the optical flow camera using mavsdk??
If so, How can do this in SITL gazebo ??

**Comment by julianoes** [comment]
I don't think it's obtainable via MAVLink from SITL Gazebo, however, from PX4Flow connected via MAVLink you could select some test mode (I don't remember how) and then you should receive https://mavlink.io/en/messages/common.html#ENCAPSULATED_DATA).

**Comment by julianoes** [comment]
The question has been answered, so I'm closing this.
