### ISSUE TITLE
mavsdk::MavlinkPassthrough instructions out of date?

### ISSUE THREAD

**Issue by imfatant** [mavlink/MAVSDK#846]
I'm trying to get mavsdk::MavlinkPassthrough to work:
https://mavsdk.mavlink.io/develop/en/api_reference/classmavsdk_1_1_mavlink_passthrough.html

The instructions seem to be out of date?

**Comment by hamishwillee** [comment]
Hi @imfatant ,
I updated the documentation, so in about 5 minutes these should match what the source code says.
