### ISSUE TITLE
Building MavlinkPassthrough with cmake?

### ISSUE THREAD

**Issue by imfatant** [mavlink/MAVSDK#851]
The guide says the following regarding building MavlinkPassthrough with make:

"This plugin is not included in the build by default. To add it make ENABLE_MAVLINK_PASSTHROUGH=1 is required."

What about when building with cmake?

**Comment by JonasVautherin** [comment]
Does `-DENABLE_MAVLINK_PASSTHROUGH=ON` do it? That's what we do [in Jenkins](https://github.com/mavlink/MAVSDK/blob/develop/Jenkinsfile#L24).

**Comment by imfatant** [comment]
Yes, that works. Thanks.
