### ISSUE TITLE
Support for incoming connections (ex from GCS)

### ISSUE THREAD

**Issue by pklapperich** [mavlink/MAVSDK#852]
It would be nice if the SDK supported inbound connections as well as outbound connections. It would them be possible use the SDK to make a proxy application that sits between a drone and a groundstation. This could be useful for things like logging, injecting packets into the stream, etc.

**Comment by JonasVautherin** [comment]
I wonder if that would not be more something for [mavlink-router](https://github.com/intel/mavlink-router/). What's your opinion on that?

**Comment by pklapperich** [comment]
After a glance, I think that'll suite my needs out of box. And it's reassuring to see from [https://github.com/intel/mavlink-router/issues/164](issue 164) that it'll be around long term.

**Comment by JonasVautherin** [comment]
Awesome!
