### ISSUE TITLE
Unable to access IMU data on terminal using MAVSDK

### ISSUE THREAD

**Issue by deepak-1530** [mavlink/MAVSDK#854]
I am not able to access IMU data of pixhawk over USB. I am able to access the data using MAVROS but not using the telemetry class provided in mavsdk.

**Comment by JonasVautherin** [comment]
Can you elaborate a bit? What did you try exactly? How did you setup mavsdk, and what functions did you call?

**Comment by deepak-1530** [comment]
I tried one of the sample codes (offboard_control) and in that i tried to display angular velocity data but i was getting zero. I also tried the IMU data but it again showed zero. 
 Telemetry::AngularVelocityBody v;
Telemetry::IMUReadingNED acc;
When i use mavros  and run the px4.launch file, then i can subscribe to the /imu/data topic and see the orientation and stuff but not without it.

**Comment by JonasVautherin** [comment]
So you managed to create a connection to the drone? Does something else work, like arming and taking off, for instance?

**Comment by deepak-1530** [comment]
I connected the pixhawk to my PC over USB. I was not able to arm it. But I only wanted to access the IMU data.

**Comment by JonasVautherin** [comment]
> But I only wanted to access the IMU data.

Ok, but that's interesting information. If nothing works, then it is maybe not an issue specific to the IMU data :sweat_smile:.

Can you show me the output of MAVSDK when you connect it to the pixhawk? Also, does MAVSDK work with SITL for you?

**Comment by deepak-1530** [comment]
![px4](https://user-images.githubusercontent.com/43798160/64990864-4bf9f800-d8ee-11e9-997a-78a6a8baa751.jpg) 
This is the output after I run the px4.launch command in mavros. I have not tried MAVSDK with SITL yet.

**Comment by deepak-1530** [comment]
![image](https://user-images.githubusercontent.com/43798160/64992066-c0359b00-d8f0-11e9-9063-e5cab7ef2af4.png)
This is the output of mavros stuff (px4.launch). I have not tried MAVSDK with the SITL yet.

**Comment by deepak-1530** [comment]
![px4_](https://user-images.githubusercontent.com/43798160/64992219-11458f00-d8f1-11e9-9be2-7a4b87089331.jpg)
This is the output of mavros(px4.launch). I have not tried mavsdk on the sitl yet.

**Comment by JonasVautherin** [comment]
I trust you when you say that it works with MAVROS. I want to see the output of MAVSDK in order to help you understand what is going wrong :+1:

**Comment by julianoes** [comment]
@deepak-1530 by the way, you can copy console output using Ctrl+Shift+C. It makes it much more readable (and searchable).

**Comment by deepak-1530** [comment]
![Screenshot from 2019-09-17 20-45-31](https://user-images.githubusercontent.com/43798160/65133304-02112f00-da20-11e9-8300-d6dd18024608.png)
This is the MAVSDK example code output. I just displayed the acceleration data

**Comment by julianoes** [comment]
@deepak-1530:

What code are you using to print the accel values?

**Comment by deepak-1530** [comment]
Telemetry::IMUReadingNED IMU;
std::cout<<telemetry->health()<<std::endl; 
int i = 1;
while(i>0)
{
std::cout<<" acceleration is (down) "<<IMU.acceleration.down_m_s2<<std::endl;
sleep_for(milliseconds(100));
}

This is the piece of code that I added in the takeoff_and_land.cpp example code to see the IMU readings.

**Comment by JonasVautherin** [comment]
Hmm so you create an `IMU` object, and then print its value. That object was initialized with zeros as default values, so that's what you're printing.

**Comment by julianoes** [comment]
@deepak-1530 you are printing an uninitialised struct.

You should do something like this:

```
while (true)
{
    Telemetry::IMUReadingNED imu = telemetry->imu_reading_ned();
    std::cout<<" acceleration is (down) "<<imu.acceleration.down_m_s2<<std::endl;
    sleep_for(milliseconds(100));
}
```

For more examples, see:
https://github.com/mavlink/MAVSDK/blob/develop/src/integration_tests/telemetry_sync.cpp
