### ISSUE TITLE
traceMode feature like DJI

### ISSUE THREAD

**Issue by dangviethieu** [mavlink/MAVSDK#897]
Hello all. Please help me with the question.
In DJI, they have the mission mode: traceMode, that is smooth transition between waypoints.
https://developer.dji.com/onboard-api-reference/structDJI_1_1OSDK_1_1WayPointInitSettings.html#a0f2517fd1775e16675921b8b62b919ef
And this is demo: https://gyazo.com/a724d2ba73a51775cc6c37ed23dc29b1
So I wonder that MAVSDK is have the feature same that?

**Comment by julianoes** [comment]
What exactly are you trying to achieve? If you need to stop at a waypoint in order to take a picture, yes we already have that. You can use `fly_through = false` and set a camera action, e.g. `TAKE_PICTURE`.

**Comment by dangviethieu** [comment]
@julianoes Thank you very much about quickly reply!
![traceMode](https://user-images.githubusercontent.com/14278358/68923754-a0680980-07b1-11ea-8372-891b2392108d.png)
I mean the DJI has the flights mode like: drone will not reach at waypoint, it will fly through the curve corner with the distance as input value. It look like the VTOL mode.

**Comment by julianoes** [comment]
Aha, I think now I understand. We have several waypoint smoothing mechanisms. I don't know much about it but I'm hoping that @bresch can help here.

**Comment by dangviethieu** [comment]
Hi @bresch @julianoes . I try research about **smoothing mechanisms** of several waypoint.
<img width="485" alt="Screen Shot 2019-11-21 at 3 52 54 PM" src="https://user-images.githubusercontent.com/14278358/69322817-2683c480-0c78-11ea-80c9-b2f831c3c32c.png">
I found that we can use the key: **acceptance_radius_m**, it look like curve corner when drone reach at waypoints. I try changed it, but the result isn't as expected.
Please help me understand more about smoothing mechanisms if we have it? Thanks you very much !!!

**Comment by bresch** [comment]
@julianoes @dangviethieu if you want a nicer curve, you need to increase the acceptance radius more than 3m, you could try larger values (10m for example).

**Comment by julianoes** [comment]
Closing this as the behaviour can be achieved as @bresch writes above in https://github.com/mavlink/MAVSDK/issues/897#issuecomment-594594163.
