### ISSUE TITLE
How to program multiple vehicles in C++?

### ISSUE THREAD

**Issue by KrisRadowski** [mavlink/MAVSDK#915]
I saw the examples for single vehicle in the guide and I wonder how to modify them to work with multiple vehicles. I understand how "takeoff an land" example works, but I'm just a beginner and I'm not sure how to make it works with multiple vehicles

**Comment by julianoes** [comment]
Have you seen this example?
https://github.com/mavlink/MAVSDK/blob/develop/example/multiple_drones/multiple_drones.cpp

**Comment by KrisRadowski** [comment]
Duh, that wasn't in the guide -_- 
Anyway, thanks for this example and sorry for making problems :)
