### ISSUE TITLE
 C:/MAVSDK/build/default/third_party/jsoncpp failed to build!

### ISSUE THREAD

**Issue by maerad7** [mavlink/MAVSDK#929]
<img width="642" alt="1" src="https://user-images.githubusercontent.com/34180175/70604612-42a5d080-1c3c-11ea-9414-2e3fd3306ed3.PNG">
<img width="273" alt="2" src="https://user-images.githubusercontent.com/34180175/70604617-446f9400-1c3c-11ea-97eb-151f7a3d3940.PNG">

 C:/MAVSDK/build/default/third_party/jsoncpp failed to build! 

I get an error Why? The installation process is as follows.

cmdline => visual studio 2019 x86_x64 cross tools command prompt and admin permision
cd MAVSDK
git checkout master ma
git submodule update --init --recursive
cmake -G "Visual Studio 16 2019" -DBUILD_SHARED_LIBS=ON -DENABLE_MAVLINK_PASSTHROUGH=1 -Bbuild/default -H.

I created some files in Unicode for installation. 

cmake --build build/default --config Debug
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=install -Bbuild/default -H.

ERROR

OS : WINDOWS10

**Comment by JonasVautherin** [comment]
hmm, "patch step" is failing. Is that a clean build? I see messages like "CMake doesn't need to be rerun...".

Can you try a clean build? On Windows it may be that the patch step sometimes fails if it is not a clean build... :thinking:

**Comment by lizn520** [comment]
same problem in Visual Studio 2017, 
Output: 
2>Creating directories for 'jsoncpp'
2>Building Custom Rule D:/SoftWareDevelopement/Ruigan/MAVSDK/third_party/jsoncpp/CMakeLists.txt
2>Performing download step (git clone) for 'jsoncpp'
2>-- Avoiding repeated git clone, stamp file is up to date: 'D:/SoftWareDevelopement/Ruigan/MAVSDK/build/release/third_party/jsoncpp/jsoncpp/src/jsoncpp-stamp/jsoncpp-gitclone-lastrun.txt'
2>Performing update step for 'jsoncpp'
2>Performing patch step for 'jsoncpp'
2>CUSTOMBUILD : error : patch failed: CMakeLists.txt:148
2>CUSTOMBUILD : error : CMakeLists.txt: patch does not apply
2>CUSTOMBUILD : error : patch failed: src/lib_json/CMakeLists.txt:69
2>CUSTOMBUILD : error : src/lib_json/CMakeLists.txt: patch does not apply

**Comment by JonasVautherin** [comment]
Same question as above :sweat_smile:. Is that a clean build? Doesn't seem like a clean build:

> Avoiding repeated git clone, stamp file is up to date

**Comment by julianoes** [comment]
If this is still an issue, please re-open.
