### ISSUE TITLE
Airspeed data missing on telemetry

### ISSUE THREAD

**Issue by itrigitech** [mavlink/MAVSDK#937]
I've been looking for the airspeed data in telemetry and doesn't seem to be implemented. For some vehicles this information is important depending the fly mode so I was thinking to modify the telemetry plugin to add this information because I need it. The mavlink message is VFR_HUD. 
If I want to contribute how should I start?

**Comment by JonasVautherin** [comment]
I see that [VFR_HUD](https://mavlink.io/en/messages/common.html#VFR_HUD) is defined as follows:

```
Metrics typically displayed on a HUD for fixed wing aircraft.

airspeed     | float    | m/s | Current indicated airspeed (IAS).
groundspeed  | float    | m/s | Current ground speed.
heading      | int16_t  | deg | Current heading in compass units (0-360, 0=north).
throttle     | uint16_t | %   | Current throttle setting (0 to 100).
alt          | float    | m   | Current altitude (MSL).
climb        | float    | m/s | Current climb rate.
```

For information, we have a [`GroundSpeedNed`](https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/telemetry/telemetry.proto#L34) that emits [`SpeedNed`](https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/telemetry/telemetry.proto#L201-L206) events.

I guess VFR_HUD is only emitted for fixed wing or VTOL (in fixed wind mode) aircrafts? Or is it also emitted for multicopters (I guess multicopers typically don't compute their airspeed, do they?)?

**Comment by julianoes** [comment]
> I guess VFR_HUD is only emitted for fixed wing or VTOL (in fixed wind mode) aircrafts? Or is it also emitted for multicopters (I guess multicopers typically don't compute their airspeed, do they?)?

Good question. We'd have to try it out.

Anyway, you can add it to the telemetry plugin, and I think the `VFR_HUD` message is the one to use.

**Comment by itrigitech** [comment]
I don't know how it works but i could imagine the message sent if the airspeed sensor is present, anyway in Mavlink documentation says "Metrics typically displayed on a HUD for fixed wing aircraft." 
Anyway, testing with gazebo multicopter i see the VFR_HUD message sent so i imagine it depends more in the fact of the sensor being present or not.

I think it's a good idea to add it to the telemetry plugin then. For some drones this information is very important so i will try to add it when i have time.

**Comment by itrigitech** [comment]
I'm starting to add the message to the plugin. I'm thinking how to structure the information. The important information in this message is the airspeed for me but the rest of the information we have it already from other messages. I really don't know if there is any difference or not in this information received but i guess not.

What would you do with that? add all the information as it comes ? o just take the information needed? just the airspeed

**Comment by JonasVautherin** [comment]
> I really don't know if there is any difference or not in this information received but i guess not.

In that case I would not repeat it.

> the rest of the information we have it already from other messages

I believe we get `groundspeed`, `heading` and `alt`, but not `airspeed`, `throttle` and `climb`. Is that correct? In that case I guess we could add the new ones only :+1:.
