### ISSUE TITLE
Naming clash with Windows API

### ISSUE THREAD

**Issue by jehontan** [mavlink/MAVSDK#953]
In the `ConnectionResult` enum, the value `SOCKET_ERROR` clashes with a preprocessor definition in `WinSock2.h`, causing weird substitutions and compile failure.

Propose to change the name `SOCKET_ERROR` to something else.

**Comment by jehontan** [comment]
Similar issue with `ERROR` in `Mission::Result`, clashes with `ERROR` defined in `wingdi.h`.

**Comment by julianoes** [comment]
Right, that's correct. However, we could usually work around it by doing `#undef`:

https://github.com/mavlink/MAVSDK/blob/164e5fe719608898b009364dbd870846d5163bfc/src/core/tcp_connection.h#L13

Does that not work for you?

**Comment by jehontan** [comment]
I'm using it with another library that uses winsock, so the #undef would mess with the library.

In any case it's probably best practice to avoid clashes with the Windows API.

**Comment by julianoes** [comment]
I think we can use `CamelCase` instead of `ALLCAPS` soon in the future.

**Comment by JonasVautherin** [comment]
Agreed, and that would also follow [this guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#enum5-dont-use-all_caps-for-enumerators).

I started working on auto-generating C++, and I believe that will be a good opportunity to do that :+1:.

**Comment by julianoes** [comment]
Fixed after auto-generation and #1075.
