### ISSUE TITLE
Install PX4

### ISSUE THREAD

**Issue by q7frkz** [mavlink/MAVSDK#968]
Hello,

I have pixhawk2.1 with ardupilot 4.0.0 and i don't find how to install PX4.
For the moment, impossible to be detected by QGC, when i link by USB Pixhawk to QGC, pixhawk boot without any problem and QGC does not do anything.
With mission planner, Pixhawk is detected, i choose "Load custom firmware", I select "px4_fmu-v3_default.px4" (v1.10.0) I just download, installation finish with everything OK.

When I restart pixhawk, it's detected direcly but lose connection after 4-5 seconds.
Sound about 2-3 bips by seconds.

I have exactly this message on QGC:
https://github.com/PX4/Firmware/issues/10507
I'm on QGC 3.5.6

I don't know what to do

Thank you

**Comment by JonasVautherin** [comment]
Hello :blush:!

It seems to me that this is not a MAVSDK-related question. I think you should ask it on [PX4 discuss](https://discuss.px4.io/) or, if you don't know where to ask, you can go on [PX4 Slack](https://slack.px4.io/) :+1:.

Closing here, but feel free to ask if you have more questions!
