### ISSUE TITLE
mavshell example is not starting shell

### ISSUE THREAD

**Issue by shrit** [mavlink/MAVSDK#980]
Hello,

I have just compiled mavshell example. After discovering the system I am getting this error in the real px4 shell:
`pxh> ERROR [mavlink] Failed to start shell (-1)`

On the mavshell side only  a blocking terminal
PX4 version 1.9.2
Any ideas??

**Comment by shrit** [comment]
I suppose that this shell does not work in SITL simulation as it requires Nuttx to be used instead of Linux

**Comment by JonasVautherin** [comment]
Exact, it does not run on SITL. Did you try on NuttX?

**Comment by shrit** [comment]
I no longer have access to Pixhawk hardware.
Unless if there is a magic virtual machine for running SITL with PX4 inside Nuttx

**Comment by JonasVautherin** [comment]
Right. Well, closing that, as I know for a fact that mavshell only runs in NuttX :slightly_smiling_face:. Feel free to reopen if necessary!
