### ISSUE TITLE
Request to add interface message to get gimbal angle in mavsdk

### ISSUE THREAD

**Issue by jiejiezhang** [mavlink/MAVSDK#995]
Hi @julianoes 　In the API documentation in mavsdk, there is no interface to get the gimbal angle (pitch / roll / yaw). Can we add an interface to get the gimbal angle ? (edited)

**Comment by hamishwillee** [comment]
FYI @julianoes is away for a few days.

**Comment by JonasVautherin** [comment]
I think that [`camera_attitude_quaternion_async`](https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/telemetry/include/plugins/telemetry/telemetry.h#L1071) gives you what you want, doesn't it? The camera attitude is related to the gimbal angle, right?

**Comment by julianoes** [comment]
@JonasVautherin is correct. `camera_attitude` is data from `MOUNT_ORIENTATION` which is the gimbal attitude.
